<?php

declare(strict_types=1);

$package = dirname(__DIR__, 2);
require_once $package . '/scripts/lib/ported.php';
require_once $package . '/scripts/lib/parse.php';
require_once $package . '/scripts/lib/join.php';
require_once $package . '/scripts/lib/emit.php';
require_once $package . '/scripts/lib/enums.php';

it('emits a PHP interface plus projected-method trait for every bound GIR interface', function (): void {
    $ext = gtkExtRoot();
    $parsed = parseBoundMethods($ext);
    $joined = joinAnnotationsToGir($parsed['methods'], $ext . '/scripts/gir');

    $bound = [];
    foreach ($joined['classes'] as $classPath => $info) {
        if (($info['kind'] ?? '') === 'interface') {
            $bound[] = (string) substr((string) strrchr($classPath, '\\'), 1);
        }
    }
    expect($bound)->not->toBeEmpty();

    $dir = dirname(__DIR__, 2) . '/src/Contracts';
    foreach ($bound as $short) {
        $path = $dir . '/' . $short . '.php';
        expect(is_file($path))->toBeTrue();
        $source = (string) file_get_contents($path);
        expect($source)->toContain('GENERATED by scripts/generate.php')
            ->and($source)->toContain("interface {$short}")
            ->and($source)->toContain("trait {$short}Methods");
    }
});

it('has GtkBox and GtkEntry implement the bound GTK interfaces they declare', function (): void {
    $box = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Gtk/GtkBox.php');
    expect($box)->toContain('\\Jovian\\Bindings\\Gtk\\Contracts\\GtkOrientable')
        ->and($box)->toContain('\\Jovian\\Bindings\\Gtk\\Contracts\\GtkOrientableMethods');

    $entry = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Gtk/GtkEntry.php');
    expect($entry)->toContain('\\Jovian\\Bindings\\Gtk\\Contracts\\GtkEditable')
        ->and($entry)->toContain('\\Jovian\\Bindings\\Gtk\\Contracts\\GtkEditableMethods');
});

it('supplies trait methods that are exactly one extension call', function (): void {
    $source = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Contracts/GtkOrientable.php');
    expect($source)->toContain('ExtGtkOrientable::setOrientation($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation))')
        ->and($source)->toContain('ExtGtkOrientable::getOrientation($this->handle)');
});
