<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gdk;

use Gtk\Gdk\GdkGLContext\GdkGLContext as ExtGdkGLContext;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GdkGLContext extends GObject
{
    public function getAllowedApis(): int
    {
        return ExtGdkGLContext::getAllowedApis($this->handle);
    }

    public function getApi(): int
    {
        return ExtGdkGLContext::getApi($this->handle);
    }

    public function getDebugEnabled(): bool
    {
        return ExtGdkGLContext::getDebugEnabled($this->handle);
    }

    public function getDisplay(): ?GObject
    {
        return Registry::box(ExtGdkGLContext::getDisplay($this->handle));
    }

    public function getForwardCompatible(): bool
    {
        return ExtGdkGLContext::getForwardCompatible($this->handle);
    }

    /**
     * @return array{major: mixed, minor: mixed}
     */
    public function getRequiredVersion(): array
    {
        return ExtGdkGLContext::getRequiredVersion($this->handle);
    }

    public function getSurface(): ?GObject
    {
        return Registry::box(ExtGdkGLContext::getSurface($this->handle));
    }

    public function getUseEs(): bool
    {
        return ExtGdkGLContext::getUseEs($this->handle);
    }

    /**
     * @return array{major: mixed, minor: mixed}
     */
    public function getVersion(): array
    {
        return ExtGdkGLContext::getVersion($this->handle);
    }

    public function isLegacy(): bool
    {
        return ExtGdkGLContext::isLegacy($this->handle);
    }

    public function isShared(GdkGLContext $other): bool
    {
        return ExtGdkGLContext::isShared($this->handle, $other->handle);
    }

    public function makeCurrent(): static
    {
        ExtGdkGLContext::makeCurrent($this->handle);

        return $this;
    }

    public function setAllowedApis(int $apis): static
    {
        ExtGdkGLContext::setAllowedApis($this->handle, $apis);

        return $this;
    }

    public function setDebugEnabled(bool $enabled): static
    {
        ExtGdkGLContext::setDebugEnabled($this->handle, $enabled);

        return $this;
    }

    public function setForwardCompatible(bool $compatible): static
    {
        ExtGdkGLContext::setForwardCompatible($this->handle, $compatible);

        return $this;
    }

    public function setRequiredVersion(int $major, int $minor): static
    {
        ExtGdkGLContext::setRequiredVersion($this->handle, $major, $minor);

        return $this;
    }

    public function setUseEs(int $useEs): static
    {
        ExtGdkGLContext::setUseEs($this->handle, $useEs);

        return $this;
    }

    public static function clearCurrent(): void
    {
        ExtGdkGLContext::clearCurrent();
    }

    public static function getCurrent(): ?GObject
    {
        return Registry::box(ExtGdkGLContext::getCurrent());
    }
}
