<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GAction\GAction as ExtGAction;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GAction extends GObject implements \Jovian\Bindings\Gtk\Contracts\GAction
{
    use \Jovian\Bindings\Gtk\Contracts\GActionMethods;

    public static function nameIsValid(string $actionName): bool
    {
        return ExtGAction::nameIsValid($actionName);
    }

    public function getEnabled(): bool
    {
        return ExtGAction::getEnabled($this->handle);
    }

    public function getName(): ?string
    {
        return ExtGAction::getName($this->handle);
    }
}
