<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GApplication\GApplication as ExtGApplication;
use Jovian\Bindings\Gtk\Enums\GOptionArg;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GApplication extends GObject implements \Jovian\Bindings\Gtk\Contracts\GActionMap
{
    use \Jovian\Bindings\Gtk\Contracts\GActionMapMethods;

    public static function new(mixed $applicationId, int $flags): self
    {
        return new self(ExtGApplication::new_($applicationId, $flags));
    }

    public static function getDefault(): ?GObject
    {
        return Registry::box(ExtGApplication::getDefault());
    }

    public static function idIsValid(string $applicationId): bool
    {
        return ExtGApplication::idIsValid($applicationId);
    }

    public function activate(): static
    {
        ExtGApplication::activate($this->handle);

        return $this;
    }

    public function addMainOption(string $longName, int $shortName, int $flags, GOptionArg|int $arg, string $description, mixed $argDescription): static
    {
        ExtGApplication::addMainOption($this->handle, $longName, $shortName, $flags, ($arg instanceof GOptionArg ? $arg->value : $arg), $description, $argDescription);

        return $this;
    }

    public function getApplicationId(): ?string
    {
        return ExtGApplication::getApplicationId($this->handle);
    }

    public function getDbusConnection(): ?GObject
    {
        return Registry::box(ExtGApplication::getDbusConnection($this->handle));
    }

    public function getDbusObjectPath(): ?string
    {
        return ExtGApplication::getDbusObjectPath($this->handle);
    }

    public function getFlags(): int
    {
        return ExtGApplication::getFlags($this->handle);
    }

    public function getInactivityTimeout(): int
    {
        return ExtGApplication::getInactivityTimeout($this->handle);
    }

    public function getIsBusy(): bool
    {
        return ExtGApplication::getIsBusy($this->handle);
    }

    public function getIsRegistered(): bool
    {
        return ExtGApplication::getIsRegistered($this->handle);
    }

    public function getIsRemote(): bool
    {
        return ExtGApplication::getIsRemote($this->handle);
    }

    public function getResourceBasePath(): ?string
    {
        return ExtGApplication::getResourceBasePath($this->handle);
    }

    public function getVersion(): ?string
    {
        return ExtGApplication::getVersion($this->handle);
    }

    public function hold(): static
    {
        ExtGApplication::hold($this->handle);

        return $this;
    }

    public function markBusy(): static
    {
        ExtGApplication::markBusy($this->handle);

        return $this;
    }

    public function open(array $files, int $nFiles, string $hint): static
    {
        ExtGApplication::open($this->handle, $files, $nFiles, $hint);

        return $this;
    }

    public function quit(): static
    {
        ExtGApplication::quit($this->handle);

        return $this;
    }

    public function release(): static
    {
        ExtGApplication::release($this->handle);

        return $this;
    }

    public function run(int $argc, array $argv): int
    {
        return ExtGApplication::run($this->handle, $argc, $argv);
    }

    public function sendNotification(mixed $id, int $notification): static
    {
        ExtGApplication::sendNotification($this->handle, $id, $notification);

        return $this;
    }

    public function setApplicationId(mixed $applicationId): static
    {
        ExtGApplication::setApplicationId($this->handle, $applicationId);

        return $this;
    }

    public function setDefault(): static
    {
        ExtGApplication::setDefault($this->handle);

        return $this;
    }

    public function setFlags(int $flags): static
    {
        ExtGApplication::setFlags($this->handle, $flags);

        return $this;
    }

    public function setInactivityTimeout(int $inactivityTimeout): static
    {
        ExtGApplication::setInactivityTimeout($this->handle, $inactivityTimeout);

        return $this;
    }

    public function setOptionContextDescription(mixed $description): static
    {
        ExtGApplication::setOptionContextDescription($this->handle, $description);

        return $this;
    }

    public function setOptionContextParameterString(mixed $parameterString): static
    {
        ExtGApplication::setOptionContextParameterString($this->handle, $parameterString);

        return $this;
    }

    public function setOptionContextSummary(mixed $summary): static
    {
        ExtGApplication::setOptionContextSummary($this->handle, $summary);

        return $this;
    }

    public function setResourceBasePath(mixed $resourcePath): static
    {
        ExtGApplication::setResourceBasePath($this->handle, $resourcePath);

        return $this;
    }

    public function setVersion(string $version): static
    {
        ExtGApplication::setVersion($this->handle, $version);

        return $this;
    }

    public function unmarkBusy(): static
    {
        ExtGApplication::unmarkBusy($this->handle);

        return $this;
    }

    public function withdrawNotification(string $id): static
    {
        ExtGApplication::withdrawNotification($this->handle, $id);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onCommandLine(callable $callback): int
    {
        return Bridge::connect($this->handle, 'command-line', $callback);
    }

    public function onHandleLocalOptions(callable $callback): int
    {
        return Bridge::connect($this->handle, 'handle-local-options', $callback);
    }

    public function onNameLost(callable $callback): int
    {
        return Bridge::connect($this->handle, 'name-lost', $callback);
    }

    public function onOpen(callable $callback): int
    {
        return Bridge::connect($this->handle, 'open', $callback);
    }

    public function onShutdown(callable $callback): int
    {
        return Bridge::connect($this->handle, 'shutdown', $callback);
    }

    public function onStartup(callable $callback): int
    {
        return Bridge::connect($this->handle, 'startup', $callback);
    }
}
