<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GListStore\GListStore as ExtGListStore;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GListStore extends GObject implements \Jovian\Bindings\Gtk\Contracts\GListModel
{
    use \Jovian\Bindings\Gtk\Contracts\GListModelMethods;

    public static function new(int $itemType): self
    {
        return new self(ExtGListStore::new_($itemType));
    }

    public function append(int $item): static
    {
        ExtGListStore::append($this->handle, $item);

        return $this;
    }

    /**
     * @return array{position: mixed}
     */
    public function find(int $item): array
    {
        return ExtGListStore::find($this->handle, $item);
    }

    public function insert(int $position, int $item): static
    {
        ExtGListStore::insert($this->handle, $position, $item);

        return $this;
    }

    public function remove(int $position): static
    {
        ExtGListStore::remove($this->handle, $position);

        return $this;
    }

    public function removeAll(): static
    {
        ExtGListStore::removeAll($this->handle);

        return $this;
    }

    public function splice(int $position, int $nRemovals, array $additions, int $nAdditions): static
    {
        ExtGListStore::splice($this->handle, $position, $nRemovals, $additions, $nAdditions);

        return $this;
    }
}
