<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GMenu\GMenu as ExtGMenu;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GMenu extends GMenuModel
{
    public static function new(): self
    {
        return new self(ExtGMenu::new_());
    }

    public function append(mixed $label, mixed $detailedAction): static
    {
        ExtGMenu::append($this->handle, $label, $detailedAction);

        return $this;
    }

    public function appendItem(GMenuItem $item): static
    {
        ExtGMenu::appendItem($this->handle, $item->handle);

        return $this;
    }

    public function appendSection(mixed $label, GMenuModel $section): static
    {
        ExtGMenu::appendSection($this->handle, $label, $section->handle);

        return $this;
    }

    public function appendSubmenu(mixed $label, GMenuModel $submenu): static
    {
        ExtGMenu::appendSubmenu($this->handle, $label, $submenu->handle);

        return $this;
    }

    public function freeze(): static
    {
        ExtGMenu::freeze($this->handle);

        return $this;
    }

    public function insert(int $position, mixed $label, mixed $detailedAction): static
    {
        ExtGMenu::insert($this->handle, $position, $label, $detailedAction);

        return $this;
    }

    public function insertItem(int $position, GMenuItem $item): static
    {
        ExtGMenu::insertItem($this->handle, $position, $item->handle);

        return $this;
    }

    public function insertSection(int $position, mixed $label, GMenuModel $section): static
    {
        ExtGMenu::insertSection($this->handle, $position, $label, $section->handle);

        return $this;
    }

    public function insertSubmenu(int $position, mixed $label, GMenuModel $submenu): static
    {
        ExtGMenu::insertSubmenu($this->handle, $position, $label, $submenu->handle);

        return $this;
    }

    public function prepend(mixed $label, mixed $detailedAction): static
    {
        ExtGMenu::prepend($this->handle, $label, $detailedAction);

        return $this;
    }

    public function prependItem(GMenuItem $item): static
    {
        ExtGMenu::prependItem($this->handle, $item->handle);

        return $this;
    }

    public function prependSection(mixed $label, GMenuModel $section): static
    {
        ExtGMenu::prependSection($this->handle, $label, $section->handle);

        return $this;
    }

    public function prependSubmenu(mixed $label, GMenuModel $submenu): static
    {
        ExtGMenu::prependSubmenu($this->handle, $label, $submenu->handle);

        return $this;
    }

    public function remove(int $position): static
    {
        ExtGMenu::remove($this->handle, $position);

        return $this;
    }

    public function removeAll(): static
    {
        ExtGMenu::removeAll($this->handle);

        return $this;
    }
}
