<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GMenuModel\GMenuModel as ExtGMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GMenuModel extends GObject
{
    public function getItemLink(int $itemIndex, string $link): ?GObject
    {
        return Registry::box(ExtGMenuModel::getItemLink($this->handle, $itemIndex, $link));
    }

    public function getNItems(): int
    {
        return ExtGMenuModel::getNItems($this->handle);
    }

    public function isMutable(): bool
    {
        return ExtGMenuModel::isMutable($this->handle);
    }

    public function itemsChanged(int $position, int $removed, int $added): static
    {
        ExtGMenuModel::itemsChanged($this->handle, $position, $removed, $added);

        return $this;
    }

    public function onItemsChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'items-changed', $callback);
    }
}
