<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gio;

use Gtk\Gio\GSimpleActionGroup\GSimpleActionGroup as ExtGSimpleActionGroup;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GSimpleActionGroup extends GObject implements \Jovian\Bindings\Gtk\Contracts\GActionMap
{
    use \Jovian\Bindings\Gtk\Contracts\GActionMapMethods;

    public static function new(): self
    {
        return new self(ExtGSimpleActionGroup::new_());
    }
}
