<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GApplicationFlags: int
{
    case FLAGS_NONE = 0;
    case IS_SERVICE = 1;
    case IS_LAUNCHER = 2;
    case HANDLES_OPEN = 4;
    case HANDLES_COMMAND_LINE = 8;
    case SEND_ENVIRONMENT = 16;
    case NON_UNIQUE = 32;
    case CAN_OVERRIDE_APP_ID = 64;
    case ALLOW_REPLACEMENT = 128;
    case REPLACE = 256;
}
