<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GOptionArg|int.
 */
enum GOptionArg: int
{
    case NONE = 0;
    case STRING = 1;
    case INT = 2;
    case CALLBACK = 3;
    case FILENAME = 4;
    case STRING_ARRAY = 5;
    case FILENAME_ARRAY = 6;
    case DOUBLE = 7;
    case INT64 = 8;
}
