<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkAccessiblePlatformState|int.
 */
enum GtkAccessiblePlatformState: int
{
    case FOCUSABLE = 0;
    case FOCUSED = 1;
    case ACTIVE = 2;
}
