<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GtkApplicationInhibitFlags: int
{
    case LOGOUT = 1;
    case SWITCH = 2;
    case SUSPEND = 4;
    case IDLE = 8;
}
