<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkBaselinePosition|int.
 */
enum GtkBaselinePosition: int
{
    case TOP = 0;
    case CENTER = 1;
    case BOTTOM = 2;
}
