<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkContentFit|int.
 */
enum GtkContentFit: int
{
    case FILL = 0;
    case CONTAIN = 1;
    case COVER = 2;
    case SCALE_DOWN = 3;
}
