<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkCornerType|int.
 */
enum GtkCornerType: int
{
    case TOP_LEFT = 0;
    case BOTTOM_LEFT = 1;
    case TOP_RIGHT = 2;
    case BOTTOM_RIGHT = 3;
}
