<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkDirectionType|int.
 */
enum GtkDirectionType: int
{
    case TAB_FORWARD = 0;
    case TAB_BACKWARD = 1;
    case UP = 2;
    case DOWN = 3;
    case LEFT = 4;
    case RIGHT = 5;
}
