<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkEntryIconPosition|int.
 */
enum GtkEntryIconPosition: int
{
    case PRIMARY = 0;
    case SECONDARY = 1;
}
