<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkInputPurpose|int.
 */
enum GtkInputPurpose: int
{
    case FREE_FORM = 0;
    case ALPHA = 1;
    case DIGITS = 2;
    case NUMBER = 3;
    case PHONE = 4;
    case URL = 5;
    case EMAIL = 6;
    case NAME = 7;
    case PASSWORD = 8;
    case PIN = 9;
    case TERMINAL = 10;
}
