<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkImageType|int.
 */
enum GtkImageType: int
{
    case EMPTY = 0;
    case ICON_NAME = 1;
    case GICON = 2;
    case PAINTABLE = 3;
}
