<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GtkInputHints: int
{
    case NONE = 0;
    case SPELLCHECK = 1;
    case NO_SPELLCHECK = 2;
    case WORD_COMPLETION = 4;
    case LOWERCASE = 8;
    case UPPERCASE_CHARS = 16;
    case UPPERCASE_WORDS = 32;
    case UPPERCASE_SENTENCES = 64;
    case INHIBIT_OSK = 128;
    case VERTICAL_WRITING = 256;
    case EMOJI = 512;
    case NO_EMOJI = 1024;
    case PRIVATE = 2048;
}
