<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkIconSize|int.
 */
enum GtkIconSize: int
{
    case INHERIT = 0;
    case NORMAL = 1;
    case LARGE = 2;
}
