<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkJustification|int.
 */
enum GtkJustification: int
{
    case LEFT = 0;
    case RIGHT = 1;
    case CENTER = 2;
    case FILL = 3;
}
