<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkListTabBehavior|int.
 */
enum GtkListTabBehavior: int
{
    case ALL = 0;
    case ITEM = 1;
    case CELL = 2;
}
