<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkLevelBarMode|int.
 */
enum GtkLevelBarMode: int
{
    case CONTINUOUS = 0;
    case DISCRETE = 1;
}
