<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkNaturalWrapMode|int.
 */
enum GtkNaturalWrapMode: int
{
    case INHERIT = 0;
    case NONE = 1;
    case WORD = 2;
}
