<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkOverflow|int.
 */
enum GtkOverflow: int
{
    case VISIBLE = 0;
    case HIDDEN = 1;
}
