<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkOrientation|int.
 */
enum GtkOrientation: int
{
    case HORIZONTAL = 0;
    case VERTICAL = 1;
}
