<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GtkPickFlags: int
{
    case DEFAULT = 0;
    case INSENSITIVE = 1;
    case NON_TARGETABLE = 2;
}
