<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GtkPopoverMenuFlags: int
{
    case SLIDING = 0;
    case NESTED = 1;
}
