<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkPackType|int.
 */
enum GtkPackType: int
{
    case START = 0;
    case END = 1;
}
