<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkRevealerTransitionType|int.
 */
enum GtkRevealerTransitionType: int
{
    case NONE = 0;
    case CROSSFADE = 1;
    case SLIDE_RIGHT = 2;
    case SLIDE_LEFT = 3;
    case SLIDE_UP = 4;
    case SLIDE_DOWN = 5;
    case SWING_RIGHT = 6;
    case SWING_LEFT = 7;
    case SWING_UP = 8;
    case SWING_DOWN = 9;
}
