<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkScrollablePolicy|int.
 */
enum GtkScrollablePolicy: int
{
    case MINIMUM = 0;
    case NATURAL = 1;
}
