<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkSizeRequestMode|int.
 */
enum GtkSizeRequestMode: int
{
    case HEIGHT_FOR_WIDTH = 0;
    case WIDTH_FOR_HEIGHT = 1;
    case CONSTANT_SIZE = 2;
}
