<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkSelectionMode|int.
 */
enum GtkSelectionMode: int
{
    case NONE = 0;
    case SINGLE = 1;
    case BROWSE = 2;
    case MULTIPLE = 3;
}
