<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkSpinButtonUpdatePolicy|int.
 */
enum GtkSpinButtonUpdatePolicy: int
{
    case ALWAYS = 0;
    case IF_VALID = 1;
}
