<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkStackTransitionType|int.
 */
enum GtkStackTransitionType: int
{
    case NONE = 0;
    case CROSSFADE = 1;
    case SLIDE_RIGHT = 2;
    case SLIDE_LEFT = 3;
    case SLIDE_UP = 4;
    case SLIDE_DOWN = 5;
    case SLIDE_LEFT_RIGHT = 6;
    case SLIDE_UP_DOWN = 7;
    case OVER_UP = 8;
    case OVER_DOWN = 9;
    case OVER_LEFT = 10;
    case OVER_RIGHT = 11;
    case UNDER_UP = 12;
    case UNDER_DOWN = 13;
    case UNDER_LEFT = 14;
    case UNDER_RIGHT = 15;
    case OVER_UP_DOWN = 16;
    case OVER_DOWN_UP = 17;
    case OVER_LEFT_RIGHT = 18;
    case OVER_RIGHT_LEFT = 19;
    case ROTATE_LEFT = 20;
    case ROTATE_RIGHT = 21;
    case ROTATE_LEFT_RIGHT = 22;
}
