<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkStringFilterMatchMode|int.
 */
enum GtkStringFilterMatchMode: int
{
    case EXACT = 0;
    case SUBSTRING = 1;
    case PREFIX = 2;
}
