<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR bitfield. Parameters stay int; PHP enums cannot be OR'd.
 */
enum GtkStateFlags: int
{
    case NORMAL = 0;
    case ACTIVE = 1;
    case PRELIGHT = 2;
    case SELECTED = 4;
    case INSENSITIVE = 8;
    case INCONSISTENT = 16;
    case FOCUSED = 32;
    case BACKDROP = 64;
    case DIR_LTR = 128;
    case DIR_RTL = 256;
    case LINK = 512;
    case VISITED = 1024;
    case CHECKED = 2048;
    case DROP_ACTIVE = 4096;
    case FOCUS_VISIBLE = 8192;
    case FOCUS_WITHIN = 16384;
}
