<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed GtkSortType|int.
 */
enum GtkSortType: int
{
    case ASCENDING = 0;
    case DESCENDING = 1;
}
