<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed PangoEllipsizeMode|int.
 */
enum PangoEllipsizeMode: int
{
    case NONE = 0;
    case START = 1;
    case MIDDLE = 2;
    case END = 3;
}
