<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Enums;

/**
 * GIR enumeration. Parameters are typed PangoWrapMode|int.
 */
enum PangoWrapMode: int
{
    case WORD = 0;
    case CHAR = 1;
    case WORD_CHAR = 2;
    case NONE = 3;
}
