<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkAspectFrame\GtkAspectFrame as ExtGtkAspectFrame;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkAspectFrame extends GtkWidget
{
    public static function new(float $xalign, float $yalign, float $ratio, bool $obeyChild): self
    {
        return new self(ExtGtkAspectFrame::new_($xalign, $yalign, $ratio, $obeyChild));
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkAspectFrame::getChild($this->handle));
    }

    public function getObeyChild(): bool
    {
        return ExtGtkAspectFrame::getObeyChild($this->handle);
    }

    public function getRatio(): float
    {
        return ExtGtkAspectFrame::getRatio($this->handle);
    }

    public function getXalign(): float
    {
        return ExtGtkAspectFrame::getXalign($this->handle);
    }

    public function getYalign(): float
    {
        return ExtGtkAspectFrame::getYalign($this->handle);
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkAspectFrame::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setObeyChild(bool $obeyChild): static
    {
        ExtGtkAspectFrame::setObeyChild($this->handle, $obeyChild);

        return $this;
    }

    public function setRatio(float $ratio): static
    {
        ExtGtkAspectFrame::setRatio($this->handle, $ratio);

        return $this;
    }

    public function setXalign(float $xalign): static
    {
        ExtGtkAspectFrame::setXalign($this->handle, $xalign);

        return $this;
    }

    public function setYalign(float $yalign): static
    {
        ExtGtkAspectFrame::setYalign($this->handle, $yalign);

        return $this;
    }
}
