<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkActionable\GtkActionable as ExtGtkActionable;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkActionable extends GObject implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public function getActionName(): ?string
    {
        return ExtGtkActionable::getActionName($this->handle);
    }

    public function setActionName(mixed $actionName): static
    {
        ExtGtkActionable::setActionName($this->handle, $actionName);

        return $this;
    }

    public function setDetailedActionName(string $detailedActionName): static
    {
        ExtGtkActionable::setDetailedActionName($this->handle, $detailedActionName);

        return $this;
    }
}
