<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkAboutDialog\GtkAboutDialog as ExtGtkAboutDialog;
use Jovian\Bindings\Gtk\Enums\GtkLicense;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkAboutDialog extends GtkWindow
{
    public static function new(): self
    {
        return new self(ExtGtkAboutDialog::new_());
    }

    public function addCreditSection(string $sectionName, array $people): static
    {
        ExtGtkAboutDialog::addCreditSection($this->handle, $sectionName, $people);

        return $this;
    }

    public function getArtists(): array
    {
        return ExtGtkAboutDialog::getArtists($this->handle);
    }

    public function getAuthors(): array
    {
        return ExtGtkAboutDialog::getAuthors($this->handle);
    }

    public function getComments(): ?string
    {
        return ExtGtkAboutDialog::getComments($this->handle);
    }

    public function getCopyright(): ?string
    {
        return ExtGtkAboutDialog::getCopyright($this->handle);
    }

    public function getDocumenters(): array
    {
        return ExtGtkAboutDialog::getDocumenters($this->handle);
    }

    public function getLicense(): ?string
    {
        return ExtGtkAboutDialog::getLicense($this->handle);
    }

    public function getLicenseType(): int
    {
        return ExtGtkAboutDialog::getLicenseType($this->handle);
    }

    public function getLogo(): ?GObject
    {
        return Registry::box(ExtGtkAboutDialog::getLogo($this->handle));
    }

    public function getLogoIconName(): ?string
    {
        return ExtGtkAboutDialog::getLogoIconName($this->handle);
    }

    public function getProgramName(): ?string
    {
        return ExtGtkAboutDialog::getProgramName($this->handle);
    }

    public function getSystemInformation(): ?string
    {
        return ExtGtkAboutDialog::getSystemInformation($this->handle);
    }

    public function getTranslatorCredits(): ?string
    {
        return ExtGtkAboutDialog::getTranslatorCredits($this->handle);
    }

    public function getVersion(): ?string
    {
        return ExtGtkAboutDialog::getVersion($this->handle);
    }

    public function getWebsite(): ?string
    {
        return ExtGtkAboutDialog::getWebsite($this->handle);
    }

    public function getWebsiteLabel(): ?string
    {
        return ExtGtkAboutDialog::getWebsiteLabel($this->handle);
    }

    public function getWrapLicense(): bool
    {
        return ExtGtkAboutDialog::getWrapLicense($this->handle);
    }

    public function setArtists(array $artists): static
    {
        ExtGtkAboutDialog::setArtists($this->handle, $artists);

        return $this;
    }

    public function setAuthors(array $authors): static
    {
        ExtGtkAboutDialog::setAuthors($this->handle, $authors);

        return $this;
    }

    public function setComments(mixed $comments): static
    {
        ExtGtkAboutDialog::setComments($this->handle, $comments);

        return $this;
    }

    public function setCopyright(mixed $copyright): static
    {
        ExtGtkAboutDialog::setCopyright($this->handle, $copyright);

        return $this;
    }

    public function setDocumenters(array $documenters): static
    {
        ExtGtkAboutDialog::setDocumenters($this->handle, $documenters);

        return $this;
    }

    public function setLicense(mixed $license): static
    {
        ExtGtkAboutDialog::setLicense($this->handle, $license);

        return $this;
    }

    public function setLicenseType(GtkLicense|int $licenseType): static
    {
        ExtGtkAboutDialog::setLicenseType($this->handle, ($licenseType instanceof GtkLicense ? $licenseType->value : $licenseType));

        return $this;
    }

    public function setLogo(int $logo): static
    {
        ExtGtkAboutDialog::setLogo($this->handle, $logo);

        return $this;
    }

    public function setLogoIconName(mixed $iconName): static
    {
        ExtGtkAboutDialog::setLogoIconName($this->handle, $iconName);

        return $this;
    }

    public function setProgramName(mixed $name): static
    {
        ExtGtkAboutDialog::setProgramName($this->handle, $name);

        return $this;
    }

    public function setSystemInformation(mixed $systemInformation): static
    {
        ExtGtkAboutDialog::setSystemInformation($this->handle, $systemInformation);

        return $this;
    }

    public function setTranslatorCredits(mixed $translatorCredits): static
    {
        ExtGtkAboutDialog::setTranslatorCredits($this->handle, $translatorCredits);

        return $this;
    }

    public function setVersion(mixed $version): static
    {
        ExtGtkAboutDialog::setVersion($this->handle, $version);

        return $this;
    }

    public function setWebsite(mixed $website): static
    {
        ExtGtkAboutDialog::setWebsite($this->handle, $website);

        return $this;
    }

    public function setWebsiteLabel(string $websiteLabel): static
    {
        ExtGtkAboutDialog::setWebsiteLabel($this->handle, $websiteLabel);

        return $this;
    }

    public function setWrapLicense(bool $wrapLicense): static
    {
        ExtGtkAboutDialog::setWrapLicense($this->handle, $wrapLicense);

        return $this;
    }

    public function onActivateLink(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-link', $callback);
    }
}
