<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkApplicationWindow\GtkApplicationWindow as ExtGtkApplicationWindow;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkApplicationWindow extends GtkWindow implements \Jovian\Bindings\Gtk\Contracts\GActionMap
{
    use \Jovian\Bindings\Gtk\Contracts\GActionMapMethods;

    public static function new(?GtkApplication $application = null): self
    {
        if (is_null($application)) {
            throw new \InvalidArgumentException('GtkApplicationWindow::new() requires a non-null GtkApplication');
        }

        return new self(ExtGtkApplicationWindow::new_($application->handle));
    }

    public function getId(): int
    {
        return ExtGtkApplicationWindow::getId($this->handle);
    }

    public function getShowMenubar(): bool
    {
        return ExtGtkApplicationWindow::getShowMenubar($this->handle);
    }

    public function setShowMenubar(bool $showMenubar): static
    {
        ExtGtkApplicationWindow::setShowMenubar($this->handle, $showMenubar);

        return $this;
    }
}
