<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkAdjustment\GtkAdjustment as ExtGtkAdjustment;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkAdjustment extends GObject
{
    public static function new(float $value, float $lower, float $upper, float $stepIncrement, float $pageIncrement, float $pageSize): self
    {
        return new self(ExtGtkAdjustment::new_($value, $lower, $upper, $stepIncrement, $pageIncrement, $pageSize));
    }

    public function clampPage(float $lower, float $upper): static
    {
        ExtGtkAdjustment::clampPage($this->handle, $lower, $upper);

        return $this;
    }

    public function configure(float $value, float $lower, float $upper, float $stepIncrement, float $pageIncrement, float $pageSize): static
    {
        ExtGtkAdjustment::configure($this->handle, $value, $lower, $upper, $stepIncrement, $pageIncrement, $pageSize);

        return $this;
    }

    public function getLower(): float
    {
        return ExtGtkAdjustment::getLower($this->handle);
    }

    public function getMinimumIncrement(): float
    {
        return ExtGtkAdjustment::getMinimumIncrement($this->handle);
    }

    public function getPageIncrement(): float
    {
        return ExtGtkAdjustment::getPageIncrement($this->handle);
    }

    public function getPageSize(): float
    {
        return ExtGtkAdjustment::getPageSize($this->handle);
    }

    public function getStepIncrement(): float
    {
        return ExtGtkAdjustment::getStepIncrement($this->handle);
    }

    public function getUpper(): float
    {
        return ExtGtkAdjustment::getUpper($this->handle);
    }

    public function getValue(): float
    {
        return ExtGtkAdjustment::getValue($this->handle);
    }

    public function setLower(float $lower): static
    {
        ExtGtkAdjustment::setLower($this->handle, $lower);

        return $this;
    }

    public function setPageIncrement(float $pageIncrement): static
    {
        ExtGtkAdjustment::setPageIncrement($this->handle, $pageIncrement);

        return $this;
    }

    public function setPageSize(float $pageSize): static
    {
        ExtGtkAdjustment::setPageSize($this->handle, $pageSize);

        return $this;
    }

    public function setStepIncrement(float $stepIncrement): static
    {
        ExtGtkAdjustment::setStepIncrement($this->handle, $stepIncrement);

        return $this;
    }

    public function setUpper(float $upper): static
    {
        ExtGtkAdjustment::setUpper($this->handle, $upper);

        return $this;
    }

    public function setValue(float $value): static
    {
        ExtGtkAdjustment::setValue($this->handle, $value);

        return $this;
    }

    public function onChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'changed', $callback);
    }

    public function onValueChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'value-changed', $callback);
    }
}
