<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkButton\GtkButton as ExtGtkButton;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkButton extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public static function new(): self
    {
        return new self(ExtGtkButton::new_());
    }

    public static function newFromIconName(string $iconName): self
    {
        return new self(ExtGtkButton::newFromIconName($iconName));
    }

    public static function newWithLabel(string $label): self
    {
        return new self(ExtGtkButton::newWithLabel($label));
    }

    public static function newWithMnemonic(string $label): self
    {
        return new self(ExtGtkButton::newWithMnemonic($label));
    }

    public function getCanShrink(): bool
    {
        return ExtGtkButton::getCanShrink($this->handle);
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkButton::getChild($this->handle));
    }

    public function getHasFrame(): bool
    {
        return ExtGtkButton::getHasFrame($this->handle);
    }

    public function getIconName(): ?string
    {
        return ExtGtkButton::getIconName($this->handle);
    }

    public function getLabel(): ?string
    {
        return ExtGtkButton::getLabel($this->handle);
    }

    public function getUseUnderline(): bool
    {
        return ExtGtkButton::getUseUnderline($this->handle);
    }

    public function setCanShrink(bool $canShrink): static
    {
        ExtGtkButton::setCanShrink($this->handle, $canShrink);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkButton::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setHasFrame(bool $hasFrame): static
    {
        ExtGtkButton::setHasFrame($this->handle, $hasFrame);

        return $this;
    }

    public function setIconName(string $iconName): static
    {
        ExtGtkButton::setIconName($this->handle, $iconName);

        return $this;
    }

    public function setLabel(string $label): static
    {
        ExtGtkButton::setLabel($this->handle, $label);

        return $this;
    }

    public function setUseUnderline(bool $useUnderline): static
    {
        ExtGtkButton::setUseUnderline($this->handle, $useUnderline);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onClicked(callable $callback): int
    {
        return Bridge::connect($this->handle, 'clicked', $callback);
    }
}
