<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkBox\GtkBox as ExtGtkBox;
use Jovian\Bindings\Gtk\Enums\GtkBaselinePosition;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkBox extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(GtkOrientation|int $orientation, int $spacing): self
    {
        return new self(ExtGtkBox::new_(($orientation instanceof GtkOrientation ? $orientation->value : $orientation), $spacing));
    }

    public function append(GtkWidget $child): static
    {
        ExtGtkBox::append($this->handle, $child->handle);

        return $this;
    }

    public function getBaselineChild(): int
    {
        return ExtGtkBox::getBaselineChild($this->handle);
    }

    public function getBaselinePosition(): int
    {
        return ExtGtkBox::getBaselinePosition($this->handle);
    }

    public function getHomogeneous(): bool
    {
        return ExtGtkBox::getHomogeneous($this->handle);
    }

    public function getSpacing(): int
    {
        return ExtGtkBox::getSpacing($this->handle);
    }

    public function insertChildAfter(GtkWidget $child, ?GtkWidget $sibling): static
    {
        ExtGtkBox::insertChildAfter($this->handle, $child->handle, (is_null($sibling) ? 0 : $sibling->handle));

        return $this;
    }

    public function prepend(GtkWidget $child): static
    {
        ExtGtkBox::prepend($this->handle, $child->handle);

        return $this;
    }

    public function remove(GtkWidget $child): static
    {
        ExtGtkBox::remove($this->handle, $child->handle);

        return $this;
    }

    public function reorderChildAfter(GtkWidget $child, ?GtkWidget $sibling): static
    {
        ExtGtkBox::reorderChildAfter($this->handle, $child->handle, (is_null($sibling) ? 0 : $sibling->handle));

        return $this;
    }

    public function setBaselineChild(int $child): static
    {
        ExtGtkBox::setBaselineChild($this->handle, $child);

        return $this;
    }

    public function setBaselinePosition(GtkBaselinePosition|int $position): static
    {
        ExtGtkBox::setBaselinePosition($this->handle, ($position instanceof GtkBaselinePosition ? $position->value : $position));

        return $this;
    }

    public function setHomogeneous(bool $homogeneous): static
    {
        ExtGtkBox::setHomogeneous($this->handle, $homogeneous);

        return $this;
    }

    public function setSpacing(int $spacing): static
    {
        ExtGtkBox::setSpacing($this->handle, $spacing);

        return $this;
    }
}
