<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkCssProvider\GtkCssProvider as ExtGtkCssProvider;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkCssProvider extends GObject
{
    public static function new(): self
    {
        return new self(ExtGtkCssProvider::new_());
    }

    public function loadFromString(string $css): static
    {
        ExtGtkCssProvider::loadFromString($this->handle, $css);

        return $this;
    }

    public function loadFromPath(string $path): static
    {
        ExtGtkCssProvider::loadFromPath($this->handle, $path);

        return $this;
    }

    public function toString(): string
    {
        return ExtGtkCssProvider::toString($this->handle);
    }

    public function onParsingError(callable $callback): int
    {
        return Bridge::connect($this->handle, 'parsing-error', $callback);
    }
}
