<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkCheckButton\GtkCheckButton as ExtGtkCheckButton;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkCheckButton extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public static function new(): self
    {
        return new self(ExtGtkCheckButton::new_());
    }

    public static function newWithLabel(mixed $label): self
    {
        return new self(ExtGtkCheckButton::newWithLabel($label));
    }

    public static function newWithMnemonic(mixed $label): self
    {
        return new self(ExtGtkCheckButton::newWithMnemonic($label));
    }

    public function getActive(): bool
    {
        return ExtGtkCheckButton::getActive($this->handle);
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkCheckButton::getChild($this->handle));
    }

    public function getInconsistent(): bool
    {
        return ExtGtkCheckButton::getInconsistent($this->handle);
    }

    public function getLabel(): ?string
    {
        return ExtGtkCheckButton::getLabel($this->handle);
    }

    public function getUseUnderline(): bool
    {
        return ExtGtkCheckButton::getUseUnderline($this->handle);
    }

    public function setActive(bool $setting): static
    {
        ExtGtkCheckButton::setActive($this->handle, $setting);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkCheckButton::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setGroup(?GtkCheckButton $group): static
    {
        ExtGtkCheckButton::setGroup($this->handle, (is_null($group) ? 0 : $group->handle));

        return $this;
    }

    public function setInconsistent(bool $inconsistent): static
    {
        ExtGtkCheckButton::setInconsistent($this->handle, $inconsistent);

        return $this;
    }

    public function setLabel(mixed $label): static
    {
        ExtGtkCheckButton::setLabel($this->handle, $label);

        return $this;
    }

    public function setUseUnderline(bool $setting): static
    {
        ExtGtkCheckButton::setUseUnderline($this->handle, $setting);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onToggled(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggled', $callback);
    }
}
