<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkCenterBox\GtkCenterBox as ExtGtkCenterBox;
use Jovian\Bindings\Gtk\Enums\GtkBaselinePosition;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkCenterBox extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkCenterBox::new_());
    }

    public function getBaselinePosition(): int
    {
        return ExtGtkCenterBox::getBaselinePosition($this->handle);
    }

    public function getCenterWidget(): ?GObject
    {
        return Registry::box(ExtGtkCenterBox::getCenterWidget($this->handle));
    }

    public function getEndWidget(): ?GObject
    {
        return Registry::box(ExtGtkCenterBox::getEndWidget($this->handle));
    }

    public function getShrinkCenterLast(): bool
    {
        return ExtGtkCenterBox::getShrinkCenterLast($this->handle);
    }

    public function getStartWidget(): ?GObject
    {
        return Registry::box(ExtGtkCenterBox::getStartWidget($this->handle));
    }

    public function setBaselinePosition(GtkBaselinePosition|int $position): static
    {
        ExtGtkCenterBox::setBaselinePosition($this->handle, ($position instanceof GtkBaselinePosition ? $position->value : $position));

        return $this;
    }

    public function setCenterWidget(?GtkWidget $child): static
    {
        ExtGtkCenterBox::setCenterWidget($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setEndWidget(?GtkWidget $child): static
    {
        ExtGtkCenterBox::setEndWidget($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setShrinkCenterLast(bool $shrinkCenterLast): static
    {
        ExtGtkCenterBox::setShrinkCenterLast($this->handle, $shrinkCenterLast);

        return $this;
    }

    public function setStartWidget(?GtkWidget $child): static
    {
        ExtGtkCenterBox::setStartWidget($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }
}
