<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkCalendar\GtkCalendar as ExtGtkCalendar;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkCalendar extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkCalendar::new_());
    }

    public function clearMarks(): static
    {
        ExtGtkCalendar::clearMarks($this->handle);

        return $this;
    }

    public function getDay(): int
    {
        return ExtGtkCalendar::getDay($this->handle);
    }

    public function getDayIsMarked(int $day): bool
    {
        return ExtGtkCalendar::getDayIsMarked($this->handle, $day);
    }

    public function getMonth(): int
    {
        return ExtGtkCalendar::getMonth($this->handle);
    }

    public function getShowDayNames(): bool
    {
        return ExtGtkCalendar::getShowDayNames($this->handle);
    }

    public function getShowHeading(): bool
    {
        return ExtGtkCalendar::getShowHeading($this->handle);
    }

    public function getShowWeekNumbers(): bool
    {
        return ExtGtkCalendar::getShowWeekNumbers($this->handle);
    }

    public function getYear(): int
    {
        return ExtGtkCalendar::getYear($this->handle);
    }

    public function markDay(int $day): static
    {
        ExtGtkCalendar::markDay($this->handle, $day);

        return $this;
    }

    public function setDay(int $day): static
    {
        ExtGtkCalendar::setDay($this->handle, $day);

        return $this;
    }

    public function setMonth(int $month): static
    {
        ExtGtkCalendar::setMonth($this->handle, $month);

        return $this;
    }

    public function setShowDayNames(bool $value): static
    {
        ExtGtkCalendar::setShowDayNames($this->handle, $value);

        return $this;
    }

    public function setShowHeading(bool $value): static
    {
        ExtGtkCalendar::setShowHeading($this->handle, $value);

        return $this;
    }

    public function setShowWeekNumbers(bool $value): static
    {
        ExtGtkCalendar::setShowWeekNumbers($this->handle, $value);

        return $this;
    }

    public function setYear(int $year): static
    {
        ExtGtkCalendar::setYear($this->handle, $year);

        return $this;
    }

    public function unmarkDay(int $day): static
    {
        ExtGtkCalendar::unmarkDay($this->handle, $day);

        return $this;
    }

    public function onDaySelected(callable $callback): int
    {
        return Bridge::connect($this->handle, 'day-selected', $callback);
    }

    public function onNextMonth(callable $callback): int
    {
        return Bridge::connect($this->handle, 'next-month', $callback);
    }

    public function onNextYear(callable $callback): int
    {
        return Bridge::connect($this->handle, 'next-year', $callback);
    }

    public function onPrevMonth(callable $callback): int
    {
        return Bridge::connect($this->handle, 'prev-month', $callback);
    }

    public function onPrevYear(callable $callback): int
    {
        return Bridge::connect($this->handle, 'prev-year', $callback);
    }
}
