<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkColumnView\GtkColumnView as ExtGtkColumnView;
use Jovian\Bindings\Gtk\Contracts\GtkSelectionModel;
use Jovian\Bindings\Gtk\Enums\GtkListTabBehavior;
use Jovian\Bindings\Gtk\Enums\GtkSortType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkColumnView extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkScrollable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkScrollableMethods;

    public static function new(?GtkSelectionModel $model): self
    {
        return new self(ExtGtkColumnView::new_((is_null($model) ? 0 : $model->handle)));
    }

    public function appendColumn(GtkColumnViewColumn $column): static
    {
        ExtGtkColumnView::appendColumn($this->handle, $column->handle);

        return $this;
    }

    public function getColumns(): ?GObject
    {
        return Registry::box(ExtGtkColumnView::getColumns($this->handle));
    }

    public function getEnableRubberband(): bool
    {
        return ExtGtkColumnView::getEnableRubberband($this->handle);
    }

    public function getHeaderFactory(): ?GObject
    {
        return Registry::box(ExtGtkColumnView::getHeaderFactory($this->handle));
    }

    public function getModel(): ?GObject
    {
        return Registry::box(ExtGtkColumnView::getModel($this->handle));
    }

    public function getReorderable(): bool
    {
        return ExtGtkColumnView::getReorderable($this->handle);
    }

    public function getRowFactory(): ?GObject
    {
        return Registry::box(ExtGtkColumnView::getRowFactory($this->handle));
    }

    public function getShowColumnSeparators(): bool
    {
        return ExtGtkColumnView::getShowColumnSeparators($this->handle);
    }

    public function getShowRowSeparators(): bool
    {
        return ExtGtkColumnView::getShowRowSeparators($this->handle);
    }

    public function getSingleClickActivate(): bool
    {
        return ExtGtkColumnView::getSingleClickActivate($this->handle);
    }

    public function getTabBehavior(): int
    {
        return ExtGtkColumnView::getTabBehavior($this->handle);
    }

    public function insertColumn(int $position, GtkColumnViewColumn $column): static
    {
        ExtGtkColumnView::insertColumn($this->handle, $position, $column->handle);

        return $this;
    }

    public function removeColumn(GtkColumnViewColumn $column): static
    {
        ExtGtkColumnView::removeColumn($this->handle, $column->handle);

        return $this;
    }

    public function setEnableRubberband(bool $enableRubberband): static
    {
        ExtGtkColumnView::setEnableRubberband($this->handle, $enableRubberband);

        return $this;
    }

    public function setHeaderFactory(int $factory): static
    {
        ExtGtkColumnView::setHeaderFactory($this->handle, $factory);

        return $this;
    }

    public function setModel(?GtkSelectionModel $model): static
    {
        ExtGtkColumnView::setModel($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setReorderable(bool $reorderable): static
    {
        ExtGtkColumnView::setReorderable($this->handle, $reorderable);

        return $this;
    }

    public function setRowFactory(int $factory): static
    {
        ExtGtkColumnView::setRowFactory($this->handle, $factory);

        return $this;
    }

    public function setShowColumnSeparators(bool $showColumnSeparators): static
    {
        ExtGtkColumnView::setShowColumnSeparators($this->handle, $showColumnSeparators);

        return $this;
    }

    public function setShowRowSeparators(bool $showRowSeparators): static
    {
        ExtGtkColumnView::setShowRowSeparators($this->handle, $showRowSeparators);

        return $this;
    }

    public function setSingleClickActivate(bool $singleClickActivate): static
    {
        ExtGtkColumnView::setSingleClickActivate($this->handle, $singleClickActivate);

        return $this;
    }

    public function setTabBehavior(GtkListTabBehavior|int $tabBehavior): static
    {
        ExtGtkColumnView::setTabBehavior($this->handle, ($tabBehavior instanceof GtkListTabBehavior ? $tabBehavior->value : $tabBehavior));

        return $this;
    }

    public function sortByColumn(?GtkColumnViewColumn $column, GtkSortType|int $direction): static
    {
        ExtGtkColumnView::sortByColumn($this->handle, (is_null($column) ? 0 : $column->handle), ($direction instanceof GtkSortType ? $direction->value : $direction));

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }
}
