<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkExpander\GtkExpander as ExtGtkExpander;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkExpander extends GtkWidget
{
    public static function new(mixed $label): self
    {
        return new self(ExtGtkExpander::new_($label));
    }

    public static function newWithMnemonic(mixed $label): self
    {
        return new self(ExtGtkExpander::newWithMnemonic($label));
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkExpander::getChild($this->handle));
    }

    public function getExpanded(): bool
    {
        return ExtGtkExpander::getExpanded($this->handle);
    }

    public function getLabel(): ?string
    {
        return ExtGtkExpander::getLabel($this->handle);
    }

    public function getLabelWidget(): ?GObject
    {
        return Registry::box(ExtGtkExpander::getLabelWidget($this->handle));
    }

    public function getResizeToplevel(): bool
    {
        return ExtGtkExpander::getResizeToplevel($this->handle);
    }

    public function getUseMarkup(): bool
    {
        return ExtGtkExpander::getUseMarkup($this->handle);
    }

    public function getUseUnderline(): bool
    {
        return ExtGtkExpander::getUseUnderline($this->handle);
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkExpander::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setExpanded(bool $expanded): static
    {
        ExtGtkExpander::setExpanded($this->handle, $expanded);

        return $this;
    }

    public function setLabel(mixed $label): static
    {
        ExtGtkExpander::setLabel($this->handle, $label);

        return $this;
    }

    public function setLabelWidget(?GtkWidget $labelWidget): static
    {
        ExtGtkExpander::setLabelWidget($this->handle, (is_null($labelWidget) ? 0 : $labelWidget->handle));

        return $this;
    }

    public function setResizeToplevel(bool $resizeToplevel): static
    {
        ExtGtkExpander::setResizeToplevel($this->handle, $resizeToplevel);

        return $this;
    }

    public function setUseMarkup(bool $useMarkup): static
    {
        ExtGtkExpander::setUseMarkup($this->handle, $useMarkup);

        return $this;
    }

    public function setUseUnderline(bool $useUnderline): static
    {
        ExtGtkExpander::setUseUnderline($this->handle, $useUnderline);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }
}
