<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkEditable\GtkEditable as ExtGtkEditable;
use Jovian\Bindings\Gtk\Enums\GtkAccessiblePlatformState;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkEditable extends GObject implements \Jovian\Bindings\Gtk\Contracts\GtkEditable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkEditableMethods;

    public function delegateGetAccessiblePlatformState(GtkAccessiblePlatformState|int $state): bool
    {
        return ExtGtkEditable::delegateGetAccessiblePlatformState($this->handle, ($state instanceof GtkAccessiblePlatformState ? $state->value : $state));
    }

    public function deleteSelection(): static
    {
        ExtGtkEditable::deleteSelection($this->handle);

        return $this;
    }

    public function deleteText(int $startPos, int $endPos): static
    {
        ExtGtkEditable::deleteText($this->handle, $startPos, $endPos);

        return $this;
    }

    public function finishDelegate(): static
    {
        ExtGtkEditable::finishDelegate($this->handle);

        return $this;
    }

    public function getAlignment(): float
    {
        return ExtGtkEditable::getAlignment($this->handle);
    }

    public function getChars(int $startPos, int $endPos): ?string
    {
        return ExtGtkEditable::getChars($this->handle, $startPos, $endPos);
    }

    public function getDelegate(): ?GObject
    {
        return Registry::box(ExtGtkEditable::getDelegate($this->handle));
    }

    public function getEditable(): bool
    {
        return ExtGtkEditable::getEditable($this->handle);
    }

    public function getEnableUndo(): bool
    {
        return ExtGtkEditable::getEnableUndo($this->handle);
    }

    public function getMaxWidthChars(): int
    {
        return ExtGtkEditable::getMaxWidthChars($this->handle);
    }

    public function getPosition(): int
    {
        return ExtGtkEditable::getPosition($this->handle);
    }

    /**
     * @return array{start_pos: mixed, end_pos: mixed}
     */
    public function getSelectionBounds(): array
    {
        return ExtGtkEditable::getSelectionBounds($this->handle);
    }

    public function getText(): ?string
    {
        return ExtGtkEditable::getText($this->handle);
    }

    public function getWidthChars(): int
    {
        return ExtGtkEditable::getWidthChars($this->handle);
    }

    public function initDelegate(): static
    {
        ExtGtkEditable::initDelegate($this->handle);

        return $this;
    }

    public function insertText(string $text, int $length, int $position): array
    {
        return ExtGtkEditable::insertText($this->handle, $text, $length, $position);
    }

    public function selectRegion(int $startPos, int $endPos): static
    {
        ExtGtkEditable::selectRegion($this->handle, $startPos, $endPos);

        return $this;
    }

    public function setAlignment(float $xalign): static
    {
        ExtGtkEditable::setAlignment($this->handle, $xalign);

        return $this;
    }

    public function setEditable(bool $isEditable): static
    {
        ExtGtkEditable::setEditable($this->handle, $isEditable);

        return $this;
    }

    public function setEnableUndo(bool $enableUndo): static
    {
        ExtGtkEditable::setEnableUndo($this->handle, $enableUndo);

        return $this;
    }

    public function setMaxWidthChars(int $nChars): static
    {
        ExtGtkEditable::setMaxWidthChars($this->handle, $nChars);

        return $this;
    }

    public function setPosition(int $position): static
    {
        ExtGtkEditable::setPosition($this->handle, $position);

        return $this;
    }

    public function setText(string $text): static
    {
        ExtGtkEditable::setText($this->handle, $text);

        return $this;
    }

    public function setWidthChars(int $nChars): static
    {
        ExtGtkEditable::setWidthChars($this->handle, $nChars);

        return $this;
    }

    public function onChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'changed', $callback);
    }

    public function onDeleteText(callable $callback): int
    {
        return Bridge::connect($this->handle, 'delete-text', $callback);
    }

    public function onInsertText(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-text', $callback);
    }
}
