<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkEntry\GtkEntry as ExtGtkEntry;
use Jovian\Bindings\Gtk\Enums\GtkEntryIconPosition;
use Jovian\Bindings\Gtk\Enums\GtkInputPurpose;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;
use Jovian\Bindings\Gtk\Values\GdkRectangle;

class GtkEntry extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkEditable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkEditableMethods;

    public static function new(): self
    {
        return new self(ExtGtkEntry::new_());
    }

    public static function newWithBuffer(GtkEntryBuffer $buffer): self
    {
        return new self(ExtGtkEntry::newWithBuffer($buffer->handle));
    }

    public function getActivatesDefault(): bool
    {
        return ExtGtkEntry::getActivatesDefault($this->handle);
    }

    public function getAlignment(): float
    {
        return ExtGtkEntry::getAlignment($this->handle);
    }

    public function getBuffer(): ?GObject
    {
        return Registry::box(ExtGtkEntry::getBuffer($this->handle));
    }

    public function getCurrentIconDragSource(): int
    {
        return ExtGtkEntry::getCurrentIconDragSource($this->handle);
    }

    public function getExtraMenu(): ?GObject
    {
        return Registry::box(ExtGtkEntry::getExtraMenu($this->handle));
    }

    public function getHasFrame(): bool
    {
        return ExtGtkEntry::getHasFrame($this->handle);
    }

    public function getIconActivatable(GtkEntryIconPosition|int $iconPos): bool
    {
        return ExtGtkEntry::getIconActivatable($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getIconArea(GtkEntryIconPosition|int $iconPos): GdkRectangle
    {
        return GdkRectangle::fromArray(ExtGtkEntry::getIconArea($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos)));
    }

    public function getIconAtPos(int $x, int $y): int
    {
        return ExtGtkEntry::getIconAtPos($this->handle, $x, $y);
    }

    public function getIconGicon(GtkEntryIconPosition|int $iconPos): ?GObject
    {
        return Registry::box(ExtGtkEntry::getIconGicon($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos)));
    }

    public function getIconName(GtkEntryIconPosition|int $iconPos): ?string
    {
        return ExtGtkEntry::getIconName($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getIconPaintable(GtkEntryIconPosition|int $iconPos): ?GObject
    {
        return Registry::box(ExtGtkEntry::getIconPaintable($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos)));
    }

    public function getIconSensitive(GtkEntryIconPosition|int $iconPos): bool
    {
        return ExtGtkEntry::getIconSensitive($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getIconStorageType(GtkEntryIconPosition|int $iconPos): int
    {
        return ExtGtkEntry::getIconStorageType($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getIconTooltipMarkup(GtkEntryIconPosition|int $iconPos): ?string
    {
        return ExtGtkEntry::getIconTooltipMarkup($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getIconTooltipText(GtkEntryIconPosition|int $iconPos): ?string
    {
        return ExtGtkEntry::getIconTooltipText($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos));
    }

    public function getInputHints(): int
    {
        return ExtGtkEntry::getInputHints($this->handle);
    }

    public function getInputPurpose(): int
    {
        return ExtGtkEntry::getInputPurpose($this->handle);
    }

    public function getInvisibleChar(): int
    {
        return ExtGtkEntry::getInvisibleChar($this->handle);
    }

    public function getMaxLength(): int
    {
        return ExtGtkEntry::getMaxLength($this->handle);
    }

    public function getOverwriteMode(): bool
    {
        return ExtGtkEntry::getOverwriteMode($this->handle);
    }

    public function getPlaceholderText(): ?string
    {
        return ExtGtkEntry::getPlaceholderText($this->handle);
    }

    public function getProgressFraction(): float
    {
        return ExtGtkEntry::getProgressFraction($this->handle);
    }

    public function getProgressPulseStep(): float
    {
        return ExtGtkEntry::getProgressPulseStep($this->handle);
    }

    public function getTextLength(): int
    {
        return ExtGtkEntry::getTextLength($this->handle);
    }

    public function getVisibility(): bool
    {
        return ExtGtkEntry::getVisibility($this->handle);
    }

    public function grabFocusWithoutSelecting(): bool
    {
        return ExtGtkEntry::grabFocusWithoutSelecting($this->handle);
    }

    public function progressPulse(): static
    {
        ExtGtkEntry::progressPulse($this->handle);

        return $this;
    }

    public function resetImContext(): static
    {
        ExtGtkEntry::resetImContext($this->handle);

        return $this;
    }

    public function setActivatesDefault(bool $setting): static
    {
        ExtGtkEntry::setActivatesDefault($this->handle, $setting);

        return $this;
    }

    public function setAlignment(float $xalign): static
    {
        ExtGtkEntry::setAlignment($this->handle, $xalign);

        return $this;
    }

    public function setBuffer(GtkEntryBuffer $buffer): static
    {
        ExtGtkEntry::setBuffer($this->handle, $buffer->handle);

        return $this;
    }

    public function setExtraMenu(?GMenuModel $model): static
    {
        ExtGtkEntry::setExtraMenu($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setHasFrame(bool $setting): static
    {
        ExtGtkEntry::setHasFrame($this->handle, $setting);

        return $this;
    }

    public function setIconActivatable(GtkEntryIconPosition|int $iconPos, bool $activatable): static
    {
        ExtGtkEntry::setIconActivatable($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $activatable);

        return $this;
    }

    public function setIconFromGicon(GtkEntryIconPosition|int $iconPos, int $icon): static
    {
        ExtGtkEntry::setIconFromGicon($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $icon);

        return $this;
    }

    public function setIconFromIconName(GtkEntryIconPosition|int $iconPos, mixed $iconName): static
    {
        ExtGtkEntry::setIconFromIconName($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $iconName);

        return $this;
    }

    public function setIconFromPaintable(GtkEntryIconPosition|int $iconPos, int $paintable): static
    {
        ExtGtkEntry::setIconFromPaintable($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $paintable);

        return $this;
    }

    public function setIconSensitive(GtkEntryIconPosition|int $iconPos, bool $sensitive): static
    {
        ExtGtkEntry::setIconSensitive($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $sensitive);

        return $this;
    }

    public function setIconTooltipMarkup(GtkEntryIconPosition|int $iconPos, mixed $tooltip): static
    {
        ExtGtkEntry::setIconTooltipMarkup($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $tooltip);

        return $this;
    }

    public function setIconTooltipText(GtkEntryIconPosition|int $iconPos, mixed $tooltip): static
    {
        ExtGtkEntry::setIconTooltipText($this->handle, ($iconPos instanceof GtkEntryIconPosition ? $iconPos->value : $iconPos), $tooltip);

        return $this;
    }

    public function setInputHints(int $hints): static
    {
        ExtGtkEntry::setInputHints($this->handle, $hints);

        return $this;
    }

    public function setInputPurpose(GtkInputPurpose|int $purpose): static
    {
        ExtGtkEntry::setInputPurpose($this->handle, ($purpose instanceof GtkInputPurpose ? $purpose->value : $purpose));

        return $this;
    }

    public function setInvisibleChar(int $ch): static
    {
        ExtGtkEntry::setInvisibleChar($this->handle, $ch);

        return $this;
    }

    public function setMaxLength(int $max): static
    {
        ExtGtkEntry::setMaxLength($this->handle, $max);

        return $this;
    }

    public function setOverwriteMode(bool $overwrite): static
    {
        ExtGtkEntry::setOverwriteMode($this->handle, $overwrite);

        return $this;
    }

    public function setPlaceholderText(mixed $text): static
    {
        ExtGtkEntry::setPlaceholderText($this->handle, $text);

        return $this;
    }

    public function setProgressFraction(float $fraction): static
    {
        ExtGtkEntry::setProgressFraction($this->handle, $fraction);

        return $this;
    }

    public function setProgressPulseStep(float $fraction): static
    {
        ExtGtkEntry::setProgressPulseStep($this->handle, $fraction);

        return $this;
    }

    public function setVisibility(bool $visible): static
    {
        ExtGtkEntry::setVisibility($this->handle, $visible);

        return $this;
    }

    public function unsetInvisibleChar(): static
    {
        ExtGtkEntry::unsetInvisibleChar($this->handle);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onIconPress(callable $callback): int
    {
        return Bridge::connect($this->handle, 'icon-press', $callback);
    }

    public function onIconRelease(callable $callback): int
    {
        return Bridge::connect($this->handle, 'icon-release', $callback);
    }
}
