<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkFlowBoxChild\GtkFlowBoxChild as ExtGtkFlowBoxChild;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkFlowBoxChild extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkFlowBoxChild::new_());
    }

    public function changed(): static
    {
        ExtGtkFlowBoxChild::changed($this->handle);

        return $this;
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkFlowBoxChild::getChild($this->handle));
    }

    public function getIndex(): int
    {
        return ExtGtkFlowBoxChild::getIndex($this->handle);
    }

    public function isSelected(): bool
    {
        return ExtGtkFlowBoxChild::isSelected($this->handle);
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkFlowBoxChild::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }
}
