<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkFrame\GtkFrame as ExtGtkFrame;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkFrame extends GtkWidget
{
    public static function new(mixed $label): self
    {
        return new self(ExtGtkFrame::new_($label));
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkFrame::getChild($this->handle));
    }

    public function getLabel(): ?string
    {
        return ExtGtkFrame::getLabel($this->handle);
    }

    public function getLabelAlign(): float
    {
        return ExtGtkFrame::getLabelAlign($this->handle);
    }

    public function getLabelWidget(): ?GObject
    {
        return Registry::box(ExtGtkFrame::getLabelWidget($this->handle));
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkFrame::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setLabel(mixed $label): static
    {
        ExtGtkFrame::setLabel($this->handle, $label);

        return $this;
    }

    public function setLabelAlign(float $xalign): static
    {
        ExtGtkFrame::setLabelAlign($this->handle, $xalign);

        return $this;
    }

    public function setLabelWidget(?GtkWidget $labelWidget): static
    {
        ExtGtkFrame::setLabelWidget($this->handle, (is_null($labelWidget) ? 0 : $labelWidget->handle));

        return $this;
    }
}
