<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkFlowBox\GtkFlowBox as ExtGtkFlowBox;
use Jovian\Bindings\Gtk\Enums\GtkSelectionMode;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkFlowBox extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkFlowBox::new_());
    }

    public function append(GtkWidget $child): static
    {
        ExtGtkFlowBox::append($this->handle, $child->handle);

        return $this;
    }

    public function getActivateOnSingleClick(): bool
    {
        return ExtGtkFlowBox::getActivateOnSingleClick($this->handle);
    }

    public function getChildAtIndex(int $idx): ?GObject
    {
        return Registry::box(ExtGtkFlowBox::getChildAtIndex($this->handle, $idx));
    }

    public function getChildAtPos(int $x, int $y): ?GObject
    {
        return Registry::box(ExtGtkFlowBox::getChildAtPos($this->handle, $x, $y));
    }

    public function getColumnSpacing(): int
    {
        return ExtGtkFlowBox::getColumnSpacing($this->handle);
    }

    public function getHomogeneous(): bool
    {
        return ExtGtkFlowBox::getHomogeneous($this->handle);
    }

    public function getMaxChildrenPerLine(): int
    {
        return ExtGtkFlowBox::getMaxChildrenPerLine($this->handle);
    }

    public function getMinChildrenPerLine(): int
    {
        return ExtGtkFlowBox::getMinChildrenPerLine($this->handle);
    }

    public function getRowSpacing(): int
    {
        return ExtGtkFlowBox::getRowSpacing($this->handle);
    }

    public function getSelectedChildren(): array
    {
        return ExtGtkFlowBox::getSelectedChildren($this->handle);
    }

    public function getSelectionMode(): int
    {
        return ExtGtkFlowBox::getSelectionMode($this->handle);
    }

    public function insert(GtkWidget $widget, int $position): static
    {
        ExtGtkFlowBox::insert($this->handle, $widget->handle, $position);

        return $this;
    }

    public function invalidateFilter(): static
    {
        ExtGtkFlowBox::invalidateFilter($this->handle);

        return $this;
    }

    public function invalidateSort(): static
    {
        ExtGtkFlowBox::invalidateSort($this->handle);

        return $this;
    }

    public function prepend(GtkWidget $child): static
    {
        ExtGtkFlowBox::prepend($this->handle, $child->handle);

        return $this;
    }

    public function remove(GtkWidget $widget): static
    {
        ExtGtkFlowBox::remove($this->handle, $widget->handle);

        return $this;
    }

    public function removeAll(): static
    {
        ExtGtkFlowBox::removeAll($this->handle);

        return $this;
    }

    public function selectAll(): static
    {
        ExtGtkFlowBox::selectAll($this->handle);

        return $this;
    }

    public function selectChild(GtkFlowBoxChild $child): static
    {
        ExtGtkFlowBox::selectChild($this->handle, $child->handle);

        return $this;
    }

    public function setActivateOnSingleClick(bool $single): static
    {
        ExtGtkFlowBox::setActivateOnSingleClick($this->handle, $single);

        return $this;
    }

    public function setColumnSpacing(int $spacing): static
    {
        ExtGtkFlowBox::setColumnSpacing($this->handle, $spacing);

        return $this;
    }

    public function setHadjustment(GtkAdjustment $adjustment): static
    {
        ExtGtkFlowBox::setHadjustment($this->handle, $adjustment->handle);

        return $this;
    }

    public function setHomogeneous(bool $homogeneous): static
    {
        ExtGtkFlowBox::setHomogeneous($this->handle, $homogeneous);

        return $this;
    }

    public function setMaxChildrenPerLine(int $nChildren): static
    {
        ExtGtkFlowBox::setMaxChildrenPerLine($this->handle, $nChildren);

        return $this;
    }

    public function setMinChildrenPerLine(int $nChildren): static
    {
        ExtGtkFlowBox::setMinChildrenPerLine($this->handle, $nChildren);

        return $this;
    }

    public function setRowSpacing(int $spacing): static
    {
        ExtGtkFlowBox::setRowSpacing($this->handle, $spacing);

        return $this;
    }

    public function setSelectionMode(GtkSelectionMode|int $mode): static
    {
        ExtGtkFlowBox::setSelectionMode($this->handle, ($mode instanceof GtkSelectionMode ? $mode->value : $mode));

        return $this;
    }

    public function setVadjustment(GtkAdjustment $adjustment): static
    {
        ExtGtkFlowBox::setVadjustment($this->handle, $adjustment->handle);

        return $this;
    }

    public function unselectAll(): static
    {
        ExtGtkFlowBox::unselectAll($this->handle);

        return $this;
    }

    public function unselectChild(GtkFlowBoxChild $child): static
    {
        ExtGtkFlowBox::unselectChild($this->handle, $child->handle);

        return $this;
    }

    public function onActivateCursorChild(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-cursor-child', $callback);
    }

    public function onChildActivated(callable $callback): int
    {
        return Bridge::connect($this->handle, 'child-activated', $callback);
    }

    public function onMoveCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-cursor', $callback);
    }

    public function onSelectAll(callable $callback): int
    {
        return Bridge::connect($this->handle, 'select-all', $callback);
    }

    public function onSelectedChildrenChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'selected-children-changed', $callback);
    }

    public function onToggleCursorChild(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-cursor-child', $callback);
    }

    public function onUnselectAll(callable $callback): int
    {
        return Bridge::connect($this->handle, 'unselect-all', $callback);
    }
}
