<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkGrid\GtkGrid as ExtGtkGrid;
use Jovian\Bindings\Gtk\Enums\GtkBaselinePosition;
use Jovian\Bindings\Gtk\Enums\GtkPositionType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkGrid extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkGrid::new_());
    }

    public function attach(GtkWidget $child, int $column, int $row, int $width, int $height): static
    {
        ExtGtkGrid::attach($this->handle, $child->handle, $column, $row, $width, $height);

        return $this;
    }

    public function attachNextTo(GtkWidget $child, ?GtkWidget $sibling, GtkPositionType|int $side, int $width, int $height): static
    {
        ExtGtkGrid::attachNextTo($this->handle, $child->handle, (is_null($sibling) ? 0 : $sibling->handle), ($side instanceof GtkPositionType ? $side->value : $side), $width, $height);

        return $this;
    }

    public function getBaselineRow(): int
    {
        return ExtGtkGrid::getBaselineRow($this->handle);
    }

    public function getChildAt(int $column, int $row): ?GObject
    {
        return Registry::box(ExtGtkGrid::getChildAt($this->handle, $column, $row));
    }

    public function getColumnHomogeneous(): bool
    {
        return ExtGtkGrid::getColumnHomogeneous($this->handle);
    }

    public function getColumnSpacing(): int
    {
        return ExtGtkGrid::getColumnSpacing($this->handle);
    }

    public function getRowBaselinePosition(int $row): int
    {
        return ExtGtkGrid::getRowBaselinePosition($this->handle, $row);
    }

    public function getRowHomogeneous(): bool
    {
        return ExtGtkGrid::getRowHomogeneous($this->handle);
    }

    public function getRowSpacing(): int
    {
        return ExtGtkGrid::getRowSpacing($this->handle);
    }

    public function insertColumn(int $position): static
    {
        ExtGtkGrid::insertColumn($this->handle, $position);

        return $this;
    }

    public function insertNextTo(GtkWidget $sibling, GtkPositionType|int $side): static
    {
        ExtGtkGrid::insertNextTo($this->handle, $sibling->handle, ($side instanceof GtkPositionType ? $side->value : $side));

        return $this;
    }

    public function insertRow(int $position): static
    {
        ExtGtkGrid::insertRow($this->handle, $position);

        return $this;
    }

    /**
     * @return array{column: mixed, row: mixed, width: mixed, height: mixed}
     */
    public function queryChild(GtkWidget $child): array
    {
        return ExtGtkGrid::queryChild($this->handle, $child->handle);
    }

    public function remove(GtkWidget $child): static
    {
        ExtGtkGrid::remove($this->handle, $child->handle);

        return $this;
    }

    public function removeColumn(int $position): static
    {
        ExtGtkGrid::removeColumn($this->handle, $position);

        return $this;
    }

    public function removeRow(int $position): static
    {
        ExtGtkGrid::removeRow($this->handle, $position);

        return $this;
    }

    public function setBaselineRow(int $row): static
    {
        ExtGtkGrid::setBaselineRow($this->handle, $row);

        return $this;
    }

    public function setColumnHomogeneous(bool $homogeneous): static
    {
        ExtGtkGrid::setColumnHomogeneous($this->handle, $homogeneous);

        return $this;
    }

    public function setColumnSpacing(int $spacing): static
    {
        ExtGtkGrid::setColumnSpacing($this->handle, $spacing);

        return $this;
    }

    public function setRowBaselinePosition(int $row, GtkBaselinePosition|int $pos): static
    {
        ExtGtkGrid::setRowBaselinePosition($this->handle, $row, ($pos instanceof GtkBaselinePosition ? $pos->value : $pos));

        return $this;
    }

    public function setRowHomogeneous(bool $homogeneous): static
    {
        ExtGtkGrid::setRowHomogeneous($this->handle, $homogeneous);

        return $this;
    }

    public function setRowSpacing(int $spacing): static
    {
        ExtGtkGrid::setRowSpacing($this->handle, $spacing);

        return $this;
    }
}
