<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkGLArea\GtkGLArea as ExtGtkGLArea;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkGLArea extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkGLArea::new_());
    }

    public function attachBuffers(): static
    {
        ExtGtkGLArea::attachBuffers($this->handle);

        return $this;
    }

    public function getAllowedApis(): int
    {
        return ExtGtkGLArea::getAllowedApis($this->handle);
    }

    public function getApi(): int
    {
        return ExtGtkGLArea::getApi($this->handle);
    }

    public function getAutoRender(): bool
    {
        return ExtGtkGLArea::getAutoRender($this->handle);
    }

    public function getContext(): ?GObject
    {
        return Registry::box(ExtGtkGLArea::getContext($this->handle));
    }

    public function getHasDepthBuffer(): bool
    {
        return ExtGtkGLArea::getHasDepthBuffer($this->handle);
    }

    public function getHasStencilBuffer(): bool
    {
        return ExtGtkGLArea::getHasStencilBuffer($this->handle);
    }

    /**
     * @return array{major: mixed, minor: mixed}
     */
    public function getRequiredVersion(): array
    {
        return ExtGtkGLArea::getRequiredVersion($this->handle);
    }

    public function makeCurrent(): static
    {
        ExtGtkGLArea::makeCurrent($this->handle);

        return $this;
    }

    public function queueRender(): static
    {
        ExtGtkGLArea::queueRender($this->handle);

        return $this;
    }

    public function setAllowedApis(int $apis): static
    {
        ExtGtkGLArea::setAllowedApis($this->handle, $apis);

        return $this;
    }

    public function setAutoRender(bool $autoRender): static
    {
        ExtGtkGLArea::setAutoRender($this->handle, $autoRender);

        return $this;
    }

    public function setHasDepthBuffer(bool $hasDepthBuffer): static
    {
        ExtGtkGLArea::setHasDepthBuffer($this->handle, $hasDepthBuffer);

        return $this;
    }

    public function setHasStencilBuffer(bool $hasStencilBuffer): static
    {
        ExtGtkGLArea::setHasStencilBuffer($this->handle, $hasStencilBuffer);

        return $this;
    }

    public function setRequiredVersion(int $major, int $minor): static
    {
        ExtGtkGLArea::setRequiredVersion($this->handle, $major, $minor);

        return $this;
    }

    public function onCreateContext(callable $callback): int
    {
        return Bridge::connect($this->handle, 'create-context', $callback);
    }

    public function onRender(callable $callback): int
    {
        return Bridge::connect($this->handle, 'render', $callback);
    }

    public function onResize(callable $callback): int
    {
        return Bridge::connect($this->handle, 'resize', $callback);
    }
}
