<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkHeaderBar\GtkHeaderBar as ExtGtkHeaderBar;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkHeaderBar extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkHeaderBar::new_());
    }

    public function getDecorationLayout(): ?string
    {
        return ExtGtkHeaderBar::getDecorationLayout($this->handle);
    }

    public function getShowTitleButtons(): bool
    {
        return ExtGtkHeaderBar::getShowTitleButtons($this->handle);
    }

    public function getTitleWidget(): ?GObject
    {
        return Registry::box(ExtGtkHeaderBar::getTitleWidget($this->handle));
    }

    public function getUseNativeControls(): bool
    {
        return ExtGtkHeaderBar::getUseNativeControls($this->handle);
    }

    public function packEnd(GtkWidget $child): static
    {
        ExtGtkHeaderBar::packEnd($this->handle, $child->handle);

        return $this;
    }

    public function packStart(GtkWidget $child): static
    {
        ExtGtkHeaderBar::packStart($this->handle, $child->handle);

        return $this;
    }

    public function remove(GtkWidget $child): static
    {
        ExtGtkHeaderBar::remove($this->handle, $child->handle);

        return $this;
    }

    public function setDecorationLayout(mixed $layout): static
    {
        ExtGtkHeaderBar::setDecorationLayout($this->handle, $layout);

        return $this;
    }

    public function setShowTitleButtons(bool $setting): static
    {
        ExtGtkHeaderBar::setShowTitleButtons($this->handle, $setting);

        return $this;
    }

    public function setTitleWidget(?GtkWidget $titleWidget): static
    {
        ExtGtkHeaderBar::setTitleWidget($this->handle, (is_null($titleWidget) ? 0 : $titleWidget->handle));

        return $this;
    }

    public function setUseNativeControls(bool $setting): static
    {
        ExtGtkHeaderBar::setUseNativeControls($this->handle, $setting);

        return $this;
    }
}
