<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkImage\GtkImage as ExtGtkImage;
use Jovian\Bindings\Gtk\Enums\GtkIconSize;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkImage extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkImage::new_());
    }

    public static function newFromFile(string $filename): self
    {
        return new self(ExtGtkImage::newFromFile($filename));
    }

    public static function newFromGicon(int $icon): self
    {
        return new self(ExtGtkImage::newFromGicon($icon));
    }

    public static function newFromIconName(mixed $iconName): self
    {
        return new self(ExtGtkImage::newFromIconName($iconName));
    }

    public static function newFromPaintable(int $paintable): self
    {
        return new self(ExtGtkImage::newFromPaintable($paintable));
    }

    public static function newFromResource(string $resourcePath): self
    {
        return new self(ExtGtkImage::newFromResource($resourcePath));
    }

    public function clear(): static
    {
        ExtGtkImage::clear($this->handle);

        return $this;
    }

    public function getGicon(): ?GObject
    {
        return Registry::box(ExtGtkImage::getGicon($this->handle));
    }

    public function getIconName(): ?string
    {
        return ExtGtkImage::getIconName($this->handle);
    }

    public function getIconSize(): int
    {
        return ExtGtkImage::getIconSize($this->handle);
    }

    public function getPaintable(): ?GObject
    {
        return Registry::box(ExtGtkImage::getPaintable($this->handle));
    }

    public function getPixelSize(): int
    {
        return ExtGtkImage::getPixelSize($this->handle);
    }

    public function getStorageType(): int
    {
        return ExtGtkImage::getStorageType($this->handle);
    }

    public function setFromFile(mixed $filename): static
    {
        ExtGtkImage::setFromFile($this->handle, $filename);

        return $this;
    }

    public function setFromGicon(int $icon): static
    {
        ExtGtkImage::setFromGicon($this->handle, $icon);

        return $this;
    }

    public function setFromIconName(mixed $iconName): static
    {
        ExtGtkImage::setFromIconName($this->handle, $iconName);

        return $this;
    }

    public function setFromPaintable(int $paintable): static
    {
        ExtGtkImage::setFromPaintable($this->handle, $paintable);

        return $this;
    }

    public function setFromResource(mixed $resourcePath): static
    {
        ExtGtkImage::setFromResource($this->handle, $resourcePath);

        return $this;
    }

    public function setIconSize(GtkIconSize|int $iconSize): static
    {
        ExtGtkImage::setIconSize($this->handle, ($iconSize instanceof GtkIconSize ? $iconSize->value : $iconSize));

        return $this;
    }

    public function setPixelSize(int $pixelSize): static
    {
        ExtGtkImage::setPixelSize($this->handle, $pixelSize);

        return $this;
    }
}
