<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkListBox\GtkListBox as ExtGtkListBox;
use Jovian\Bindings\Gtk\Enums\GtkListTabBehavior;
use Jovian\Bindings\Gtk\Enums\GtkSelectionMode;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkListBox extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkListBox::new_());
    }

    public function append(GtkWidget $child): static
    {
        ExtGtkListBox::append($this->handle, $child->handle);

        return $this;
    }

    public function dragHighlightRow(GtkListBoxRow $row): static
    {
        ExtGtkListBox::dragHighlightRow($this->handle, $row->handle);

        return $this;
    }

    public function dragUnhighlightRow(): static
    {
        ExtGtkListBox::dragUnhighlightRow($this->handle);

        return $this;
    }

    public function getActivateOnSingleClick(): bool
    {
        return ExtGtkListBox::getActivateOnSingleClick($this->handle);
    }

    public function getAdjustment(): ?GObject
    {
        return Registry::box(ExtGtkListBox::getAdjustment($this->handle));
    }

    public function getRowAtIndex(int $index): ?GObject
    {
        return Registry::box(ExtGtkListBox::getRowAtIndex($this->handle, $index));
    }

    public function getRowAtY(int $y): ?GObject
    {
        return Registry::box(ExtGtkListBox::getRowAtY($this->handle, $y));
    }

    public function getSelectedRow(): ?GObject
    {
        return Registry::box(ExtGtkListBox::getSelectedRow($this->handle));
    }

    public function getSelectedRows(): array
    {
        return ExtGtkListBox::getSelectedRows($this->handle);
    }

    public function getSelectionMode(): int
    {
        return ExtGtkListBox::getSelectionMode($this->handle);
    }

    public function getShowSeparators(): bool
    {
        return ExtGtkListBox::getShowSeparators($this->handle);
    }

    public function getTabBehavior(): int
    {
        return ExtGtkListBox::getTabBehavior($this->handle);
    }

    public function insert(GtkWidget $child, int $position): static
    {
        ExtGtkListBox::insert($this->handle, $child->handle, $position);

        return $this;
    }

    public function invalidateFilter(): static
    {
        ExtGtkListBox::invalidateFilter($this->handle);

        return $this;
    }

    public function invalidateHeaders(): static
    {
        ExtGtkListBox::invalidateHeaders($this->handle);

        return $this;
    }

    public function invalidateSort(): static
    {
        ExtGtkListBox::invalidateSort($this->handle);

        return $this;
    }

    public function prepend(GtkWidget $child): static
    {
        ExtGtkListBox::prepend($this->handle, $child->handle);

        return $this;
    }

    public function remove(GtkWidget $child): static
    {
        ExtGtkListBox::remove($this->handle, $child->handle);

        return $this;
    }

    public function removeAll(): static
    {
        ExtGtkListBox::removeAll($this->handle);

        return $this;
    }

    public function selectAll(): static
    {
        ExtGtkListBox::selectAll($this->handle);

        return $this;
    }

    public function selectRow(?GtkListBoxRow $row): static
    {
        ExtGtkListBox::selectRow($this->handle, (is_null($row) ? 0 : $row->handle));

        return $this;
    }

    public function setActivateOnSingleClick(bool $single): static
    {
        ExtGtkListBox::setActivateOnSingleClick($this->handle, $single);

        return $this;
    }

    public function setAdjustment(?GtkAdjustment $adjustment): static
    {
        ExtGtkListBox::setAdjustment($this->handle, (is_null($adjustment) ? 0 : $adjustment->handle));

        return $this;
    }

    public function setPlaceholder(?GtkWidget $placeholder): static
    {
        ExtGtkListBox::setPlaceholder($this->handle, (is_null($placeholder) ? 0 : $placeholder->handle));

        return $this;
    }

    public function setSelectionMode(GtkSelectionMode|int $mode): static
    {
        ExtGtkListBox::setSelectionMode($this->handle, ($mode instanceof GtkSelectionMode ? $mode->value : $mode));

        return $this;
    }

    public function setShowSeparators(bool $showSeparators): static
    {
        ExtGtkListBox::setShowSeparators($this->handle, $showSeparators);

        return $this;
    }

    public function setTabBehavior(GtkListTabBehavior|int $behavior): static
    {
        ExtGtkListBox::setTabBehavior($this->handle, ($behavior instanceof GtkListTabBehavior ? $behavior->value : $behavior));

        return $this;
    }

    public function unselectAll(): static
    {
        ExtGtkListBox::unselectAll($this->handle);

        return $this;
    }

    public function unselectRow(GtkListBoxRow $row): static
    {
        ExtGtkListBox::unselectRow($this->handle, $row->handle);

        return $this;
    }

    public function onActivateCursorRow(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-cursor-row', $callback);
    }

    public function onMoveCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-cursor', $callback);
    }

    public function onRowActivated(callable $callback): int
    {
        return Bridge::connect($this->handle, 'row-activated', $callback);
    }

    public function onRowSelected(callable $callback): int
    {
        return Bridge::connect($this->handle, 'row-selected', $callback);
    }

    public function onSelectAll(callable $callback): int
    {
        return Bridge::connect($this->handle, 'select-all', $callback);
    }

    public function onSelectedRowsChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'selected-rows-changed', $callback);
    }

    public function onToggleCursorRow(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-cursor-row', $callback);
    }

    public function onUnselectAll(callable $callback): int
    {
        return Bridge::connect($this->handle, 'unselect-all', $callback);
    }
}
