<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkLabel\GtkLabel as ExtGtkLabel;
use Jovian\Bindings\Gtk\Enums\GtkJustification;
use Jovian\Bindings\Gtk\Enums\GtkNaturalWrapMode;
use Jovian\Bindings\Gtk\Enums\PangoEllipsizeMode;
use Jovian\Bindings\Gtk\Enums\PangoWrapMode;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkLabel extends GtkWidget
{
    public static function new(mixed $str): self
    {
        return new self(ExtGtkLabel::new_($str));
    }

    public static function newWithMnemonic(mixed $str): self
    {
        return new self(ExtGtkLabel::newWithMnemonic($str));
    }

    public function getCurrentUri(): ?string
    {
        return ExtGtkLabel::getCurrentUri($this->handle);
    }

    public function getEllipsize(): int
    {
        return ExtGtkLabel::getEllipsize($this->handle);
    }

    public function getExtraMenu(): ?GObject
    {
        return Registry::box(ExtGtkLabel::getExtraMenu($this->handle));
    }

    public function getJustify(): int
    {
        return ExtGtkLabel::getJustify($this->handle);
    }

    public function getLabel(): string
    {
        return ExtGtkLabel::getLabel($this->handle);
    }

    public function getLayout(): ?GObject
    {
        return Registry::box(ExtGtkLabel::getLayout($this->handle));
    }

    /**
     * @return array{x: mixed, y: mixed}
     */
    public function getLayoutOffsets(): array
    {
        return ExtGtkLabel::getLayoutOffsets($this->handle);
    }

    public function getLines(): int
    {
        return ExtGtkLabel::getLines($this->handle);
    }

    public function getMaxWidthChars(): int
    {
        return ExtGtkLabel::getMaxWidthChars($this->handle);
    }

    public function getMnemonicKeyval(): int
    {
        return ExtGtkLabel::getMnemonicKeyval($this->handle);
    }

    public function getMnemonicWidget(): ?GObject
    {
        return Registry::box(ExtGtkLabel::getMnemonicWidget($this->handle));
    }

    public function getNaturalWrapMode(): int
    {
        return ExtGtkLabel::getNaturalWrapMode($this->handle);
    }

    public function getSelectable(): bool
    {
        return ExtGtkLabel::getSelectable($this->handle);
    }

    /**
     * @return array{start: mixed, end: mixed}
     */
    public function getSelectionBounds(): array
    {
        return ExtGtkLabel::getSelectionBounds($this->handle);
    }

    public function getSingleLineMode(): bool
    {
        return ExtGtkLabel::getSingleLineMode($this->handle);
    }

    public function getText(): string
    {
        return ExtGtkLabel::getText($this->handle);
    }

    public function getUseMarkup(): bool
    {
        return ExtGtkLabel::getUseMarkup($this->handle);
    }

    public function getUseUnderline(): bool
    {
        return ExtGtkLabel::getUseUnderline($this->handle);
    }

    public function getWidthChars(): int
    {
        return ExtGtkLabel::getWidthChars($this->handle);
    }

    public function getWrap(): bool
    {
        return ExtGtkLabel::getWrap($this->handle);
    }

    public function getWrapMode(): int
    {
        return ExtGtkLabel::getWrapMode($this->handle);
    }

    public function getXalign(): float
    {
        return ExtGtkLabel::getXalign($this->handle);
    }

    public function getYalign(): float
    {
        return ExtGtkLabel::getYalign($this->handle);
    }

    public function selectRegion(int $startOffset, int $endOffset): static
    {
        ExtGtkLabel::selectRegion($this->handle, $startOffset, $endOffset);

        return $this;
    }

    public function setEllipsize(PangoEllipsizeMode|int $mode): static
    {
        ExtGtkLabel::setEllipsize($this->handle, ($mode instanceof PangoEllipsizeMode ? $mode->value : $mode));

        return $this;
    }

    public function setExtraMenu(?GMenuModel $model): static
    {
        ExtGtkLabel::setExtraMenu($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setJustify(GtkJustification|int $jtype): static
    {
        ExtGtkLabel::setJustify($this->handle, ($jtype instanceof GtkJustification ? $jtype->value : $jtype));

        return $this;
    }

    public function setLabel(string $str): static
    {
        ExtGtkLabel::setLabel($this->handle, $str);

        return $this;
    }

    public function setLines(int $lines): static
    {
        ExtGtkLabel::setLines($this->handle, $lines);

        return $this;
    }

    public function setMarkup(string $str): static
    {
        ExtGtkLabel::setMarkup($this->handle, $str);

        return $this;
    }

    public function setMarkupWithMnemonic(string $str): static
    {
        ExtGtkLabel::setMarkupWithMnemonic($this->handle, $str);

        return $this;
    }

    public function setMaxWidthChars(int $nChars): static
    {
        ExtGtkLabel::setMaxWidthChars($this->handle, $nChars);

        return $this;
    }

    public function setMnemonicWidget(?GtkWidget $widget): static
    {
        ExtGtkLabel::setMnemonicWidget($this->handle, (is_null($widget) ? 0 : $widget->handle));

        return $this;
    }

    public function setNaturalWrapMode(GtkNaturalWrapMode|int $wrapMode): static
    {
        ExtGtkLabel::setNaturalWrapMode($this->handle, ($wrapMode instanceof GtkNaturalWrapMode ? $wrapMode->value : $wrapMode));

        return $this;
    }

    public function setSelectable(bool $setting): static
    {
        ExtGtkLabel::setSelectable($this->handle, $setting);

        return $this;
    }

    public function setSingleLineMode(bool $singleLineMode): static
    {
        ExtGtkLabel::setSingleLineMode($this->handle, $singleLineMode);

        return $this;
    }

    public function setText(string $str): static
    {
        ExtGtkLabel::setText($this->handle, $str);

        return $this;
    }

    public function setTextWithMnemonic(string $str): static
    {
        ExtGtkLabel::setTextWithMnemonic($this->handle, $str);

        return $this;
    }

    public function setUseMarkup(bool $setting): static
    {
        ExtGtkLabel::setUseMarkup($this->handle, $setting);

        return $this;
    }

    public function setUseUnderline(bool $setting): static
    {
        ExtGtkLabel::setUseUnderline($this->handle, $setting);

        return $this;
    }

    public function setWidthChars(int $nChars): static
    {
        ExtGtkLabel::setWidthChars($this->handle, $nChars);

        return $this;
    }

    public function setWrap(bool $wrap): static
    {
        ExtGtkLabel::setWrap($this->handle, $wrap);

        return $this;
    }

    public function setWrapMode(PangoWrapMode|int $wrapMode): static
    {
        ExtGtkLabel::setWrapMode($this->handle, ($wrapMode instanceof PangoWrapMode ? $wrapMode->value : $wrapMode));

        return $this;
    }

    public function setXalign(float $xalign): static
    {
        ExtGtkLabel::setXalign($this->handle, $xalign);

        return $this;
    }

    public function setYalign(float $yalign): static
    {
        ExtGtkLabel::setYalign($this->handle, $yalign);

        return $this;
    }

    public function onActivateCurrentLink(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-current-link', $callback);
    }

    public function onActivateLink(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-link', $callback);
    }

    public function onCopyClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'copy-clipboard', $callback);
    }

    public function onMoveCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-cursor', $callback);
    }
}
