<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkLevelBar\GtkLevelBar as ExtGtkLevelBar;
use Jovian\Bindings\Gtk\Enums\GtkLevelBarMode;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkLevelBar extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkLevelBar::new_());
    }

    public static function newForInterval(float $minValue, float $maxValue): self
    {
        return new self(ExtGtkLevelBar::newForInterval($minValue, $maxValue));
    }

    public function addOffsetValue(string $name, float $value): static
    {
        ExtGtkLevelBar::addOffsetValue($this->handle, $name, $value);

        return $this;
    }

    public function getInverted(): bool
    {
        return ExtGtkLevelBar::getInverted($this->handle);
    }

    public function getMaxValue(): float
    {
        return ExtGtkLevelBar::getMaxValue($this->handle);
    }

    public function getMinValue(): float
    {
        return ExtGtkLevelBar::getMinValue($this->handle);
    }

    public function getMode(): int
    {
        return ExtGtkLevelBar::getMode($this->handle);
    }

    /**
     * @return array{value: mixed}
     */
    public function getOffsetValue(mixed $name): array
    {
        return ExtGtkLevelBar::getOffsetValue($this->handle, $name);
    }

    public function getValue(): float
    {
        return ExtGtkLevelBar::getValue($this->handle);
    }

    public function removeOffsetValue(mixed $name): static
    {
        ExtGtkLevelBar::removeOffsetValue($this->handle, $name);

        return $this;
    }

    public function setInverted(bool $inverted): static
    {
        ExtGtkLevelBar::setInverted($this->handle, $inverted);

        return $this;
    }

    public function setMaxValue(float $value): static
    {
        ExtGtkLevelBar::setMaxValue($this->handle, $value);

        return $this;
    }

    public function setMinValue(float $value): static
    {
        ExtGtkLevelBar::setMinValue($this->handle, $value);

        return $this;
    }

    public function setMode(GtkLevelBarMode|int $mode): static
    {
        ExtGtkLevelBar::setMode($this->handle, ($mode instanceof GtkLevelBarMode ? $mode->value : $mode));

        return $this;
    }

    public function setValue(float $value): static
    {
        ExtGtkLevelBar::setValue($this->handle, $value);

        return $this;
    }

    public function onOffsetChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'offset-changed', $callback);
    }
}
