<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkListBoxRow\GtkListBoxRow as ExtGtkListBoxRow;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkListBoxRow extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public static function new(): self
    {
        return new self(ExtGtkListBoxRow::new_());
    }

    public function changed(): static
    {
        ExtGtkListBoxRow::changed($this->handle);

        return $this;
    }

    public function getActivatable(): bool
    {
        return ExtGtkListBoxRow::getActivatable($this->handle);
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkListBoxRow::getChild($this->handle));
    }

    public function getHeader(): ?GObject
    {
        return Registry::box(ExtGtkListBoxRow::getHeader($this->handle));
    }

    public function getIndex(): int
    {
        return ExtGtkListBoxRow::getIndex($this->handle);
    }

    public function getSelectable(): bool
    {
        return ExtGtkListBoxRow::getSelectable($this->handle);
    }

    public function isSelected(): bool
    {
        return ExtGtkListBoxRow::isSelected($this->handle);
    }

    public function setActivatable(bool $activatable): static
    {
        ExtGtkListBoxRow::setActivatable($this->handle, $activatable);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkListBoxRow::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setHeader(?GtkWidget $header): static
    {
        ExtGtkListBoxRow::setHeader($this->handle, (is_null($header) ? 0 : $header->handle));

        return $this;
    }

    public function setSelectable(bool $selectable): static
    {
        ExtGtkListBoxRow::setSelectable($this->handle, $selectable);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }
}
