<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkListItem\GtkListItem as ExtGtkListItem;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkListItem extends GObject
{
    public function getAccessibleDescription(): string
    {
        return ExtGtkListItem::getAccessibleDescription($this->handle);
    }

    public function getAccessibleLabel(): string
    {
        return ExtGtkListItem::getAccessibleLabel($this->handle);
    }

    public function getActivatable(): bool
    {
        return ExtGtkListItem::getActivatable($this->handle);
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkListItem::getChild($this->handle));
    }

    public function getFocusable(): bool
    {
        return ExtGtkListItem::getFocusable($this->handle);
    }

    public function getItem(): ?GObject
    {
        return Registry::box(ExtGtkListItem::getItem($this->handle));
    }

    public function getPosition(): int
    {
        return ExtGtkListItem::getPosition($this->handle);
    }

    public function getSelectable(): bool
    {
        return ExtGtkListItem::getSelectable($this->handle);
    }

    public function getSelected(): bool
    {
        return ExtGtkListItem::getSelected($this->handle);
    }

    public function setAccessibleDescription(string $description): static
    {
        ExtGtkListItem::setAccessibleDescription($this->handle, $description);

        return $this;
    }

    public function setAccessibleLabel(string $label): static
    {
        ExtGtkListItem::setAccessibleLabel($this->handle, $label);

        return $this;
    }

    public function setActivatable(bool $activatable): static
    {
        ExtGtkListItem::setActivatable($this->handle, $activatable);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkListItem::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setFocusable(bool $focusable): static
    {
        ExtGtkListItem::setFocusable($this->handle, $focusable);

        return $this;
    }

    public function setSelectable(bool $selectable): static
    {
        ExtGtkListItem::setSelectable($this->handle, $selectable);

        return $this;
    }
}
