<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkMediaStream\GtkMediaStream as ExtGtkMediaStream;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkMediaStream extends GObject
{
    public function getDuration(): int
    {
        return ExtGtkMediaStream::getDuration($this->handle);
    }

    public function getEnded(): bool
    {
        return ExtGtkMediaStream::getEnded($this->handle);
    }

    public function getLoop(): bool
    {
        return ExtGtkMediaStream::getLoop($this->handle);
    }

    public function getMuted(): bool
    {
        return ExtGtkMediaStream::getMuted($this->handle);
    }

    public function getPlaying(): bool
    {
        return ExtGtkMediaStream::getPlaying($this->handle);
    }

    public function getTimestamp(): int
    {
        return ExtGtkMediaStream::getTimestamp($this->handle);
    }

    public function getVolume(): float
    {
        return ExtGtkMediaStream::getVolume($this->handle);
    }

    public function hasAudio(): bool
    {
        return ExtGtkMediaStream::hasAudio($this->handle);
    }

    public function hasVideo(): bool
    {
        return ExtGtkMediaStream::hasVideo($this->handle);
    }

    public function isPrepared(): bool
    {
        return ExtGtkMediaStream::isPrepared($this->handle);
    }

    public function isSeekable(): bool
    {
        return ExtGtkMediaStream::isSeekable($this->handle);
    }

    public function isSeeking(): bool
    {
        return ExtGtkMediaStream::isSeeking($this->handle);
    }

    public function pause(): static
    {
        ExtGtkMediaStream::pause($this->handle);

        return $this;
    }

    public function play(): static
    {
        ExtGtkMediaStream::play($this->handle);

        return $this;
    }

    public function realize(int $surface): static
    {
        ExtGtkMediaStream::realize($this->handle, $surface);

        return $this;
    }

    public function seek(int $timestamp): static
    {
        ExtGtkMediaStream::seek($this->handle, $timestamp);

        return $this;
    }

    public function seekFailed(): static
    {
        ExtGtkMediaStream::seekFailed($this->handle);

        return $this;
    }

    public function seekSuccess(): static
    {
        ExtGtkMediaStream::seekSuccess($this->handle);

        return $this;
    }

    public function setLoop(bool $loop_): static
    {
        ExtGtkMediaStream::setLoop($this->handle, $loop_);

        return $this;
    }

    public function setMuted(bool $muted): static
    {
        ExtGtkMediaStream::setMuted($this->handle, $muted);

        return $this;
    }

    public function setPlaying(bool $playing): static
    {
        ExtGtkMediaStream::setPlaying($this->handle, $playing);

        return $this;
    }

    public function setVolume(float $volume): static
    {
        ExtGtkMediaStream::setVolume($this->handle, $volume);

        return $this;
    }

    public function streamEnded(): static
    {
        ExtGtkMediaStream::streamEnded($this->handle);

        return $this;
    }

    public function streamPrepared(bool $hasAudio, bool $hasVideo, bool $seekable, int $duration): static
    {
        ExtGtkMediaStream::streamPrepared($this->handle, $hasAudio, $hasVideo, $seekable, $duration);

        return $this;
    }

    public function streamUnprepared(): static
    {
        ExtGtkMediaStream::streamUnprepared($this->handle);

        return $this;
    }

    public function unrealize(int $surface): static
    {
        ExtGtkMediaStream::unrealize($this->handle, $surface);

        return $this;
    }

    public function update(int $timestamp): static
    {
        ExtGtkMediaStream::update($this->handle, $timestamp);

        return $this;
    }
}
