<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkNotebookPage\GtkNotebookPage as ExtGtkNotebookPage;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkNotebookPage extends GObject
{
    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkNotebookPage::getChild($this->handle));
    }
}
