<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkNotebook\GtkNotebook as ExtGtkNotebook;
use Jovian\Bindings\Gtk\Enums\GtkPackType;
use Jovian\Bindings\Gtk\Enums\GtkPositionType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkNotebook extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkNotebook::new_());
    }

    public function appendPage(GtkWidget $child, ?GtkWidget $tabLabel): int
    {
        return ExtGtkNotebook::appendPage($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle));
    }

    public function appendPageMenu(GtkWidget $child, ?GtkWidget $tabLabel, ?GtkWidget $menuLabel): int
    {
        return ExtGtkNotebook::appendPageMenu($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle), (is_null($menuLabel) ? 0 : $menuLabel->handle));
    }

    public function detachTab(GtkWidget $child): static
    {
        ExtGtkNotebook::detachTab($this->handle, $child->handle);

        return $this;
    }

    public function getActionWidget(GtkPackType|int $packType): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getActionWidget($this->handle, ($packType instanceof GtkPackType ? $packType->value : $packType)));
    }

    public function getCurrentPage(): int
    {
        return ExtGtkNotebook::getCurrentPage($this->handle);
    }

    public function getGroupName(): ?string
    {
        return ExtGtkNotebook::getGroupName($this->handle);
    }

    public function getMenuLabel(GtkWidget $child): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getMenuLabel($this->handle, $child->handle));
    }

    public function getMenuLabelText(GtkWidget $child): ?string
    {
        return ExtGtkNotebook::getMenuLabelText($this->handle, $child->handle);
    }

    public function getNPages(): int
    {
        return ExtGtkNotebook::getNPages($this->handle);
    }

    public function getNthPage(int $pageNum): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getNthPage($this->handle, $pageNum));
    }

    public function getPage(GtkWidget $child): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getPage($this->handle, $child->handle));
    }

    public function getPages(): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getPages($this->handle));
    }

    public function getScrollable(): bool
    {
        return ExtGtkNotebook::getScrollable($this->handle);
    }

    public function getShowBorder(): bool
    {
        return ExtGtkNotebook::getShowBorder($this->handle);
    }

    public function getShowTabs(): bool
    {
        return ExtGtkNotebook::getShowTabs($this->handle);
    }

    public function getTabDetachable(GtkWidget $child): bool
    {
        return ExtGtkNotebook::getTabDetachable($this->handle, $child->handle);
    }

    public function getTabLabel(GtkWidget $child): ?GObject
    {
        return Registry::box(ExtGtkNotebook::getTabLabel($this->handle, $child->handle));
    }

    public function getTabLabelText(GtkWidget $child): ?string
    {
        return ExtGtkNotebook::getTabLabelText($this->handle, $child->handle);
    }

    public function getTabPos(): int
    {
        return ExtGtkNotebook::getTabPos($this->handle);
    }

    public function getTabReorderable(GtkWidget $child): bool
    {
        return ExtGtkNotebook::getTabReorderable($this->handle, $child->handle);
    }

    public function insertPage(GtkWidget $child, ?GtkWidget $tabLabel, int $position): int
    {
        return ExtGtkNotebook::insertPage($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle), $position);
    }

    public function insertPageMenu(GtkWidget $child, ?GtkWidget $tabLabel, ?GtkWidget $menuLabel, int $position): int
    {
        return ExtGtkNotebook::insertPageMenu($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle), (is_null($menuLabel) ? 0 : $menuLabel->handle), $position);
    }

    public function nextPage(): static
    {
        ExtGtkNotebook::nextPage($this->handle);

        return $this;
    }

    public function pageNum(GtkWidget $child): int
    {
        return ExtGtkNotebook::pageNum($this->handle, $child->handle);
    }

    public function popupDisable(): static
    {
        ExtGtkNotebook::popupDisable($this->handle);

        return $this;
    }

    public function popupEnable(): static
    {
        ExtGtkNotebook::popupEnable($this->handle);

        return $this;
    }

    public function prependPage(GtkWidget $child, ?GtkWidget $tabLabel): int
    {
        return ExtGtkNotebook::prependPage($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle));
    }

    public function prependPageMenu(GtkWidget $child, ?GtkWidget $tabLabel, ?GtkWidget $menuLabel): int
    {
        return ExtGtkNotebook::prependPageMenu($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle), (is_null($menuLabel) ? 0 : $menuLabel->handle));
    }

    public function prevPage(): static
    {
        ExtGtkNotebook::prevPage($this->handle);

        return $this;
    }

    public function removePage(int $pageNum): static
    {
        ExtGtkNotebook::removePage($this->handle, $pageNum);

        return $this;
    }

    public function reorderChild(GtkWidget $child, int $position): static
    {
        ExtGtkNotebook::reorderChild($this->handle, $child->handle, $position);

        return $this;
    }

    public function setActionWidget(GtkWidget $widget, GtkPackType|int $packType): static
    {
        ExtGtkNotebook::setActionWidget($this->handle, $widget->handle, ($packType instanceof GtkPackType ? $packType->value : $packType));

        return $this;
    }

    public function setCurrentPage(int $pageNum): static
    {
        ExtGtkNotebook::setCurrentPage($this->handle, $pageNum);

        return $this;
    }

    public function setGroupName(mixed $groupName): static
    {
        ExtGtkNotebook::setGroupName($this->handle, $groupName);

        return $this;
    }

    public function setMenuLabel(GtkWidget $child, ?GtkWidget $menuLabel): static
    {
        ExtGtkNotebook::setMenuLabel($this->handle, $child->handle, (is_null($menuLabel) ? 0 : $menuLabel->handle));

        return $this;
    }

    public function setMenuLabelText(GtkWidget $child, string $menuText): static
    {
        ExtGtkNotebook::setMenuLabelText($this->handle, $child->handle, $menuText);

        return $this;
    }

    public function setScrollable(bool $scrollable): static
    {
        ExtGtkNotebook::setScrollable($this->handle, $scrollable);

        return $this;
    }

    public function setShowBorder(bool $showBorder): static
    {
        ExtGtkNotebook::setShowBorder($this->handle, $showBorder);

        return $this;
    }

    public function setShowTabs(bool $showTabs): static
    {
        ExtGtkNotebook::setShowTabs($this->handle, $showTabs);

        return $this;
    }

    public function setTabDetachable(GtkWidget $child, bool $detachable): static
    {
        ExtGtkNotebook::setTabDetachable($this->handle, $child->handle, $detachable);

        return $this;
    }

    public function setTabLabel(GtkWidget $child, ?GtkWidget $tabLabel): static
    {
        ExtGtkNotebook::setTabLabel($this->handle, $child->handle, (is_null($tabLabel) ? 0 : $tabLabel->handle));

        return $this;
    }

    public function setTabLabelText(GtkWidget $child, string $tabText): static
    {
        ExtGtkNotebook::setTabLabelText($this->handle, $child->handle, $tabText);

        return $this;
    }

    public function setTabPos(GtkPositionType|int $pos): static
    {
        ExtGtkNotebook::setTabPos($this->handle, ($pos instanceof GtkPositionType ? $pos->value : $pos));

        return $this;
    }

    public function setTabReorderable(GtkWidget $child, bool $reorderable): static
    {
        ExtGtkNotebook::setTabReorderable($this->handle, $child->handle, $reorderable);

        return $this;
    }

    public function onChangeCurrentPage(callable $callback): int
    {
        return Bridge::connect($this->handle, 'change-current-page', $callback);
    }

    public function onCreateWindow(callable $callback): int
    {
        return Bridge::connect($this->handle, 'create-window', $callback);
    }

    public function onFocusTab(callable $callback): int
    {
        return Bridge::connect($this->handle, 'focus-tab', $callback);
    }

    public function onMoveFocusOut(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-focus-out', $callback);
    }

    public function onPageAdded(callable $callback): int
    {
        return Bridge::connect($this->handle, 'page-added', $callback);
    }

    public function onPageRemoved(callable $callback): int
    {
        return Bridge::connect($this->handle, 'page-removed', $callback);
    }

    public function onPageReordered(callable $callback): int
    {
        return Bridge::connect($this->handle, 'page-reordered', $callback);
    }

    public function onReorderTab(callable $callback): int
    {
        return Bridge::connect($this->handle, 'reorder-tab', $callback);
    }

    public function onSelectPage(callable $callback): int
    {
        return Bridge::connect($this->handle, 'select-page', $callback);
    }

    public function onSwitchPage(callable $callback): int
    {
        return Bridge::connect($this->handle, 'switch-page', $callback);
    }
}
