<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkNoSelection\GtkNoSelection as ExtGtkNoSelection;
use Jovian\Bindings\Gtk\Contracts\GListModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkNoSelection extends GObject implements \Jovian\Bindings\Gtk\Contracts\GListModel, \Jovian\Bindings\Gtk\Contracts\GtkSelectionModel
{
    use \Jovian\Bindings\Gtk\Contracts\GListModelMethods, \Jovian\Bindings\Gtk\Contracts\GtkSelectionModelMethods;

    public static function new(?GListModel $model): self
    {
        return new self(ExtGtkNoSelection::new_((is_null($model) ? 0 : $model->handle)));
    }

    public function getModel(): ?GObject
    {
        return Registry::box(ExtGtkNoSelection::getModel($this->handle));
    }

    public function setModel(?GListModel $model): static
    {
        ExtGtkNoSelection::setModel($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }
}
