<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkOrientable\GtkOrientable as ExtGtkOrientable;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkOrientable extends GObject implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public function getOrientation(): int
    {
        return ExtGtkOrientable::getOrientation($this->handle);
    }

    public function setOrientation(GtkOrientation|int $orientation): static
    {
        ExtGtkOrientable::setOrientation($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation));

        return $this;
    }
}
