<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkOverlay\GtkOverlay as ExtGtkOverlay;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkOverlay extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkOverlay::new_());
    }

    public function addOverlay(GtkWidget $widget): static
    {
        ExtGtkOverlay::addOverlay($this->handle, $widget->handle);

        return $this;
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkOverlay::getChild($this->handle));
    }

    public function getClipOverlay(GtkWidget $widget): bool
    {
        return ExtGtkOverlay::getClipOverlay($this->handle, $widget->handle);
    }

    public function getMeasureOverlay(GtkWidget $widget): bool
    {
        return ExtGtkOverlay::getMeasureOverlay($this->handle, $widget->handle);
    }

    public function removeOverlay(GtkWidget $widget): static
    {
        ExtGtkOverlay::removeOverlay($this->handle, $widget->handle);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkOverlay::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setClipOverlay(GtkWidget $widget, bool $clipOverlay): static
    {
        ExtGtkOverlay::setClipOverlay($this->handle, $widget->handle, $clipOverlay);

        return $this;
    }

    public function setMeasureOverlay(GtkWidget $widget, bool $measure): static
    {
        ExtGtkOverlay::setMeasureOverlay($this->handle, $widget->handle, $measure);

        return $this;
    }

    public function onGetChildPosition(callable $callback): int
    {
        return Bridge::connect($this->handle, 'get-child-position', $callback);
    }
}
