<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkPopoverMenu\GtkPopoverMenu as ExtGtkPopoverMenu;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkPopoverMenu extends GtkPopover
{
    public static function newFromModel(?GMenuModel $model): self
    {
        return new self(ExtGtkPopoverMenu::newFromModel((is_null($model) ? 0 : $model->handle)));
    }

    public static function newFromModelFull(GMenuModel $model, int $flags): self
    {
        return new self(ExtGtkPopoverMenu::newFromModelFull($model->handle, $flags));
    }

    public function addChild(GtkWidget $child, string $id): bool
    {
        return ExtGtkPopoverMenu::addChild($this->handle, $child->handle, $id);
    }

    public function getFlags(): int
    {
        return ExtGtkPopoverMenu::getFlags($this->handle);
    }

    public function getMenuModel(): ?GObject
    {
        return Registry::box(ExtGtkPopoverMenu::getMenuModel($this->handle));
    }

    public function removeChild(GtkWidget $child): bool
    {
        return ExtGtkPopoverMenu::removeChild($this->handle, $child->handle);
    }

    public function setFlags(int $flags): static
    {
        ExtGtkPopoverMenu::setFlags($this->handle, $flags);

        return $this;
    }

    public function setMenuModel(?GMenuModel $model): static
    {
        ExtGtkPopoverMenu::setMenuModel($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }
}
