<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkPaned\GtkPaned as ExtGtkPaned;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkPaned extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(GtkOrientation|int $orientation): self
    {
        return new self(ExtGtkPaned::new_(($orientation instanceof GtkOrientation ? $orientation->value : $orientation)));
    }

    public function getEndChild(): ?GObject
    {
        return Registry::box(ExtGtkPaned::getEndChild($this->handle));
    }

    public function getPosition(): int
    {
        return ExtGtkPaned::getPosition($this->handle);
    }

    public function getResizeEndChild(): bool
    {
        return ExtGtkPaned::getResizeEndChild($this->handle);
    }

    public function getResizeStartChild(): bool
    {
        return ExtGtkPaned::getResizeStartChild($this->handle);
    }

    public function getShrinkEndChild(): bool
    {
        return ExtGtkPaned::getShrinkEndChild($this->handle);
    }

    public function getShrinkStartChild(): bool
    {
        return ExtGtkPaned::getShrinkStartChild($this->handle);
    }

    public function getStartChild(): ?GObject
    {
        return Registry::box(ExtGtkPaned::getStartChild($this->handle));
    }

    public function getWideHandle(): bool
    {
        return ExtGtkPaned::getWideHandle($this->handle);
    }

    public function setEndChild(?GtkWidget $child): static
    {
        ExtGtkPaned::setEndChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setPosition(int $position): static
    {
        ExtGtkPaned::setPosition($this->handle, $position);

        return $this;
    }

    public function setResizeEndChild(bool $resize): static
    {
        ExtGtkPaned::setResizeEndChild($this->handle, $resize);

        return $this;
    }

    public function setResizeStartChild(bool $resize): static
    {
        ExtGtkPaned::setResizeStartChild($this->handle, $resize);

        return $this;
    }

    public function setShrinkEndChild(bool $resize): static
    {
        ExtGtkPaned::setShrinkEndChild($this->handle, $resize);

        return $this;
    }

    public function setShrinkStartChild(bool $resize): static
    {
        ExtGtkPaned::setShrinkStartChild($this->handle, $resize);

        return $this;
    }

    public function setStartChild(?GtkWidget $child): static
    {
        ExtGtkPaned::setStartChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setWideHandle(bool $wide): static
    {
        ExtGtkPaned::setWideHandle($this->handle, $wide);

        return $this;
    }

    public function onAcceptPosition(callable $callback): int
    {
        return Bridge::connect($this->handle, 'accept-position', $callback);
    }

    public function onCancelPosition(callable $callback): int
    {
        return Bridge::connect($this->handle, 'cancel-position', $callback);
    }

    public function onCycleChildFocus(callable $callback): int
    {
        return Bridge::connect($this->handle, 'cycle-child-focus', $callback);
    }

    public function onCycleHandleFocus(callable $callback): int
    {
        return Bridge::connect($this->handle, 'cycle-handle-focus', $callback);
    }

    public function onMoveHandle(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-handle', $callback);
    }

    public function onToggleHandleFocus(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-handle-focus', $callback);
    }
}
