<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkPopover\GtkPopover as ExtGtkPopover;
use Jovian\Bindings\Gtk\Enums\GtkPositionType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;
use Jovian\Bindings\Gtk\Values\GdkRectangle;

class GtkPopover extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkPopover::new_());
    }

    public function getAutohide(): bool
    {
        return ExtGtkPopover::getAutohide($this->handle);
    }

    public function getCascadePopdown(): bool
    {
        return ExtGtkPopover::getCascadePopdown($this->handle);
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkPopover::getChild($this->handle));
    }

    public function getHasArrow(): bool
    {
        return ExtGtkPopover::getHasArrow($this->handle);
    }

    public function getMnemonicsVisible(): bool
    {
        return ExtGtkPopover::getMnemonicsVisible($this->handle);
    }

    /**
     * @return array{x_offset: mixed, y_offset: mixed}
     */
    public function getOffset(): array
    {
        return ExtGtkPopover::getOffset($this->handle);
    }

    public function getPointingTo(): GdkRectangle
    {
        return GdkRectangle::fromArray(ExtGtkPopover::getPointingTo($this->handle));
    }

    public function getPosition(): int
    {
        return ExtGtkPopover::getPosition($this->handle);
    }

    public function popdown(): static
    {
        ExtGtkPopover::popdown($this->handle);

        return $this;
    }

    public function popup(): static
    {
        ExtGtkPopover::popup($this->handle);

        return $this;
    }

    public function present(): static
    {
        ExtGtkPopover::present($this->handle);

        return $this;
    }

    public function setAutohide(bool $autohide): static
    {
        ExtGtkPopover::setAutohide($this->handle, $autohide);

        return $this;
    }

    public function setCascadePopdown(bool $cascadePopdown): static
    {
        ExtGtkPopover::setCascadePopdown($this->handle, $cascadePopdown);

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkPopover::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setDefaultWidget(?GtkWidget $widget): static
    {
        ExtGtkPopover::setDefaultWidget($this->handle, (is_null($widget) ? 0 : $widget->handle));

        return $this;
    }

    public function setHasArrow(bool $hasArrow): static
    {
        ExtGtkPopover::setHasArrow($this->handle, $hasArrow);

        return $this;
    }

    public function setMnemonicsVisible(bool $mnemonicsVisible): static
    {
        ExtGtkPopover::setMnemonicsVisible($this->handle, $mnemonicsVisible);

        return $this;
    }

    public function setOffset(int $xOffset, int $yOffset): static
    {
        ExtGtkPopover::setOffset($this->handle, $xOffset, $yOffset);

        return $this;
    }

    public function setPointingTo(GdkRectangle $rect): static
    {
        ExtGtkPopover::setPointingTo($this->handle, ...$rect->toArgs());

        return $this;
    }

    public function setPosition(GtkPositionType|int $position): static
    {
        ExtGtkPopover::setPosition($this->handle, ($position instanceof GtkPositionType ? $position->value : $position));

        return $this;
    }

    public function onActivateDefault(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-default', $callback);
    }

    public function onClosed(callable $callback): int
    {
        return Bridge::connect($this->handle, 'closed', $callback);
    }
}
