<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkPasswordEntry\GtkPasswordEntry as ExtGtkPasswordEntry;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkPasswordEntry extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkEditable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkEditableMethods;

    public static function new(): self
    {
        return new self(ExtGtkPasswordEntry::new_());
    }

    public function getExtraMenu(): ?GObject
    {
        return Registry::box(ExtGtkPasswordEntry::getExtraMenu($this->handle));
    }

    public function getShowPeekIcon(): bool
    {
        return ExtGtkPasswordEntry::getShowPeekIcon($this->handle);
    }

    public function setExtraMenu(?GMenuModel $model): static
    {
        ExtGtkPasswordEntry::setExtraMenu($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setShowPeekIcon(bool $showPeekIcon): static
    {
        ExtGtkPasswordEntry::setShowPeekIcon($this->handle, $showPeekIcon);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }
}
