<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkProgressBar\GtkProgressBar as ExtGtkProgressBar;
use Jovian\Bindings\Gtk\Enums\PangoEllipsizeMode;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkProgressBar extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkProgressBar::new_());
    }

    public function getEllipsize(): int
    {
        return ExtGtkProgressBar::getEllipsize($this->handle);
    }

    public function getFraction(): float
    {
        return ExtGtkProgressBar::getFraction($this->handle);
    }

    public function getInverted(): bool
    {
        return ExtGtkProgressBar::getInverted($this->handle);
    }

    public function getPulseStep(): float
    {
        return ExtGtkProgressBar::getPulseStep($this->handle);
    }

    public function getShowText(): bool
    {
        return ExtGtkProgressBar::getShowText($this->handle);
    }

    public function getText(): ?string
    {
        return ExtGtkProgressBar::getText($this->handle);
    }

    public function pulse(): static
    {
        ExtGtkProgressBar::pulse($this->handle);

        return $this;
    }

    public function setEllipsize(PangoEllipsizeMode|int $mode): static
    {
        ExtGtkProgressBar::setEllipsize($this->handle, ($mode instanceof PangoEllipsizeMode ? $mode->value : $mode));

        return $this;
    }

    public function setFraction(float $fraction): static
    {
        ExtGtkProgressBar::setFraction($this->handle, $fraction);

        return $this;
    }

    public function setInverted(bool $inverted): static
    {
        ExtGtkProgressBar::setInverted($this->handle, $inverted);

        return $this;
    }

    public function setPulseStep(float $fraction): static
    {
        ExtGtkProgressBar::setPulseStep($this->handle, $fraction);

        return $this;
    }

    public function setShowText(bool $showText): static
    {
        ExtGtkProgressBar::setShowText($this->handle, $showText);

        return $this;
    }

    public function setText(mixed $text): static
    {
        ExtGtkProgressBar::setText($this->handle, $text);

        return $this;
    }
}
