<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkRange\GtkRange as ExtGtkRange;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;
use Jovian\Bindings\Gtk\Values\GdkRectangle;

class GtkRange extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public function getAdjustment(): ?GObject
    {
        return Registry::box(ExtGtkRange::getAdjustment($this->handle));
    }

    public function getFillLevel(): float
    {
        return ExtGtkRange::getFillLevel($this->handle);
    }

    public function getFlippable(): bool
    {
        return ExtGtkRange::getFlippable($this->handle);
    }

    public function getInverted(): bool
    {
        return ExtGtkRange::getInverted($this->handle);
    }

    public function getRangeRect(): GdkRectangle
    {
        return GdkRectangle::fromArray(ExtGtkRange::getRangeRect($this->handle));
    }

    public function getRestrictToFillLevel(): bool
    {
        return ExtGtkRange::getRestrictToFillLevel($this->handle);
    }

    public function getRoundDigits(): int
    {
        return ExtGtkRange::getRoundDigits($this->handle);
    }

    public function getShowFillLevel(): bool
    {
        return ExtGtkRange::getShowFillLevel($this->handle);
    }

    /**
     * @return array{slider_start: mixed, slider_end: mixed}
     */
    public function getSliderRange(): array
    {
        return ExtGtkRange::getSliderRange($this->handle);
    }

    public function getSliderSizeFixed(): bool
    {
        return ExtGtkRange::getSliderSizeFixed($this->handle);
    }

    public function getValue(): float
    {
        return ExtGtkRange::getValue($this->handle);
    }

    public function setAdjustment(GtkAdjustment $adjustment): static
    {
        ExtGtkRange::setAdjustment($this->handle, $adjustment->handle);

        return $this;
    }

    public function setFillLevel(float $fillLevel): static
    {
        ExtGtkRange::setFillLevel($this->handle, $fillLevel);

        return $this;
    }

    public function setFlippable(bool $flippable): static
    {
        ExtGtkRange::setFlippable($this->handle, $flippable);

        return $this;
    }

    public function setIncrements(float $step, float $page): static
    {
        ExtGtkRange::setIncrements($this->handle, $step, $page);

        return $this;
    }

    public function setInverted(bool $setting): static
    {
        ExtGtkRange::setInverted($this->handle, $setting);

        return $this;
    }

    public function setRange(float $min, float $max): static
    {
        ExtGtkRange::setRange($this->handle, $min, $max);

        return $this;
    }

    public function setRestrictToFillLevel(bool $restrictToFillLevel): static
    {
        ExtGtkRange::setRestrictToFillLevel($this->handle, $restrictToFillLevel);

        return $this;
    }

    public function setRoundDigits(int $roundDigits): static
    {
        ExtGtkRange::setRoundDigits($this->handle, $roundDigits);

        return $this;
    }

    public function setShowFillLevel(bool $showFillLevel): static
    {
        ExtGtkRange::setShowFillLevel($this->handle, $showFillLevel);

        return $this;
    }

    public function setSliderSizeFixed(bool $sizeFixed): static
    {
        ExtGtkRange::setSliderSizeFixed($this->handle, $sizeFixed);

        return $this;
    }

    public function setValue(float $value): static
    {
        ExtGtkRange::setValue($this->handle, $value);

        return $this;
    }

    public function onAdjustBounds(callable $callback): int
    {
        return Bridge::connect($this->handle, 'adjust-bounds', $callback);
    }

    public function onChangeValue(callable $callback): int
    {
        return Bridge::connect($this->handle, 'change-value', $callback);
    }

    public function onMoveSlider(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-slider', $callback);
    }

    public function onValueChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'value-changed', $callback);
    }
}
