<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSignalListItemFactory\GtkSignalListItemFactory as ExtGtkSignalListItemFactory;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSignalListItemFactory extends GObject
{
    public static function new(): self
    {
        return new self(ExtGtkSignalListItemFactory::new_());
    }

    public function onBind(callable $callback): int
    {
        return Bridge::connect($this->handle, 'bind', $callback);
    }

    public function onSetup(callable $callback): int
    {
        return Bridge::connect($this->handle, 'setup', $callback);
    }

    public function onTeardown(callable $callback): int
    {
        return Bridge::connect($this->handle, 'teardown', $callback);
    }

    public function onUnbind(callable $callback): int
    {
        return Bridge::connect($this->handle, 'unbind', $callback);
    }
}
