<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSelectionModel\GtkSelectionModel as ExtGtkSelectionModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSelectionModel extends GObject implements \Jovian\Bindings\Gtk\Contracts\GtkSelectionModel
{
    use \Jovian\Bindings\Gtk\Contracts\GtkSelectionModelMethods;

    public function isSelected(int $position): bool
    {
        return ExtGtkSelectionModel::isSelected($this->handle, $position);
    }

    public function selectAll(): bool
    {
        return ExtGtkSelectionModel::selectAll($this->handle);
    }

    public function selectItem(int $position, bool $unselectRest): bool
    {
        return ExtGtkSelectionModel::selectItem($this->handle, $position, $unselectRest);
    }

    public function selectRange(int $position, int $nItems, bool $unselectRest): bool
    {
        return ExtGtkSelectionModel::selectRange($this->handle, $position, $nItems, $unselectRest);
    }

    public function selectionChanged(int $position, int $nItems): static
    {
        ExtGtkSelectionModel::selectionChanged($this->handle, $position, $nItems);

        return $this;
    }

    public function unselectAll(): bool
    {
        return ExtGtkSelectionModel::unselectAll($this->handle);
    }

    public function unselectItem(int $position): bool
    {
        return ExtGtkSelectionModel::unselectItem($this->handle, $position);
    }

    public function unselectRange(int $position, int $nItems): bool
    {
        return ExtGtkSelectionModel::unselectRange($this->handle, $position, $nItems);
    }

    public function onSelectionChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'selection-changed', $callback);
    }
}
