<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSingleSelection\GtkSingleSelection as ExtGtkSingleSelection;
use Jovian\Bindings\Gtk\Contracts\GListModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSingleSelection extends GObject implements \Jovian\Bindings\Gtk\Contracts\GListModel, \Jovian\Bindings\Gtk\Contracts\GtkSelectionModel
{
    use \Jovian\Bindings\Gtk\Contracts\GListModelMethods, \Jovian\Bindings\Gtk\Contracts\GtkSelectionModelMethods;

    public static function new(?GListModel $model): self
    {
        return new self(ExtGtkSingleSelection::new_((is_null($model) ? 0 : $model->handle)));
    }

    public function getAutoselect(): bool
    {
        return ExtGtkSingleSelection::getAutoselect($this->handle);
    }

    public function getCanUnselect(): bool
    {
        return ExtGtkSingleSelection::getCanUnselect($this->handle);
    }

    public function getModel(): ?GObject
    {
        return Registry::box(ExtGtkSingleSelection::getModel($this->handle));
    }

    public function getSelected(): int
    {
        return ExtGtkSingleSelection::getSelected($this->handle);
    }

    public function getSelectedItem(): ?GObject
    {
        return Registry::box(ExtGtkSingleSelection::getSelectedItem($this->handle));
    }

    public function setAutoselect(bool $autoselect): static
    {
        ExtGtkSingleSelection::setAutoselect($this->handle, $autoselect);

        return $this;
    }

    public function setCanUnselect(bool $canUnselect): static
    {
        ExtGtkSingleSelection::setCanUnselect($this->handle, $canUnselect);

        return $this;
    }

    public function setModel(?GListModel $model): static
    {
        ExtGtkSingleSelection::setModel($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setSelected(int $position): static
    {
        ExtGtkSingleSelection::setSelected($this->handle, $position);

        return $this;
    }
}
