<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkStringObject\GtkStringObject as ExtGtkStringObject;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkStringObject extends GObject
{
    public static function new(string $string_): self
    {
        return new self(ExtGtkStringObject::new_($string_));
    }

    public function getString(): ?string
    {
        return ExtGtkStringObject::getString($this->handle);
    }
}
