<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkStackSwitcher\GtkStackSwitcher as ExtGtkStackSwitcher;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkStackSwitcher extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(): self
    {
        return new self(ExtGtkStackSwitcher::new_());
    }

    public function getStack(): ?GObject
    {
        return Registry::box(ExtGtkStackSwitcher::getStack($this->handle));
    }

    public function setStack(?GtkStack $stack): static
    {
        ExtGtkStackSwitcher::setStack($this->handle, (is_null($stack) ? 0 : $stack->handle));

        return $this;
    }
}
