<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSpinButton\GtkSpinButton as ExtGtkSpinButton;
use Jovian\Bindings\Gtk\Enums\GtkSpinButtonUpdatePolicy;
use Jovian\Bindings\Gtk\Enums\GtkSpinType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSpinButton extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkEditable, \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkEditableMethods, \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(?GtkAdjustment $adjustment, float $climbRate, int $digits): self
    {
        return new self(ExtGtkSpinButton::new_((is_null($adjustment) ? 0 : $adjustment->handle), $climbRate, $digits));
    }

    public static function newWithRange(float $min, float $max, float $step): self
    {
        return new self(ExtGtkSpinButton::newWithRange($min, $max, $step));
    }

    public function configure(?GtkAdjustment $adjustment, float $climbRate, int $digits): static
    {
        ExtGtkSpinButton::configure($this->handle, (is_null($adjustment) ? 0 : $adjustment->handle), $climbRate, $digits);

        return $this;
    }

    public function getActivatesDefault(): bool
    {
        return ExtGtkSpinButton::getActivatesDefault($this->handle);
    }

    public function getAdjustment(): ?GObject
    {
        return Registry::box(ExtGtkSpinButton::getAdjustment($this->handle));
    }

    public function getClimbRate(): float
    {
        return ExtGtkSpinButton::getClimbRate($this->handle);
    }

    public function getDigits(): int
    {
        return ExtGtkSpinButton::getDigits($this->handle);
    }

    /**
     * @return array{step: mixed, page: mixed}
     */
    public function getIncrements(): array
    {
        return ExtGtkSpinButton::getIncrements($this->handle);
    }

    public function getNumeric(): bool
    {
        return ExtGtkSpinButton::getNumeric($this->handle);
    }

    /**
     * @return array{min: mixed, max: mixed}
     */
    public function getRange(): array
    {
        return ExtGtkSpinButton::getRange($this->handle);
    }

    public function getSnapToTicks(): bool
    {
        return ExtGtkSpinButton::getSnapToTicks($this->handle);
    }

    public function getUpdatePolicy(): int
    {
        return ExtGtkSpinButton::getUpdatePolicy($this->handle);
    }

    public function getValue(): float
    {
        return ExtGtkSpinButton::getValue($this->handle);
    }

    public function getValueAsInt(): int
    {
        return ExtGtkSpinButton::getValueAsInt($this->handle);
    }

    public function getWrap(): bool
    {
        return ExtGtkSpinButton::getWrap($this->handle);
    }

    public function setActivatesDefault(bool $activatesDefault): static
    {
        ExtGtkSpinButton::setActivatesDefault($this->handle, $activatesDefault);

        return $this;
    }

    public function setAdjustment(GtkAdjustment $adjustment): static
    {
        ExtGtkSpinButton::setAdjustment($this->handle, $adjustment->handle);

        return $this;
    }

    public function setClimbRate(float $climbRate): static
    {
        ExtGtkSpinButton::setClimbRate($this->handle, $climbRate);

        return $this;
    }

    public function setDigits(int $digits): static
    {
        ExtGtkSpinButton::setDigits($this->handle, $digits);

        return $this;
    }

    public function setIncrements(float $step, float $page): static
    {
        ExtGtkSpinButton::setIncrements($this->handle, $step, $page);

        return $this;
    }

    public function setNumeric(bool $numeric): static
    {
        ExtGtkSpinButton::setNumeric($this->handle, $numeric);

        return $this;
    }

    public function setRange(float $min, float $max): static
    {
        ExtGtkSpinButton::setRange($this->handle, $min, $max);

        return $this;
    }

    public function setSnapToTicks(bool $snapToTicks): static
    {
        ExtGtkSpinButton::setSnapToTicks($this->handle, $snapToTicks);

        return $this;
    }

    public function setUpdatePolicy(GtkSpinButtonUpdatePolicy|int $policy): static
    {
        ExtGtkSpinButton::setUpdatePolicy($this->handle, ($policy instanceof GtkSpinButtonUpdatePolicy ? $policy->value : $policy));

        return $this;
    }

    public function setValue(float $value): static
    {
        ExtGtkSpinButton::setValue($this->handle, $value);

        return $this;
    }

    public function setWrap(bool $wrap): static
    {
        ExtGtkSpinButton::setWrap($this->handle, $wrap);

        return $this;
    }

    public function spin(GtkSpinType|int $direction, float $increment): static
    {
        ExtGtkSpinButton::spin($this->handle, ($direction instanceof GtkSpinType ? $direction->value : $direction), $increment);

        return $this;
    }

    public function update(): static
    {
        ExtGtkSpinButton::update($this->handle);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onChangeValue(callable $callback): int
    {
        return Bridge::connect($this->handle, 'change-value', $callback);
    }

    public function onInput(callable $callback): int
    {
        return Bridge::connect($this->handle, 'input', $callback);
    }

    public function onOutput(callable $callback): int
    {
        return Bridge::connect($this->handle, 'output', $callback);
    }

    public function onValueChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'value-changed', $callback);
    }

    public function onWrapped(callable $callback): int
    {
        return Bridge::connect($this->handle, 'wrapped', $callback);
    }
}
