<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkScrollbar\GtkScrollbar as ExtGtkScrollbar;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkScrollbar extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(GtkOrientation|int $orientation, ?GtkAdjustment $adjustment): self
    {
        return new self(ExtGtkScrollbar::new_(($orientation instanceof GtkOrientation ? $orientation->value : $orientation), (is_null($adjustment) ? 0 : $adjustment->handle)));
    }

    public function getAdjustment(): ?GObject
    {
        return Registry::box(ExtGtkScrollbar::getAdjustment($this->handle));
    }

    public function setAdjustment(?GtkAdjustment $adjustment): static
    {
        ExtGtkScrollbar::setAdjustment($this->handle, (is_null($adjustment) ? 0 : $adjustment->handle));

        return $this;
    }
}
