<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkStringList\GtkStringList as ExtGtkStringList;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkStringList extends GObject implements \Jovian\Bindings\Gtk\Contracts\GListModel
{
    use \Jovian\Bindings\Gtk\Contracts\GListModelMethods;

    public static function new(mixed $strings): self
    {
        return new self(ExtGtkStringList::new_($strings));
    }

    public function append(string $string_): static
    {
        ExtGtkStringList::append($this->handle, $string_);

        return $this;
    }

    public function find(string $string_): int
    {
        return ExtGtkStringList::find($this->handle, $string_);
    }

    public function getString(int $position): ?string
    {
        return ExtGtkStringList::getString($this->handle, $position);
    }

    public function remove(int $position): static
    {
        ExtGtkStringList::remove($this->handle, $position);

        return $this;
    }

    public function splice(int $position, int $nRemovals, mixed $additions): static
    {
        ExtGtkStringList::splice($this->handle, $position, $nRemovals, $additions);

        return $this;
    }

    public function take(string $string_): static
    {
        ExtGtkStringList::take($this->handle, $string_);

        return $this;
    }
}
