<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSeparator\GtkSeparator as ExtGtkSeparator;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSeparator extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(GtkOrientation|int $orientation): self
    {
        return new self(ExtGtkSeparator::new_(($orientation instanceof GtkOrientation ? $orientation->value : $orientation)));
    }
}
