<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkStackSidebar\GtkStackSidebar as ExtGtkStackSidebar;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkStackSidebar extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkStackSidebar::new_());
    }

    public function getStack(): ?GObject
    {
        return Registry::box(ExtGtkStackSidebar::getStack($this->handle));
    }

    public function setStack(GtkStack $stack): static
    {
        ExtGtkStackSidebar::setStack($this->handle, $stack->handle);

        return $this;
    }
}
