<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkScrolledWindow\GtkScrolledWindow as ExtGtkScrolledWindow;
use Jovian\Bindings\Gtk\Enums\GtkCornerType;
use Jovian\Bindings\Gtk\Enums\GtkPolicyType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkScrolledWindow extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkScrolledWindow::new_());
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkScrolledWindow::getChild($this->handle));
    }

    public function getHadjustment(): ?GObject
    {
        return Registry::box(ExtGtkScrolledWindow::getHadjustment($this->handle));
    }

    public function getHasFrame(): bool
    {
        return ExtGtkScrolledWindow::getHasFrame($this->handle);
    }

    public function getHscrollbar(): ?GObject
    {
        return Registry::box(ExtGtkScrolledWindow::getHscrollbar($this->handle));
    }

    public function getKineticScrolling(): bool
    {
        return ExtGtkScrolledWindow::getKineticScrolling($this->handle);
    }

    public function getMaxContentHeight(): int
    {
        return ExtGtkScrolledWindow::getMaxContentHeight($this->handle);
    }

    public function getMaxContentWidth(): int
    {
        return ExtGtkScrolledWindow::getMaxContentWidth($this->handle);
    }

    public function getMinContentHeight(): int
    {
        return ExtGtkScrolledWindow::getMinContentHeight($this->handle);
    }

    public function getMinContentWidth(): int
    {
        return ExtGtkScrolledWindow::getMinContentWidth($this->handle);
    }

    public function getOverlayScrolling(): bool
    {
        return ExtGtkScrolledWindow::getOverlayScrolling($this->handle);
    }

    public function getPlacement(): int
    {
        return ExtGtkScrolledWindow::getPlacement($this->handle);
    }

    public function getPolicy(): array
    {
        return ExtGtkScrolledWindow::getPolicy($this->handle);
    }

    public function getPropagateNaturalHeight(): bool
    {
        return ExtGtkScrolledWindow::getPropagateNaturalHeight($this->handle);
    }

    public function getPropagateNaturalWidth(): bool
    {
        return ExtGtkScrolledWindow::getPropagateNaturalWidth($this->handle);
    }

    public function getVadjustment(): ?GObject
    {
        return Registry::box(ExtGtkScrolledWindow::getVadjustment($this->handle));
    }

    public function getVscrollbar(): ?GObject
    {
        return Registry::box(ExtGtkScrolledWindow::getVscrollbar($this->handle));
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkScrolledWindow::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setHadjustment(?GtkAdjustment $hadjustment): static
    {
        ExtGtkScrolledWindow::setHadjustment($this->handle, (is_null($hadjustment) ? 0 : $hadjustment->handle));

        return $this;
    }

    public function setHasFrame(bool $hasFrame): static
    {
        ExtGtkScrolledWindow::setHasFrame($this->handle, $hasFrame);

        return $this;
    }

    public function setKineticScrolling(bool $kineticScrolling): static
    {
        ExtGtkScrolledWindow::setKineticScrolling($this->handle, $kineticScrolling);

        return $this;
    }

    public function setMaxContentHeight(int $height): static
    {
        ExtGtkScrolledWindow::setMaxContentHeight($this->handle, $height);

        return $this;
    }

    public function setMaxContentWidth(int $width): static
    {
        ExtGtkScrolledWindow::setMaxContentWidth($this->handle, $width);

        return $this;
    }

    public function setMinContentHeight(int $height): static
    {
        ExtGtkScrolledWindow::setMinContentHeight($this->handle, $height);

        return $this;
    }

    public function setMinContentWidth(int $width): static
    {
        ExtGtkScrolledWindow::setMinContentWidth($this->handle, $width);

        return $this;
    }

    public function setOverlayScrolling(bool $overlayScrolling): static
    {
        ExtGtkScrolledWindow::setOverlayScrolling($this->handle, $overlayScrolling);

        return $this;
    }

    public function setPlacement(GtkCornerType|int $windowPlacement): static
    {
        ExtGtkScrolledWindow::setPlacement($this->handle, ($windowPlacement instanceof GtkCornerType ? $windowPlacement->value : $windowPlacement));

        return $this;
    }

    public function setPolicy(GtkPolicyType|int $hscrollbarPolicy, GtkPolicyType|int $vscrollbarPolicy): static
    {
        ExtGtkScrolledWindow::setPolicy($this->handle, ($hscrollbarPolicy instanceof GtkPolicyType ? $hscrollbarPolicy->value : $hscrollbarPolicy), ($vscrollbarPolicy instanceof GtkPolicyType ? $vscrollbarPolicy->value : $vscrollbarPolicy));

        return $this;
    }

    public function setPropagateNaturalHeight(bool $propagate): static
    {
        ExtGtkScrolledWindow::setPropagateNaturalHeight($this->handle, $propagate);

        return $this;
    }

    public function setPropagateNaturalWidth(bool $propagate): static
    {
        ExtGtkScrolledWindow::setPropagateNaturalWidth($this->handle, $propagate);

        return $this;
    }

    public function setVadjustment(?GtkAdjustment $vadjustment): static
    {
        ExtGtkScrolledWindow::setVadjustment($this->handle, (is_null($vadjustment) ? 0 : $vadjustment->handle));

        return $this;
    }

    public function unsetPlacement(): static
    {
        ExtGtkScrolledWindow::unsetPlacement($this->handle);

        return $this;
    }

    public function onEdgeOvershot(callable $callback): int
    {
        return Bridge::connect($this->handle, 'edge-overshot', $callback);
    }

    public function onEdgeReached(callable $callback): int
    {
        return Bridge::connect($this->handle, 'edge-reached', $callback);
    }

    public function onMoveFocusOut(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-focus-out', $callback);
    }

    public function onScrollChild(callable $callback): int
    {
        return Bridge::connect($this->handle, 'scroll-child', $callback);
    }
}
