<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkSwitch\GtkSwitch as ExtGtkSwitch;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkSwitch extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public static function new(): self
    {
        return new self(ExtGtkSwitch::new_());
    }

    public function getActive(): bool
    {
        return ExtGtkSwitch::getActive($this->handle);
    }

    public function getState(): bool
    {
        return ExtGtkSwitch::getState($this->handle);
    }

    public function setActive(bool $isActive): static
    {
        ExtGtkSwitch::setActive($this->handle, $isActive);

        return $this;
    }

    public function setState(bool $state): static
    {
        ExtGtkSwitch::setState($this->handle, $state);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onStateSet(callable $callback): int
    {
        return Bridge::connect($this->handle, 'state-set', $callback);
    }
}
