<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkScale\GtkScale as ExtGtkScale;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Enums\GtkPositionType;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkScale extends GtkRange implements \Jovian\Bindings\Gtk\Contracts\GtkOrientable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods;

    public static function new(GtkOrientation|int $orientation, ?GtkAdjustment $adjustment): self
    {
        return new self(ExtGtkScale::new_(($orientation instanceof GtkOrientation ? $orientation->value : $orientation), (is_null($adjustment) ? 0 : $adjustment->handle)));
    }

    public static function newWithRange(GtkOrientation|int $orientation, float $min, float $max, float $step): self
    {
        return new self(ExtGtkScale::newWithRange(($orientation instanceof GtkOrientation ? $orientation->value : $orientation), $min, $max, $step));
    }

    public function addMark(float $value, GtkPositionType|int $position, mixed $markup): static
    {
        ExtGtkScale::addMark($this->handle, $value, ($position instanceof GtkPositionType ? $position->value : $position), $markup);

        return $this;
    }

    public function clearMarks(): static
    {
        ExtGtkScale::clearMarks($this->handle);

        return $this;
    }

    public function getDigits(): int
    {
        return ExtGtkScale::getDigits($this->handle);
    }

    public function getDrawValue(): bool
    {
        return ExtGtkScale::getDrawValue($this->handle);
    }

    public function getHasOrigin(): bool
    {
        return ExtGtkScale::getHasOrigin($this->handle);
    }

    public function getLayout(): ?GObject
    {
        return Registry::box(ExtGtkScale::getLayout($this->handle));
    }

    /**
     * @return array{x: mixed, y: mixed}
     */
    public function getLayoutOffsets(): array
    {
        return ExtGtkScale::getLayoutOffsets($this->handle);
    }

    public function getValuePos(): int
    {
        return ExtGtkScale::getValuePos($this->handle);
    }

    public function setDigits(int $digits): static
    {
        ExtGtkScale::setDigits($this->handle, $digits);

        return $this;
    }

    public function setDrawValue(bool $drawValue): static
    {
        ExtGtkScale::setDrawValue($this->handle, $drawValue);

        return $this;
    }

    public function setHasOrigin(bool $hasOrigin): static
    {
        ExtGtkScale::setHasOrigin($this->handle, $hasOrigin);

        return $this;
    }

    public function setValuePos(GtkPositionType|int $pos): static
    {
        ExtGtkScale::setValuePos($this->handle, ($pos instanceof GtkPositionType ? $pos->value : $pos));

        return $this;
    }
}
