<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkText\GtkText as ExtGtkText;
use Jovian\Bindings\Gtk\Enums\GtkInputPurpose;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkText extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkEditable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkEditableMethods;

    public static function new(): self
    {
        return new self(ExtGtkText::new_());
    }

    public static function newWithBuffer(GtkEntryBuffer $buffer): self
    {
        return new self(ExtGtkText::newWithBuffer($buffer->handle));
    }

    public function computeCursorExtents(int $position): array
    {
        return ExtGtkText::computeCursorExtents($this->handle, $position);
    }

    public function getActivatesDefault(): bool
    {
        return ExtGtkText::getActivatesDefault($this->handle);
    }

    public function getBuffer(): ?GObject
    {
        return Registry::box(ExtGtkText::getBuffer($this->handle));
    }

    public function getEnableEmojiCompletion(): bool
    {
        return ExtGtkText::getEnableEmojiCompletion($this->handle);
    }

    public function getExtraMenu(): ?GObject
    {
        return Registry::box(ExtGtkText::getExtraMenu($this->handle));
    }

    public function getInputHints(): int
    {
        return ExtGtkText::getInputHints($this->handle);
    }

    public function getInputPurpose(): int
    {
        return ExtGtkText::getInputPurpose($this->handle);
    }

    public function getInvisibleChar(): int
    {
        return ExtGtkText::getInvisibleChar($this->handle);
    }

    public function getMaxLength(): int
    {
        return ExtGtkText::getMaxLength($this->handle);
    }

    public function getOverwriteMode(): bool
    {
        return ExtGtkText::getOverwriteMode($this->handle);
    }

    public function getPlaceholderText(): ?string
    {
        return ExtGtkText::getPlaceholderText($this->handle);
    }

    public function getPropagateTextWidth(): bool
    {
        return ExtGtkText::getPropagateTextWidth($this->handle);
    }

    public function getTextLength(): int
    {
        return ExtGtkText::getTextLength($this->handle);
    }

    public function getTruncateMultiline(): bool
    {
        return ExtGtkText::getTruncateMultiline($this->handle);
    }

    public function getVisibility(): bool
    {
        return ExtGtkText::getVisibility($this->handle);
    }

    public function grabFocusWithoutSelecting(): bool
    {
        return ExtGtkText::grabFocusWithoutSelecting($this->handle);
    }

    public function setActivatesDefault(bool $activates): static
    {
        ExtGtkText::setActivatesDefault($this->handle, $activates);

        return $this;
    }

    public function setBuffer(GtkEntryBuffer $buffer): static
    {
        ExtGtkText::setBuffer($this->handle, $buffer->handle);

        return $this;
    }

    public function setEnableEmojiCompletion(bool $enableEmojiCompletion): static
    {
        ExtGtkText::setEnableEmojiCompletion($this->handle, $enableEmojiCompletion);

        return $this;
    }

    public function setExtraMenu(?GMenuModel $model): static
    {
        ExtGtkText::setExtraMenu($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setInputHints(int $hints): static
    {
        ExtGtkText::setInputHints($this->handle, $hints);

        return $this;
    }

    public function setInputPurpose(GtkInputPurpose|int $purpose): static
    {
        ExtGtkText::setInputPurpose($this->handle, ($purpose instanceof GtkInputPurpose ? $purpose->value : $purpose));

        return $this;
    }

    public function setInvisibleChar(int $ch): static
    {
        ExtGtkText::setInvisibleChar($this->handle, $ch);

        return $this;
    }

    public function setMaxLength(int $length): static
    {
        ExtGtkText::setMaxLength($this->handle, $length);

        return $this;
    }

    public function setOverwriteMode(bool $overwrite): static
    {
        ExtGtkText::setOverwriteMode($this->handle, $overwrite);

        return $this;
    }

    public function setPlaceholderText(mixed $text): static
    {
        ExtGtkText::setPlaceholderText($this->handle, $text);

        return $this;
    }

    public function setPropagateTextWidth(bool $propagateTextWidth): static
    {
        ExtGtkText::setPropagateTextWidth($this->handle, $propagateTextWidth);

        return $this;
    }

    public function setTruncateMultiline(bool $truncateMultiline): static
    {
        ExtGtkText::setTruncateMultiline($this->handle, $truncateMultiline);

        return $this;
    }

    public function setVisibility(bool $visible): static
    {
        ExtGtkText::setVisibility($this->handle, $visible);

        return $this;
    }

    public function unsetInvisibleChar(): static
    {
        ExtGtkText::unsetInvisibleChar($this->handle);

        return $this;
    }

    public function onActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate', $callback);
    }

    public function onBackspace(callable $callback): int
    {
        return Bridge::connect($this->handle, 'backspace', $callback);
    }

    public function onCopyClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'copy-clipboard', $callback);
    }

    public function onCutClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'cut-clipboard', $callback);
    }

    public function onDeleteFromCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'delete-from-cursor', $callback);
    }

    public function onInsertAtCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-at-cursor', $callback);
    }

    public function onInsertEmoji(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-emoji', $callback);
    }

    public function onMoveCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-cursor', $callback);
    }

    public function onPasteClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'paste-clipboard', $callback);
    }

    public function onPreeditChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'preedit-changed', $callback);
    }

    public function onToggleOverwrite(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-overwrite', $callback);
    }
}
