<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkToggleButton\GtkToggleButton as ExtGtkToggleButton;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkToggleButton extends GtkButton implements \Jovian\Bindings\Gtk\Contracts\GtkActionable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkActionableMethods;

    public static function new(): self
    {
        return new self(ExtGtkToggleButton::new_());
    }

    public static function newWithLabel(string $label): self
    {
        return new self(ExtGtkToggleButton::newWithLabel($label));
    }

    public static function newWithMnemonic(string $label): self
    {
        return new self(ExtGtkToggleButton::newWithMnemonic($label));
    }

    public function getActive(): bool
    {
        return ExtGtkToggleButton::getActive($this->handle);
    }

    public function setActive(bool $isActive): static
    {
        ExtGtkToggleButton::setActive($this->handle, $isActive);

        return $this;
    }

    public function setGroup(?GtkToggleButton $group): static
    {
        ExtGtkToggleButton::setGroup($this->handle, (is_null($group) ? 0 : $group->handle));

        return $this;
    }

    public function onToggled(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggled', $callback);
    }
}
