<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkTextBuffer\GtkTextBuffer as ExtGtkTextBuffer;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkTextBuffer extends GObject
{
    public static function new(?GtkTextTagTable $table): self
    {
        return new self(ExtGtkTextBuffer::new_((is_null($table) ? 0 : $table->handle)));
    }

    public function addSelectionClipboard(int $clipboard): static
    {
        ExtGtkTextBuffer::addSelectionClipboard($this->handle, $clipboard);

        return $this;
    }

    public function beginIrreversibleAction(): static
    {
        ExtGtkTextBuffer::beginIrreversibleAction($this->handle);

        return $this;
    }

    public function beginUserAction(): static
    {
        ExtGtkTextBuffer::beginUserAction($this->handle);

        return $this;
    }

    public function copyClipboard(int $clipboard): static
    {
        ExtGtkTextBuffer::copyClipboard($this->handle, $clipboard);

        return $this;
    }

    public function cutClipboard(int $clipboard, bool $defaultEditable): static
    {
        ExtGtkTextBuffer::cutClipboard($this->handle, $clipboard, $defaultEditable);

        return $this;
    }

    public function deleteMark(GtkTextMark $mark): static
    {
        ExtGtkTextBuffer::deleteMark($this->handle, $mark->handle);

        return $this;
    }

    public function deleteMarkByName(string $name): static
    {
        ExtGtkTextBuffer::deleteMarkByName($this->handle, $name);

        return $this;
    }

    public function deleteSelection(bool $interactive, bool $defaultEditable): bool
    {
        return ExtGtkTextBuffer::deleteSelection($this->handle, $interactive, $defaultEditable);
    }

    public function endIrreversibleAction(): static
    {
        ExtGtkTextBuffer::endIrreversibleAction($this->handle);

        return $this;
    }

    public function endUserAction(): static
    {
        ExtGtkTextBuffer::endUserAction($this->handle);

        return $this;
    }

    public function getCanRedo(): bool
    {
        return ExtGtkTextBuffer::getCanRedo($this->handle);
    }

    public function getCanUndo(): bool
    {
        return ExtGtkTextBuffer::getCanUndo($this->handle);
    }

    public function getCharCount(): int
    {
        return ExtGtkTextBuffer::getCharCount($this->handle);
    }

    public function getEnableUndo(): bool
    {
        return ExtGtkTextBuffer::getEnableUndo($this->handle);
    }

    public function getHasSelection(): bool
    {
        return ExtGtkTextBuffer::getHasSelection($this->handle);
    }

    public function getInsert(): ?GObject
    {
        return Registry::box(ExtGtkTextBuffer::getInsert($this->handle));
    }

    public function getLineCount(): int
    {
        return ExtGtkTextBuffer::getLineCount($this->handle);
    }

    public function getMark(string $name): ?GObject
    {
        return Registry::box(ExtGtkTextBuffer::getMark($this->handle, $name));
    }

    public function getMaxUndoLevels(): int
    {
        return ExtGtkTextBuffer::getMaxUndoLevels($this->handle);
    }

    public function getModified(): bool
    {
        return ExtGtkTextBuffer::getModified($this->handle);
    }

    public function getSelectionBound(): ?GObject
    {
        return Registry::box(ExtGtkTextBuffer::getSelectionBound($this->handle));
    }

    public function getTagTable(): ?GObject
    {
        return Registry::box(ExtGtkTextBuffer::getTagTable($this->handle));
    }

    public function getText(int $startOffset, int $endOffset, bool $includeHiddenChars): ?string
    {
        return ExtGtkTextBuffer::getText($this->handle, $startOffset, $endOffset, $includeHiddenChars);
    }

    public function insertAtCursor(string $text, int $len): static
    {
        ExtGtkTextBuffer::insertAtCursor($this->handle, $text, $len);

        return $this;
    }

    public function insertInteractiveAtCursor(string $text, int $len, bool $defaultEditable): bool
    {
        return ExtGtkTextBuffer::insertInteractiveAtCursor($this->handle, $text, $len, $defaultEditable);
    }

    public function redo(): static
    {
        ExtGtkTextBuffer::redo($this->handle);

        return $this;
    }

    public function removeCommitNotify(int $commitNotifyHandler): static
    {
        ExtGtkTextBuffer::removeCommitNotify($this->handle, $commitNotifyHandler);

        return $this;
    }

    public function removeSelectionClipboard(int $clipboard): static
    {
        ExtGtkTextBuffer::removeSelectionClipboard($this->handle, $clipboard);

        return $this;
    }

    public function setEnableUndo(bool $enableUndo): static
    {
        ExtGtkTextBuffer::setEnableUndo($this->handle, $enableUndo);

        return $this;
    }

    public function setMaxUndoLevels(int $maxUndoLevels): static
    {
        ExtGtkTextBuffer::setMaxUndoLevels($this->handle, $maxUndoLevels);

        return $this;
    }

    public function setModified(bool $setting): static
    {
        ExtGtkTextBuffer::setModified($this->handle, $setting);

        return $this;
    }

    public function setText(string $text, int $len): static
    {
        ExtGtkTextBuffer::setText($this->handle, $text, $len);

        return $this;
    }

    public function undo(): static
    {
        ExtGtkTextBuffer::undo($this->handle);

        return $this;
    }

    public function onApplyTag(callable $callback): int
    {
        return Bridge::connect($this->handle, 'apply-tag', $callback);
    }

    public function onBeginUserAction(callable $callback): int
    {
        return Bridge::connect($this->handle, 'begin-user-action', $callback);
    }

    public function onChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'changed', $callback);
    }

    public function onDeleteRange(callable $callback): int
    {
        return Bridge::connect($this->handle, 'delete-range', $callback);
    }

    public function onEndUserAction(callable $callback): int
    {
        return Bridge::connect($this->handle, 'end-user-action', $callback);
    }

    public function onInsertChildAnchor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-child-anchor', $callback);
    }

    public function onInsertPaintable(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-paintable', $callback);
    }

    public function onInsertText(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-text', $callback);
    }

    public function onMarkDeleted(callable $callback): int
    {
        return Bridge::connect($this->handle, 'mark-deleted', $callback);
    }

    public function onMarkSet(callable $callback): int
    {
        return Bridge::connect($this->handle, 'mark-set', $callback);
    }

    public function onModifiedChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'modified-changed', $callback);
    }

    public function onPasteDone(callable $callback): int
    {
        return Bridge::connect($this->handle, 'paste-done', $callback);
    }

    public function onRedo(callable $callback): int
    {
        return Bridge::connect($this->handle, 'redo', $callback);
    }

    public function onRemoveTag(callable $callback): int
    {
        return Bridge::connect($this->handle, 'remove-tag', $callback);
    }

    public function onUndo(callable $callback): int
    {
        return Bridge::connect($this->handle, 'undo', $callback);
    }
}
