<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkTextView\GtkTextView as ExtGtkTextView;
use Jovian\Bindings\Gtk\Enums\GtkInputPurpose;
use Jovian\Bindings\Gtk\Enums\GtkJustification;
use Jovian\Bindings\Gtk\Enums\GtkTextWindowType;
use Jovian\Bindings\Gtk\Enums\GtkWrapMode;
use Jovian\Bindings\Gtk\Gio\GMenuModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;
use Jovian\Bindings\Gtk\Values\GdkRectangle;

class GtkTextView extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkScrollable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkScrollableMethods;

    public static function new(): self
    {
        return new self(ExtGtkTextView::new_());
    }

    public static function newWithBuffer(GtkTextBuffer $buffer): self
    {
        return new self(ExtGtkTextView::newWithBuffer($buffer->handle));
    }

    public function addChildAtAnchor(GtkWidget $child, int $anchor): static
    {
        ExtGtkTextView::addChildAtAnchor($this->handle, $child->handle, $anchor);

        return $this;
    }

    public function addOverlay(GtkWidget $child, int $xpos, int $ypos): static
    {
        ExtGtkTextView::addOverlay($this->handle, $child->handle, $xpos, $ypos);

        return $this;
    }

    /**
     * @return array{window_x: mixed, window_y: mixed}
     */
    public function bufferToWindowCoords(GtkTextWindowType|int $win, int $bufferX, int $bufferY): array
    {
        return ExtGtkTextView::bufferToWindowCoords($this->handle, ($win instanceof GtkTextWindowType ? $win->value : $win), $bufferX, $bufferY);
    }

    public function getAcceptsTab(): bool
    {
        return ExtGtkTextView::getAcceptsTab($this->handle);
    }

    public function getBottomMargin(): int
    {
        return ExtGtkTextView::getBottomMargin($this->handle);
    }

    public function getBuffer(): ?GObject
    {
        return Registry::box(ExtGtkTextView::getBuffer($this->handle));
    }

    public function getCursorVisible(): bool
    {
        return ExtGtkTextView::getCursorVisible($this->handle);
    }

    public function getEditable(): bool
    {
        return ExtGtkTextView::getEditable($this->handle);
    }

    public function getExtraMenu(): ?GObject
    {
        return Registry::box(ExtGtkTextView::getExtraMenu($this->handle));
    }

    public function getGutter(GtkTextWindowType|int $win): ?GObject
    {
        return Registry::box(ExtGtkTextView::getGutter($this->handle, ($win instanceof GtkTextWindowType ? $win->value : $win)));
    }

    public function getIndent(): int
    {
        return ExtGtkTextView::getIndent($this->handle);
    }

    public function getInputHints(): int
    {
        return ExtGtkTextView::getInputHints($this->handle);
    }

    public function getInputPurpose(): int
    {
        return ExtGtkTextView::getInputPurpose($this->handle);
    }

    public function getJustification(): int
    {
        return ExtGtkTextView::getJustification($this->handle);
    }

    public function getLeftMargin(): int
    {
        return ExtGtkTextView::getLeftMargin($this->handle);
    }

    public function getLtrContext(): ?GObject
    {
        return Registry::box(ExtGtkTextView::getLtrContext($this->handle));
    }

    public function getMonospace(): bool
    {
        return ExtGtkTextView::getMonospace($this->handle);
    }

    public function getOverwrite(): bool
    {
        return ExtGtkTextView::getOverwrite($this->handle);
    }

    public function getPixelsAboveLines(): int
    {
        return ExtGtkTextView::getPixelsAboveLines($this->handle);
    }

    public function getPixelsBelowLines(): int
    {
        return ExtGtkTextView::getPixelsBelowLines($this->handle);
    }

    public function getPixelsInsideWrap(): int
    {
        return ExtGtkTextView::getPixelsInsideWrap($this->handle);
    }

    public function getRightMargin(): int
    {
        return ExtGtkTextView::getRightMargin($this->handle);
    }

    public function getRtlContext(): ?GObject
    {
        return Registry::box(ExtGtkTextView::getRtlContext($this->handle));
    }

    public function getTopMargin(): int
    {
        return ExtGtkTextView::getTopMargin($this->handle);
    }

    /**
     * @return array{x_offset: mixed, y_offset: mixed}
     */
    public function getVisibleOffset(): array
    {
        return ExtGtkTextView::getVisibleOffset($this->handle);
    }

    public function getVisibleRect(): GdkRectangle
    {
        return GdkRectangle::fromArray(ExtGtkTextView::getVisibleRect($this->handle));
    }

    public function getWrapMode(): int
    {
        return ExtGtkTextView::getWrapMode($this->handle);
    }

    public function imContextFilterKeypress(int $event): bool
    {
        return ExtGtkTextView::imContextFilterKeypress($this->handle, $event);
    }

    public function moveMarkOnscreen(GtkTextMark $mark): bool
    {
        return ExtGtkTextView::moveMarkOnscreen($this->handle, $mark->handle);
    }

    public function moveOverlay(GtkWidget $child, int $xpos, int $ypos): static
    {
        ExtGtkTextView::moveOverlay($this->handle, $child->handle, $xpos, $ypos);

        return $this;
    }

    public function placeCursorOnscreen(): bool
    {
        return ExtGtkTextView::placeCursorOnscreen($this->handle);
    }

    public function remove(GtkWidget $child): static
    {
        ExtGtkTextView::remove($this->handle, $child->handle);

        return $this;
    }

    public function resetCursorBlink(): static
    {
        ExtGtkTextView::resetCursorBlink($this->handle);

        return $this;
    }

    public function resetImContext(): static
    {
        ExtGtkTextView::resetImContext($this->handle);

        return $this;
    }

    public function scrollMarkOnscreen(GtkTextMark $mark): static
    {
        ExtGtkTextView::scrollMarkOnscreen($this->handle, $mark->handle);

        return $this;
    }

    public function scrollToMark(GtkTextMark $mark, float $withinMargin, bool $useAlign, float $xalign, float $yalign): static
    {
        ExtGtkTextView::scrollToMark($this->handle, $mark->handle, $withinMargin, $useAlign, $xalign, $yalign);

        return $this;
    }

    public function setAcceptsTab(bool $acceptsTab): static
    {
        ExtGtkTextView::setAcceptsTab($this->handle, $acceptsTab);

        return $this;
    }

    public function setBottomMargin(int $bottomMargin): static
    {
        ExtGtkTextView::setBottomMargin($this->handle, $bottomMargin);

        return $this;
    }

    public function setBuffer(?GtkTextBuffer $buffer): static
    {
        ExtGtkTextView::setBuffer($this->handle, (is_null($buffer) ? 0 : $buffer->handle));

        return $this;
    }

    public function setCursorVisible(bool $setting): static
    {
        ExtGtkTextView::setCursorVisible($this->handle, $setting);

        return $this;
    }

    public function setEditable(bool $setting): static
    {
        ExtGtkTextView::setEditable($this->handle, $setting);

        return $this;
    }

    public function setExtraMenu(?GMenuModel $model): static
    {
        ExtGtkTextView::setExtraMenu($this->handle, (is_null($model) ? 0 : $model->handle));

        return $this;
    }

    public function setGutter(GtkTextWindowType|int $win, ?GtkWidget $widget): static
    {
        ExtGtkTextView::setGutter($this->handle, ($win instanceof GtkTextWindowType ? $win->value : $win), (is_null($widget) ? 0 : $widget->handle));

        return $this;
    }

    public function setIndent(int $indent): static
    {
        ExtGtkTextView::setIndent($this->handle, $indent);

        return $this;
    }

    public function setInputHints(int $hints): static
    {
        ExtGtkTextView::setInputHints($this->handle, $hints);

        return $this;
    }

    public function setInputPurpose(GtkInputPurpose|int $purpose): static
    {
        ExtGtkTextView::setInputPurpose($this->handle, ($purpose instanceof GtkInputPurpose ? $purpose->value : $purpose));

        return $this;
    }

    public function setJustification(GtkJustification|int $justification): static
    {
        ExtGtkTextView::setJustification($this->handle, ($justification instanceof GtkJustification ? $justification->value : $justification));

        return $this;
    }

    public function setLeftMargin(int $leftMargin): static
    {
        ExtGtkTextView::setLeftMargin($this->handle, $leftMargin);

        return $this;
    }

    public function setMonospace(bool $monospace): static
    {
        ExtGtkTextView::setMonospace($this->handle, $monospace);

        return $this;
    }

    public function setOverwrite(bool $overwrite): static
    {
        ExtGtkTextView::setOverwrite($this->handle, $overwrite);

        return $this;
    }

    public function setPixelsAboveLines(int $pixelsAboveLines): static
    {
        ExtGtkTextView::setPixelsAboveLines($this->handle, $pixelsAboveLines);

        return $this;
    }

    public function setPixelsBelowLines(int $pixelsBelowLines): static
    {
        ExtGtkTextView::setPixelsBelowLines($this->handle, $pixelsBelowLines);

        return $this;
    }

    public function setPixelsInsideWrap(int $pixelsInsideWrap): static
    {
        ExtGtkTextView::setPixelsInsideWrap($this->handle, $pixelsInsideWrap);

        return $this;
    }

    public function setRightMargin(int $rightMargin): static
    {
        ExtGtkTextView::setRightMargin($this->handle, $rightMargin);

        return $this;
    }

    public function setTopMargin(int $topMargin): static
    {
        ExtGtkTextView::setTopMargin($this->handle, $topMargin);

        return $this;
    }

    public function setWrapMode(GtkWrapMode|int $wrapMode): static
    {
        ExtGtkTextView::setWrapMode($this->handle, ($wrapMode instanceof GtkWrapMode ? $wrapMode->value : $wrapMode));

        return $this;
    }

    /**
     * @return array{buffer_x: mixed, buffer_y: mixed}
     */
    public function windowToBufferCoords(GtkTextWindowType|int $win, int $windowX, int $windowY): array
    {
        return ExtGtkTextView::windowToBufferCoords($this->handle, ($win instanceof GtkTextWindowType ? $win->value : $win), $windowX, $windowY);
    }

    public function onBackspace(callable $callback): int
    {
        return Bridge::connect($this->handle, 'backspace', $callback);
    }

    public function onCopyClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'copy-clipboard', $callback);
    }

    public function onCutClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'cut-clipboard', $callback);
    }

    public function onDeleteFromCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'delete-from-cursor', $callback);
    }

    public function onExtendSelection(callable $callback): int
    {
        return Bridge::connect($this->handle, 'extend-selection', $callback);
    }

    public function onInsertAtCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-at-cursor', $callback);
    }

    public function onInsertEmoji(callable $callback): int
    {
        return Bridge::connect($this->handle, 'insert-emoji', $callback);
    }

    public function onMoveCursor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-cursor', $callback);
    }

    public function onMoveViewport(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-viewport', $callback);
    }

    public function onPasteClipboard(callable $callback): int
    {
        return Bridge::connect($this->handle, 'paste-clipboard', $callback);
    }

    public function onPreeditChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'preedit-changed', $callback);
    }

    public function onSelectAll(callable $callback): int
    {
        return Bridge::connect($this->handle, 'select-all', $callback);
    }

    public function onSetAnchor(callable $callback): int
    {
        return Bridge::connect($this->handle, 'set-anchor', $callback);
    }

    public function onToggleCursorVisible(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-cursor-visible', $callback);
    }

    public function onToggleOverwrite(callable $callback): int
    {
        return Bridge::connect($this->handle, 'toggle-overwrite', $callback);
    }
}
