<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkVideo\GtkVideo as ExtGtkVideo;
use Jovian\Bindings\Gtk\Enums\GtkGraphicsOffloadEnabled;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkVideo extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkVideo::new_());
    }

    public static function newForFile(int $file): self
    {
        return new self(ExtGtkVideo::newForFile($file));
    }

    public static function newForFilename(mixed $filename): self
    {
        return new self(ExtGtkVideo::newForFilename($filename));
    }

    public static function newForMediaStream(?GtkMediaStream $stream): self
    {
        return new self(ExtGtkVideo::newForMediaStream((is_null($stream) ? 0 : $stream->handle)));
    }

    public static function newForResource(mixed $resourcePath): self
    {
        return new self(ExtGtkVideo::newForResource($resourcePath));
    }

    public function getAutoplay(): bool
    {
        return ExtGtkVideo::getAutoplay($this->handle);
    }

    public function getFile(): ?GObject
    {
        return Registry::box(ExtGtkVideo::getFile($this->handle));
    }

    public function getGraphicsOffload(): int
    {
        return ExtGtkVideo::getGraphicsOffload($this->handle);
    }

    public function getLoop(): bool
    {
        return ExtGtkVideo::getLoop($this->handle);
    }

    public function getMediaStream(): ?GObject
    {
        return Registry::box(ExtGtkVideo::getMediaStream($this->handle));
    }

    public function setAutoplay(bool $autoplay): static
    {
        ExtGtkVideo::setAutoplay($this->handle, $autoplay);

        return $this;
    }

    public function setFile(int $file): static
    {
        ExtGtkVideo::setFile($this->handle, $file);

        return $this;
    }

    public function setFilename(mixed $filename): static
    {
        ExtGtkVideo::setFilename($this->handle, $filename);

        return $this;
    }

    public function setGraphicsOffload(GtkGraphicsOffloadEnabled|int $enabled): static
    {
        ExtGtkVideo::setGraphicsOffload($this->handle, ($enabled instanceof GtkGraphicsOffloadEnabled ? $enabled->value : $enabled));

        return $this;
    }

    public function setLoop(bool $loop_): static
    {
        ExtGtkVideo::setLoop($this->handle, $loop_);

        return $this;
    }

    public function setMediaStream(?GtkMediaStream $stream): static
    {
        ExtGtkVideo::setMediaStream($this->handle, (is_null($stream) ? 0 : $stream->handle));

        return $this;
    }

    public function setResource(mixed $resourcePath): static
    {
        ExtGtkVideo::setResource($this->handle, $resourcePath);

        return $this;
    }
}
