<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkViewport\GtkViewport as ExtGtkViewport;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkViewport extends GtkWidget implements \Jovian\Bindings\Gtk\Contracts\GtkScrollable
{
    use \Jovian\Bindings\Gtk\Contracts\GtkScrollableMethods;

    public static function new(?GtkAdjustment $hadjustment, ?GtkAdjustment $vadjustment): self
    {
        return new self(ExtGtkViewport::new_((is_null($hadjustment) ? 0 : $hadjustment->handle), (is_null($vadjustment) ? 0 : $vadjustment->handle)));
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkViewport::getChild($this->handle));
    }

    public function getScrollToFocus(): bool
    {
        return ExtGtkViewport::getScrollToFocus($this->handle);
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkViewport::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setScrollToFocus(bool $scrollToFocus): static
    {
        ExtGtkViewport::setScrollToFocus($this->handle, $scrollToFocus);

        return $this;
    }
}
