<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkWidget\GtkWidget as ExtGtkWidget;
use Jovian\Bindings\Gtk\Enums\GtkAlign;
use Jovian\Bindings\Gtk\Enums\GtkDirectionType;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Enums\GtkOverflow;
use Jovian\Bindings\Gtk\Enums\GtkTextDirection;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;
use Jovian\Bindings\Gtk\Values\GdkRGBA;
use Jovian\Bindings\Gtk\Values\GraphenePoint;
use Jovian\Bindings\Gtk\Values\GrapheneRect;

class GtkWidget extends GObject
{
    public static function getDefaultDirection(): int
    {
        return ExtGtkWidget::getDefaultDirection();
    }

    public static function setDefaultDirection(GtkTextDirection|int $dir): void
    {
        ExtGtkWidget::setDefaultDirection(($dir instanceof GtkTextDirection ? $dir->value : $dir));
    }

    public function actionSetEnabled(string $actionName, bool $enabled): static
    {
        ExtGtkWidget::actionSetEnabled($this->handle, $actionName, $enabled);

        return $this;
    }

    public function activate(): bool
    {
        return ExtGtkWidget::activate($this->handle);
    }

    public function activateDefault(): static
    {
        ExtGtkWidget::activateDefault($this->handle);

        return $this;
    }

    public function addController(int $controller): static
    {
        ExtGtkWidget::addController($this->handle, $controller);

        return $this;
    }

    public function addCssClass(string $cssClass): static
    {
        ExtGtkWidget::addCssClass($this->handle, $cssClass);

        return $this;
    }

    public function addMnemonicLabel(GtkWidget $label): static
    {
        ExtGtkWidget::addMnemonicLabel($this->handle, $label->handle);

        return $this;
    }

    public function childFocus(GtkDirectionType|int $direction): bool
    {
        return ExtGtkWidget::childFocus($this->handle, ($direction instanceof GtkDirectionType ? $direction->value : $direction));
    }

    public function computeBounds(GtkWidget $target): GrapheneRect
    {
        return GrapheneRect::fromArray(ExtGtkWidget::computeBounds($this->handle, $target->handle));
    }

    public function computeExpand(GtkOrientation|int $orientation): bool
    {
        return ExtGtkWidget::computeExpand($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation));
    }

    public function computePoint(GtkWidget $target, GraphenePoint $point): GraphenePoint
    {
        return GraphenePoint::fromArray(ExtGtkWidget::computePoint($this->handle, $target->handle, ...$point->toArgs()));
    }

    public function contains(float $x, float $y): bool
    {
        return ExtGtkWidget::contains($this->handle, $x, $y);
    }

    public function createPangoContext(): ?GObject
    {
        return Registry::box(ExtGtkWidget::createPangoContext($this->handle));
    }

    public function createPangoLayout(mixed $text): ?GObject
    {
        return Registry::box(ExtGtkWidget::createPangoLayout($this->handle, $text));
    }

    public function disposeTemplate(int $widgetType): static
    {
        ExtGtkWidget::disposeTemplate($this->handle, $widgetType);

        return $this;
    }

    public function dragCheckThreshold(int $startX, int $startY, int $currentX, int $currentY): bool
    {
        return ExtGtkWidget::dragCheckThreshold($this->handle, $startX, $startY, $currentX, $currentY);
    }

    public function errorBell(): static
    {
        ExtGtkWidget::errorBell($this->handle);

        return $this;
    }

    public function getAncestor(int $widgetType): ?GObject
    {
        return Registry::box(ExtGtkWidget::getAncestor($this->handle, $widgetType));
    }

    public function getBaseline(): int
    {
        return ExtGtkWidget::getBaseline($this->handle);
    }

    public function getCanFocus(): bool
    {
        return ExtGtkWidget::getCanFocus($this->handle);
    }

    public function getCanTarget(): bool
    {
        return ExtGtkWidget::getCanTarget($this->handle);
    }

    public function getChildVisible(): bool
    {
        return ExtGtkWidget::getChildVisible($this->handle);
    }

    public function getClipboard(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getClipboard($this->handle));
    }

    public function getColor(): GdkRGBA
    {
        return GdkRGBA::fromArray(ExtGtkWidget::getColor($this->handle));
    }

    public function getCssClasses(): array
    {
        return ExtGtkWidget::getCssClasses($this->handle);
    }

    public function getCssName(): string
    {
        return ExtGtkWidget::getCssName($this->handle);
    }

    public function getCursor(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getCursor($this->handle));
    }

    public function getDirection(): int
    {
        return ExtGtkWidget::getDirection($this->handle);
    }

    public function getDisplay(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getDisplay($this->handle));
    }

    public function getFirstChild(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getFirstChild($this->handle));
    }

    public function getFocusChild(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getFocusChild($this->handle));
    }

    public function getFocusOnClick(): bool
    {
        return ExtGtkWidget::getFocusOnClick($this->handle);
    }

    public function getFocusable(): bool
    {
        return ExtGtkWidget::getFocusable($this->handle);
    }

    public function getFontMap(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getFontMap($this->handle));
    }

    public function getFrameClock(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getFrameClock($this->handle));
    }

    public function getHalign(): int
    {
        return ExtGtkWidget::getHalign($this->handle);
    }

    public function getHasTooltip(): bool
    {
        return ExtGtkWidget::getHasTooltip($this->handle);
    }

    public function getHeight(): int
    {
        return ExtGtkWidget::getHeight($this->handle);
    }

    public function getHexpand(): bool
    {
        return ExtGtkWidget::getHexpand($this->handle);
    }

    public function getHexpandSet(): bool
    {
        return ExtGtkWidget::getHexpandSet($this->handle);
    }

    public function getLastChild(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getLastChild($this->handle));
    }

    public function getLayoutManager(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getLayoutManager($this->handle));
    }

    public function getLimitEvents(): bool
    {
        return ExtGtkWidget::getLimitEvents($this->handle);
    }

    public function getMapped(): bool
    {
        return ExtGtkWidget::getMapped($this->handle);
    }

    public function getMarginBottom(): int
    {
        return ExtGtkWidget::getMarginBottom($this->handle);
    }

    public function getMarginEnd(): int
    {
        return ExtGtkWidget::getMarginEnd($this->handle);
    }

    public function getMarginStart(): int
    {
        return ExtGtkWidget::getMarginStart($this->handle);
    }

    public function getMarginTop(): int
    {
        return ExtGtkWidget::getMarginTop($this->handle);
    }

    public function getName(): string
    {
        return ExtGtkWidget::getName($this->handle);
    }

    public function getNative(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getNative($this->handle));
    }

    public function getNextSibling(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getNextSibling($this->handle));
    }

    public function getOpacity(): float
    {
        return ExtGtkWidget::getOpacity($this->handle);
    }

    public function getOverflow(): int
    {
        return ExtGtkWidget::getOverflow($this->handle);
    }

    public function getPangoContext(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getPangoContext($this->handle));
    }

    public function getParent(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getParent($this->handle));
    }

    public function getPreferredSize(): array
    {
        return ExtGtkWidget::getPreferredSize($this->handle);
    }

    public function getPrevSibling(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getPrevSibling($this->handle));
    }

    public function getPrimaryClipboard(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getPrimaryClipboard($this->handle));
    }

    public function getRealized(): bool
    {
        return ExtGtkWidget::getRealized($this->handle);
    }

    public function getReceivesDefault(): bool
    {
        return ExtGtkWidget::getReceivesDefault($this->handle);
    }

    public function getRequestMode(): int
    {
        return ExtGtkWidget::getRequestMode($this->handle);
    }

    public function getRoot(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getRoot($this->handle));
    }

    public function getScaleFactor(): int
    {
        return ExtGtkWidget::getScaleFactor($this->handle);
    }

    public function getSensitive(): bool
    {
        return ExtGtkWidget::getSensitive($this->handle);
    }

    public function getSettings(): ?GObject
    {
        return Registry::box(ExtGtkWidget::getSettings($this->handle));
    }

    public function getSize(GtkOrientation|int $orientation): int
    {
        return ExtGtkWidget::getSize($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation));
    }

    /**
     * @return array{width: mixed, height: mixed}
     */
    public function getSizeRequest(): array
    {
        return ExtGtkWidget::getSizeRequest($this->handle);
    }

    public function getStateFlags(): int
    {
        return ExtGtkWidget::getStateFlags($this->handle);
    }

    public function getTemplateChild(int $widgetType, string $name): ?GObject
    {
        return Registry::box(ExtGtkWidget::getTemplateChild($this->handle, $widgetType, $name));
    }

    public function getTooltipMarkup(): ?string
    {
        return ExtGtkWidget::getTooltipMarkup($this->handle);
    }

    public function getTooltipText(): ?string
    {
        return ExtGtkWidget::getTooltipText($this->handle);
    }

    public function getValign(): int
    {
        return ExtGtkWidget::getValign($this->handle);
    }

    public function getVexpand(): bool
    {
        return ExtGtkWidget::getVexpand($this->handle);
    }

    public function getVexpandSet(): bool
    {
        return ExtGtkWidget::getVexpandSet($this->handle);
    }

    public function getVisible(): bool
    {
        return ExtGtkWidget::getVisible($this->handle);
    }

    public function getWidth(): int
    {
        return ExtGtkWidget::getWidth($this->handle);
    }

    public function grabFocus(): bool
    {
        return ExtGtkWidget::grabFocus($this->handle);
    }

    public function hasCssClass(string $cssClass): bool
    {
        return ExtGtkWidget::hasCssClass($this->handle, $cssClass);
    }

    public function hasDefault(): bool
    {
        return ExtGtkWidget::hasDefault($this->handle);
    }

    public function hasFocus(): bool
    {
        return ExtGtkWidget::hasFocus($this->handle);
    }

    public function hasVisibleFocus(): bool
    {
        return ExtGtkWidget::hasVisibleFocus($this->handle);
    }

    public function inDestruction(): bool
    {
        return ExtGtkWidget::inDestruction($this->handle);
    }

    public function initTemplate(): static
    {
        ExtGtkWidget::initTemplate($this->handle);

        return $this;
    }

    public function insertActionGroup(string $name, int $group): static
    {
        ExtGtkWidget::insertActionGroup($this->handle, $name, $group);

        return $this;
    }

    public function insertAfter(GtkWidget $parent, ?GtkWidget $previousSibling): static
    {
        ExtGtkWidget::insertAfter($this->handle, $parent->handle, (is_null($previousSibling) ? 0 : $previousSibling->handle));

        return $this;
    }

    public function insertBefore(GtkWidget $parent, ?GtkWidget $nextSibling): static
    {
        ExtGtkWidget::insertBefore($this->handle, $parent->handle, (is_null($nextSibling) ? 0 : $nextSibling->handle));

        return $this;
    }

    public function isAncestor(GtkWidget $ancestor): bool
    {
        return ExtGtkWidget::isAncestor($this->handle, $ancestor->handle);
    }

    public function isDrawable(): bool
    {
        return ExtGtkWidget::isDrawable($this->handle);
    }

    public function isFocus(): bool
    {
        return ExtGtkWidget::isFocus($this->handle);
    }

    public function isSensitive(): bool
    {
        return ExtGtkWidget::isSensitive($this->handle);
    }

    public function isVisible(): bool
    {
        return ExtGtkWidget::isVisible($this->handle);
    }

    public function keynavFailed(GtkDirectionType|int $direction): bool
    {
        return ExtGtkWidget::keynavFailed($this->handle, ($direction instanceof GtkDirectionType ? $direction->value : $direction));
    }

    public function listMnemonicLabels(): array
    {
        return ExtGtkWidget::listMnemonicLabels($this->handle);
    }

    public function map(): static
    {
        ExtGtkWidget::map($this->handle);

        return $this;
    }

    /**
     * @return array{minimum: mixed, natural: mixed, minimum_baseline: mixed, natural_baseline: mixed}
     */
    public function measure(GtkOrientation|int $orientation, int $forSize): array
    {
        return ExtGtkWidget::measure($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation), $forSize);
    }

    public function mnemonicActivate(bool $groupCycling): bool
    {
        return ExtGtkWidget::mnemonicActivate($this->handle, $groupCycling);
    }

    public function observeChildren(): ?GObject
    {
        return Registry::box(ExtGtkWidget::observeChildren($this->handle));
    }

    public function observeControllers(): ?GObject
    {
        return Registry::box(ExtGtkWidget::observeControllers($this->handle));
    }

    public function pick(float $x, float $y, int $flags): ?GObject
    {
        return Registry::box(ExtGtkWidget::pick($this->handle, $x, $y, $flags));
    }

    public function queueAllocate(): static
    {
        ExtGtkWidget::queueAllocate($this->handle);

        return $this;
    }

    public function queueDraw(): static
    {
        ExtGtkWidget::queueDraw($this->handle);

        return $this;
    }

    public function queueResize(): static
    {
        ExtGtkWidget::queueResize($this->handle);

        return $this;
    }

    public function realize(): static
    {
        ExtGtkWidget::realize($this->handle);

        return $this;
    }

    public function removeController(int $controller): static
    {
        ExtGtkWidget::removeController($this->handle, $controller);

        return $this;
    }

    public function removeCssClass(string $cssClass): static
    {
        ExtGtkWidget::removeCssClass($this->handle, $cssClass);

        return $this;
    }

    public function removeMnemonicLabel(GtkWidget $label): static
    {
        ExtGtkWidget::removeMnemonicLabel($this->handle, $label->handle);

        return $this;
    }

    public function removeTickCallback(int $id): static
    {
        ExtGtkWidget::removeTickCallback($this->handle, $id);

        return $this;
    }

    public function setCanFocus(bool $canFocus): static
    {
        ExtGtkWidget::setCanFocus($this->handle, $canFocus);

        return $this;
    }

    public function setCanTarget(bool $canTarget): static
    {
        ExtGtkWidget::setCanTarget($this->handle, $canTarget);

        return $this;
    }

    public function setChildVisible(bool $childVisible): static
    {
        ExtGtkWidget::setChildVisible($this->handle, $childVisible);

        return $this;
    }

    public function setCssClasses(array $classes): static
    {
        ExtGtkWidget::setCssClasses($this->handle, $classes);

        return $this;
    }

    public function setCursor(int $cursor): static
    {
        ExtGtkWidget::setCursor($this->handle, $cursor);

        return $this;
    }

    public function setCursorFromName(mixed $name): static
    {
        ExtGtkWidget::setCursorFromName($this->handle, $name);

        return $this;
    }

    public function setDirection(GtkTextDirection|int $dir): static
    {
        ExtGtkWidget::setDirection($this->handle, ($dir instanceof GtkTextDirection ? $dir->value : $dir));

        return $this;
    }

    public function setFocusChild(?GtkWidget $child): static
    {
        ExtGtkWidget::setFocusChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setFocusOnClick(bool $focusOnClick): static
    {
        ExtGtkWidget::setFocusOnClick($this->handle, $focusOnClick);

        return $this;
    }

    public function setFocusable(bool $focusable): static
    {
        ExtGtkWidget::setFocusable($this->handle, $focusable);

        return $this;
    }

    public function setFontMap(int $fontMap): static
    {
        ExtGtkWidget::setFontMap($this->handle, $fontMap);

        return $this;
    }

    public function setHalign(GtkAlign|int $align): static
    {
        ExtGtkWidget::setHalign($this->handle, ($align instanceof GtkAlign ? $align->value : $align));

        return $this;
    }

    public function setHasTooltip(bool $hasTooltip): static
    {
        ExtGtkWidget::setHasTooltip($this->handle, $hasTooltip);

        return $this;
    }

    public function setHexpand(bool $expand): static
    {
        ExtGtkWidget::setHexpand($this->handle, $expand);

        return $this;
    }

    public function setHexpandSet(bool $set): static
    {
        ExtGtkWidget::setHexpandSet($this->handle, $set);

        return $this;
    }

    public function setLayoutManager(int $layoutManager): static
    {
        ExtGtkWidget::setLayoutManager($this->handle, $layoutManager);

        return $this;
    }

    public function setLimitEvents(bool $limitEvents): static
    {
        ExtGtkWidget::setLimitEvents($this->handle, $limitEvents);

        return $this;
    }

    public function setMarginBottom(int $margin): static
    {
        ExtGtkWidget::setMarginBottom($this->handle, $margin);

        return $this;
    }

    public function setMarginEnd(int $margin): static
    {
        ExtGtkWidget::setMarginEnd($this->handle, $margin);

        return $this;
    }

    public function setMarginStart(int $margin): static
    {
        ExtGtkWidget::setMarginStart($this->handle, $margin);

        return $this;
    }

    public function setMarginTop(int $margin): static
    {
        ExtGtkWidget::setMarginTop($this->handle, $margin);

        return $this;
    }

    public function setName(string $name): static
    {
        ExtGtkWidget::setName($this->handle, $name);

        return $this;
    }

    public function setOpacity(float $opacity): static
    {
        ExtGtkWidget::setOpacity($this->handle, $opacity);

        return $this;
    }

    public function setOverflow(GtkOverflow|int $overflow): static
    {
        ExtGtkWidget::setOverflow($this->handle, ($overflow instanceof GtkOverflow ? $overflow->value : $overflow));

        return $this;
    }

    public function setParent(GtkWidget $parent): static
    {
        ExtGtkWidget::setParent($this->handle, $parent->handle);

        return $this;
    }

    public function setReceivesDefault(bool $receivesDefault): static
    {
        ExtGtkWidget::setReceivesDefault($this->handle, $receivesDefault);

        return $this;
    }

    public function setSensitive(bool $sensitive): static
    {
        ExtGtkWidget::setSensitive($this->handle, $sensitive);

        return $this;
    }

    public function setSizeRequest(int $width, int $height): static
    {
        ExtGtkWidget::setSizeRequest($this->handle, $width, $height);

        return $this;
    }

    public function setStateFlags(int $flags, bool $clear): static
    {
        ExtGtkWidget::setStateFlags($this->handle, $flags, $clear);

        return $this;
    }

    public function setTooltipMarkup(mixed $markup): static
    {
        ExtGtkWidget::setTooltipMarkup($this->handle, $markup);

        return $this;
    }

    public function setTooltipText(mixed $text): static
    {
        ExtGtkWidget::setTooltipText($this->handle, $text);

        return $this;
    }

    public function setValign(GtkAlign|int $align): static
    {
        ExtGtkWidget::setValign($this->handle, ($align instanceof GtkAlign ? $align->value : $align));

        return $this;
    }

    public function setVexpand(bool $expand): static
    {
        ExtGtkWidget::setVexpand($this->handle, $expand);

        return $this;
    }

    public function setVexpandSet(bool $set): static
    {
        ExtGtkWidget::setVexpandSet($this->handle, $set);

        return $this;
    }

    public function setVisible(bool $visible): static
    {
        ExtGtkWidget::setVisible($this->handle, $visible);

        return $this;
    }

    public function shouldLayout(): bool
    {
        return ExtGtkWidget::shouldLayout($this->handle);
    }

    public function sizeAllocate(int $allocationX, int $allocationY, int $allocationWidth, int $allocationHeight, int $baseline): static
    {
        ExtGtkWidget::sizeAllocate($this->handle, $allocationX, $allocationY, $allocationWidth, $allocationHeight, $baseline);

        return $this;
    }

    public function snapshotChild(GtkWidget $child, int $snapshot): static
    {
        ExtGtkWidget::snapshotChild($this->handle, $child->handle, $snapshot);

        return $this;
    }

    public function triggerTooltipQuery(): static
    {
        ExtGtkWidget::triggerTooltipQuery($this->handle);

        return $this;
    }

    public function unmap(): static
    {
        ExtGtkWidget::unmap($this->handle);

        return $this;
    }

    public function unparent(): static
    {
        ExtGtkWidget::unparent($this->handle);

        return $this;
    }

    public function unrealize(): static
    {
        ExtGtkWidget::unrealize($this->handle);

        return $this;
    }

    public function unsetStateFlags(int $flags): static
    {
        ExtGtkWidget::unsetStateFlags($this->handle, $flags);

        return $this;
    }

    public function onDestroy(callable $callback): int
    {
        return Bridge::connect($this->handle, 'destroy', $callback);
    }

    public function onDirectionChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'direction-changed', $callback);
    }

    public function onHide(callable $callback): int
    {
        return Bridge::connect($this->handle, 'hide', $callback);
    }

    public function onKeynavFailed(callable $callback): int
    {
        return Bridge::connect($this->handle, 'keynav-failed', $callback);
    }

    public function onMap(callable $callback): int
    {
        return Bridge::connect($this->handle, 'map', $callback);
    }

    public function onMnemonicActivate(callable $callback): int
    {
        return Bridge::connect($this->handle, 'mnemonic-activate', $callback);
    }

    public function onMoveFocus(callable $callback): int
    {
        return Bridge::connect($this->handle, 'move-focus', $callback);
    }

    public function onQueryTooltip(callable $callback): int
    {
        return Bridge::connect($this->handle, 'query-tooltip', $callback);
    }

    public function onRealize(callable $callback): int
    {
        return Bridge::connect($this->handle, 'realize', $callback);
    }

    public function onShow(callable $callback): int
    {
        return Bridge::connect($this->handle, 'show', $callback);
    }

    public function onStateFlagsChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'state-flags-changed', $callback);
    }

    public function onUnmap(callable $callback): int
    {
        return Bridge::connect($this->handle, 'unmap', $callback);
    }

    public function onUnrealize(callable $callback): int
    {
        return Bridge::connect($this->handle, 'unrealize', $callback);
    }
}
