<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Gtk;

use Gtk\Gtk\GtkWindow\GtkWindow as ExtGtkWindow;
use Jovian\Bindings\Gtk\Runtime\Bridge;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

class GtkWindow extends GtkWidget
{
    public static function new(): self
    {
        return new self(ExtGtkWindow::new_());
    }

    public static function getDefaultIconName(): ?string
    {
        return ExtGtkWindow::getDefaultIconName();
    }

    public static function getToplevels(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getToplevels());
    }

    public static function listToplevels(): array
    {
        return ExtGtkWindow::listToplevels();
    }

    public static function setAutoStartupNotification(bool $setting): void
    {
        ExtGtkWindow::setAutoStartupNotification($setting);
    }

    public static function setDefaultIconName(string $name): void
    {
        ExtGtkWindow::setDefaultIconName($name);
    }

    public static function setInteractiveDebugging(bool $enable): void
    {
        ExtGtkWindow::setInteractiveDebugging($enable);
    }

    public function close(): static
    {
        ExtGtkWindow::close($this->handle);

        return $this;
    }

    public function destroy(): static
    {
        ExtGtkWindow::destroy($this->handle);

        return $this;
    }

    public function fullscreen(): static
    {
        ExtGtkWindow::fullscreen($this->handle);

        return $this;
    }

    public function fullscreenOnMonitor(int $monitor): static
    {
        ExtGtkWindow::fullscreenOnMonitor($this->handle, $monitor);

        return $this;
    }

    public function getApplication(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getApplication($this->handle));
    }

    public function getChild(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getChild($this->handle));
    }

    public function getDecorated(): bool
    {
        return ExtGtkWindow::getDecorated($this->handle);
    }

    /**
     * @return array{width: mixed, height: mixed}
     */
    public function getDefaultSize(): array
    {
        return ExtGtkWindow::getDefaultSize($this->handle);
    }

    public function getDefaultWidget(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getDefaultWidget($this->handle));
    }

    public function getDeletable(): bool
    {
        return ExtGtkWindow::getDeletable($this->handle);
    }

    public function getDestroyWithParent(): bool
    {
        return ExtGtkWindow::getDestroyWithParent($this->handle);
    }

    public function getFocus(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getFocus($this->handle));
    }

    public function getFocusVisible(): bool
    {
        return ExtGtkWindow::getFocusVisible($this->handle);
    }

    public function getGroup(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getGroup($this->handle));
    }

    public function getHandleMenubarAccel(): bool
    {
        return ExtGtkWindow::getHandleMenubarAccel($this->handle);
    }

    public function getHideOnClose(): bool
    {
        return ExtGtkWindow::getHideOnClose($this->handle);
    }

    public function getIconName(): ?string
    {
        return ExtGtkWindow::getIconName($this->handle);
    }

    public function getMnemonicsVisible(): bool
    {
        return ExtGtkWindow::getMnemonicsVisible($this->handle);
    }

    public function getModal(): bool
    {
        return ExtGtkWindow::getModal($this->handle);
    }

    public function getResizable(): bool
    {
        return ExtGtkWindow::getResizable($this->handle);
    }

    public function getTitle(): ?string
    {
        return ExtGtkWindow::getTitle($this->handle);
    }

    public function getTitlebar(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getTitlebar($this->handle));
    }

    public function getTransientFor(): ?GObject
    {
        return Registry::box(ExtGtkWindow::getTransientFor($this->handle));
    }

    public function hasGroup(): bool
    {
        return ExtGtkWindow::hasGroup($this->handle);
    }

    public function isActive(): bool
    {
        return ExtGtkWindow::isActive($this->handle);
    }

    public function isFullscreen(): bool
    {
        return ExtGtkWindow::isFullscreen($this->handle);
    }

    public function isMaximized(): bool
    {
        return ExtGtkWindow::isMaximized($this->handle);
    }

    public function isSuspended(): bool
    {
        return ExtGtkWindow::isSuspended($this->handle);
    }

    public function maximize(): static
    {
        ExtGtkWindow::maximize($this->handle);

        return $this;
    }

    public function minimize(): static
    {
        ExtGtkWindow::minimize($this->handle);

        return $this;
    }

    public function present(): static
    {
        ExtGtkWindow::present($this->handle);

        return $this;
    }

    public function setApplication(?GtkApplication $application): static
    {
        ExtGtkWindow::setApplication($this->handle, (is_null($application) ? 0 : $application->handle));

        return $this;
    }

    public function setChild(?GtkWidget $child): static
    {
        ExtGtkWindow::setChild($this->handle, (is_null($child) ? 0 : $child->handle));

        return $this;
    }

    public function setDecorated(bool $setting): static
    {
        ExtGtkWindow::setDecorated($this->handle, $setting);

        return $this;
    }

    public function setDefaultSize(int $width, int $height): static
    {
        ExtGtkWindow::setDefaultSize($this->handle, $width, $height);

        return $this;
    }

    public function setDefaultWidget(?GtkWidget $defaultWidget): static
    {
        ExtGtkWindow::setDefaultWidget($this->handle, (is_null($defaultWidget) ? 0 : $defaultWidget->handle));

        return $this;
    }

    public function setDeletable(bool $setting): static
    {
        ExtGtkWindow::setDeletable($this->handle, $setting);

        return $this;
    }

    public function setDestroyWithParent(bool $setting): static
    {
        ExtGtkWindow::setDestroyWithParent($this->handle, $setting);

        return $this;
    }

    public function setDisplay(int $display): static
    {
        ExtGtkWindow::setDisplay($this->handle, $display);

        return $this;
    }

    public function setFocus(?GtkWidget $focus): static
    {
        ExtGtkWindow::setFocus($this->handle, (is_null($focus) ? 0 : $focus->handle));

        return $this;
    }

    public function setFocusVisible(bool $setting): static
    {
        ExtGtkWindow::setFocusVisible($this->handle, $setting);

        return $this;
    }

    public function setHandleMenubarAccel(bool $handleMenubarAccel): static
    {
        ExtGtkWindow::setHandleMenubarAccel($this->handle, $handleMenubarAccel);

        return $this;
    }

    public function setHideOnClose(bool $setting): static
    {
        ExtGtkWindow::setHideOnClose($this->handle, $setting);

        return $this;
    }

    public function setIconName(mixed $name): static
    {
        ExtGtkWindow::setIconName($this->handle, $name);

        return $this;
    }

    public function setMnemonicsVisible(bool $setting): static
    {
        ExtGtkWindow::setMnemonicsVisible($this->handle, $setting);

        return $this;
    }

    public function setModal(bool $modal): static
    {
        ExtGtkWindow::setModal($this->handle, $modal);

        return $this;
    }

    public function setResizable(bool $resizable): static
    {
        ExtGtkWindow::setResizable($this->handle, $resizable);

        return $this;
    }

    public function setStartupId(string $startupId): static
    {
        ExtGtkWindow::setStartupId($this->handle, $startupId);

        return $this;
    }

    public function setTitle(mixed $title): static
    {
        ExtGtkWindow::setTitle($this->handle, $title);

        return $this;
    }

    public function setTitlebar(?GtkWidget $titlebar): static
    {
        ExtGtkWindow::setTitlebar($this->handle, (is_null($titlebar) ? 0 : $titlebar->handle));

        return $this;
    }

    public function setTransientFor(?GtkWindow $parent): static
    {
        ExtGtkWindow::setTransientFor($this->handle, (is_null($parent) ? 0 : $parent->handle));

        return $this;
    }

    public function unfullscreen(): static
    {
        ExtGtkWindow::unfullscreen($this->handle);

        return $this;
    }

    public function unmaximize(): static
    {
        ExtGtkWindow::unmaximize($this->handle);

        return $this;
    }

    public function unminimize(): static
    {
        ExtGtkWindow::unminimize($this->handle);

        return $this;
    }

    public function onActivateDefault(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-default', $callback);
    }

    public function onActivateFocus(callable $callback): int
    {
        return Bridge::connect($this->handle, 'activate-focus', $callback);
    }

    public function onCloseRequest(callable $callback): int
    {
        return Bridge::connect($this->handle, 'close-request', $callback);
    }

    public function onEnableDebugging(callable $callback): int
    {
        return Bridge::connect($this->handle, 'enable-debugging', $callback);
    }

    public function onKeysChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'keys-changed', $callback);
    }
}
