<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GAction\GAction as ExtGAction;

function g_action_name_is_valid(string $actionName): bool
{
    return ExtGAction::nameIsValid($actionName);
}

function g_action_get_enabled(int $handle): bool
{
    return ExtGAction::getEnabled($handle);
}

function g_action_get_name(int $handle): mixed
{
    return ExtGAction::getName($handle);
}
