<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GActionMap\GActionMap as ExtGActionMap;

function g_action_map_add_action(int $handle, int $action): void
{
    ExtGActionMap::addAction($handle, $action);
}

function g_action_map_lookup_action(int $handle, string $actionName): int
{
    return ExtGActionMap::lookupAction($handle, $actionName);
}

function g_action_map_remove_action(int $handle, string $actionName): void
{
    ExtGActionMap::removeAction($handle, $actionName);
}
