<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GApplication\GApplication as ExtGApplication;

function g_application_new(mixed $applicationId, int $flags): int
{
    return ExtGApplication::new_($applicationId, $flags);
}

function g_application_get_default(): int
{
    return ExtGApplication::getDefault();
}

function g_application_id_is_valid(string $applicationId): bool
{
    return ExtGApplication::idIsValid($applicationId);
}

function g_application_activate(int $handle): void
{
    ExtGApplication::activate($handle);
}

function g_application_add_main_option(int $handle, string $longName, int $shortName, int $flags, int $arg, string $description, mixed $argDescription): void
{
    ExtGApplication::addMainOption($handle, $longName, $shortName, $flags, $arg, $description, $argDescription);
}

function g_application_get_application_id(int $handle): mixed
{
    return ExtGApplication::getApplicationId($handle);
}

function g_application_get_dbus_connection(int $handle): int
{
    return ExtGApplication::getDbusConnection($handle);
}

function g_application_get_dbus_object_path(int $handle): mixed
{
    return ExtGApplication::getDbusObjectPath($handle);
}

function g_application_get_flags(int $handle): int
{
    return ExtGApplication::getFlags($handle);
}

function g_application_get_inactivity_timeout(int $handle): int
{
    return ExtGApplication::getInactivityTimeout($handle);
}

function g_application_get_is_busy(int $handle): bool
{
    return ExtGApplication::getIsBusy($handle);
}

function g_application_get_is_registered(int $handle): bool
{
    return ExtGApplication::getIsRegistered($handle);
}

function g_application_get_is_remote(int $handle): bool
{
    return ExtGApplication::getIsRemote($handle);
}

function g_application_get_resource_base_path(int $handle): mixed
{
    return ExtGApplication::getResourceBasePath($handle);
}

function g_application_get_version(int $handle): mixed
{
    return ExtGApplication::getVersion($handle);
}

function g_application_hold(int $handle): void
{
    ExtGApplication::hold($handle);
}

function g_application_mark_busy(int $handle): void
{
    ExtGApplication::markBusy($handle);
}

function g_application_open(int $handle, array $files, int $nFiles, string $hint): void
{
    ExtGApplication::open($handle, $files, $nFiles, $hint);
}

function g_application_quit(int $handle): void
{
    ExtGApplication::quit($handle);
}

function g_application_release(int $handle): void
{
    ExtGApplication::release($handle);
}

function g_application_run(int $handle, int $argc, array $argv): int
{
    return ExtGApplication::run($handle, $argc, $argv);
}

function g_application_send_notification(int $handle, mixed $id, int $notification): void
{
    ExtGApplication::sendNotification($handle, $id, $notification);
}

function g_application_set_application_id(int $handle, mixed $applicationId): void
{
    ExtGApplication::setApplicationId($handle, $applicationId);
}

function g_application_set_default(int $handle): void
{
    ExtGApplication::setDefault($handle);
}

function g_application_set_flags(int $handle, int $flags): void
{
    ExtGApplication::setFlags($handle, $flags);
}

function g_application_set_inactivity_timeout(int $handle, int $inactivityTimeout): void
{
    ExtGApplication::setInactivityTimeout($handle, $inactivityTimeout);
}

function g_application_set_option_context_description(int $handle, mixed $description): void
{
    ExtGApplication::setOptionContextDescription($handle, $description);
}

function g_application_set_option_context_parameter_string(int $handle, mixed $parameterString): void
{
    ExtGApplication::setOptionContextParameterString($handle, $parameterString);
}

function g_application_set_option_context_summary(int $handle, mixed $summary): void
{
    ExtGApplication::setOptionContextSummary($handle, $summary);
}

function g_application_set_resource_base_path(int $handle, mixed $resourcePath): void
{
    ExtGApplication::setResourceBasePath($handle, $resourcePath);
}

function g_application_set_version(int $handle, string $version): void
{
    ExtGApplication::setVersion($handle, $version);
}

function g_application_unmark_busy(int $handle): void
{
    ExtGApplication::unmarkBusy($handle);
}

function g_application_withdraw_notification(int $handle, string $id): void
{
    ExtGApplication::withdrawNotification($handle, $id);
}
