<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GListModel\GListModel as ExtGListModel;

function g_list_model_get_item(int $handle, int $position): int
{
    return ExtGListModel::getItem($handle, $position);
}

function g_list_model_get_item_type(int $handle): int
{
    return ExtGListModel::getItemType($handle);
}

function g_list_model_get_n_items(int $handle): int
{
    return ExtGListModel::getNItems($handle);
}

function g_list_model_get_object(int $handle, int $position): int
{
    return ExtGListModel::getObject($handle, $position);
}

function g_list_model_items_changed(int $handle, int $position, int $removed, int $added): void
{
    ExtGListModel::itemsChanged($handle, $position, $removed, $added);
}
