<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GListStore\GListStore as ExtGListStore;

function g_list_store_new(int $itemType): int
{
    return ExtGListStore::new_($itemType);
}

function g_list_store_append(int $handle, int $item): void
{
    ExtGListStore::append($handle, $item);
}

function g_list_store_find(int $handle, int $item): array
{
    return ExtGListStore::find($handle, $item);
}

function g_list_store_insert(int $handle, int $position, int $item): void
{
    ExtGListStore::insert($handle, $position, $item);
}

function g_list_store_remove(int $handle, int $position): void
{
    ExtGListStore::remove($handle, $position);
}

function g_list_store_remove_all(int $handle): void
{
    ExtGListStore::removeAll($handle);
}

function g_list_store_splice(int $handle, int $position, int $nRemovals, array $additions, int $nAdditions): void
{
    ExtGListStore::splice($handle, $position, $nRemovals, $additions, $nAdditions);
}
