<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GMenuItem\GMenuItem as ExtGMenuItem;

function g_menu_item_new(mixed $label, mixed $detailedAction): int
{
    return ExtGMenuItem::new_($label, $detailedAction);
}

function g_menu_item_new_from_model(int $model, int $itemIndex): int
{
    return ExtGMenuItem::newFromModel($model, $itemIndex);
}

function g_menu_item_new_section(mixed $label, int $section): int
{
    return ExtGMenuItem::newSection($label, $section);
}

function g_menu_item_new_submenu(mixed $label, int $submenu): int
{
    return ExtGMenuItem::newSubmenu($label, $submenu);
}

function g_menu_item_get_link(int $handle, string $link): int
{
    return ExtGMenuItem::getLink($handle, $link);
}

function g_menu_item_set_detailed_action(int $handle, string $detailedAction): void
{
    ExtGMenuItem::setDetailedAction($handle, $detailedAction);
}

function g_menu_item_set_icon(int $handle, int $icon): void
{
    ExtGMenuItem::setIcon($handle, $icon);
}

function g_menu_item_set_label(int $handle, mixed $label): void
{
    ExtGMenuItem::setLabel($handle, $label);
}

function g_menu_item_set_link(int $handle, string $link, int $model): void
{
    ExtGMenuItem::setLink($handle, $link, $model);
}

function g_menu_item_set_section(int $handle, int $section): void
{
    ExtGMenuItem::setSection($handle, $section);
}

function g_menu_item_set_submenu(int $handle, int $submenu): void
{
    ExtGMenuItem::setSubmenu($handle, $submenu);
}
