<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GMenu\GMenu as ExtGMenu;

function g_menu_new(): int
{
    return ExtGMenu::new_();
}

function g_menu_append(int $handle, mixed $label, mixed $detailedAction): void
{
    ExtGMenu::append($handle, $label, $detailedAction);
}

function g_menu_append_item(int $handle, int $item): void
{
    ExtGMenu::appendItem($handle, $item);
}

function g_menu_append_section(int $handle, mixed $label, int $section): void
{
    ExtGMenu::appendSection($handle, $label, $section);
}

function g_menu_append_submenu(int $handle, mixed $label, int $submenu): void
{
    ExtGMenu::appendSubmenu($handle, $label, $submenu);
}

function g_menu_freeze(int $handle): void
{
    ExtGMenu::freeze($handle);
}

function g_menu_insert(int $handle, int $position, mixed $label, mixed $detailedAction): void
{
    ExtGMenu::insert($handle, $position, $label, $detailedAction);
}

function g_menu_insert_item(int $handle, int $position, int $item): void
{
    ExtGMenu::insertItem($handle, $position, $item);
}

function g_menu_insert_section(int $handle, int $position, mixed $label, int $section): void
{
    ExtGMenu::insertSection($handle, $position, $label, $section);
}

function g_menu_insert_submenu(int $handle, int $position, mixed $label, int $submenu): void
{
    ExtGMenu::insertSubmenu($handle, $position, $label, $submenu);
}

function g_menu_prepend(int $handle, mixed $label, mixed $detailedAction): void
{
    ExtGMenu::prepend($handle, $label, $detailedAction);
}

function g_menu_prepend_item(int $handle, int $item): void
{
    ExtGMenu::prependItem($handle, $item);
}

function g_menu_prepend_section(int $handle, mixed $label, int $section): void
{
    ExtGMenu::prependSection($handle, $label, $section);
}

function g_menu_prepend_submenu(int $handle, mixed $label, int $submenu): void
{
    ExtGMenu::prependSubmenu($handle, $label, $submenu);
}

function g_menu_remove(int $handle, int $position): void
{
    ExtGMenu::remove($handle, $position);
}

function g_menu_remove_all(int $handle): void
{
    ExtGMenu::removeAll($handle);
}
