<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GSimpleAction\GSimpleAction as ExtGSimpleAction;

function g_simple_action_new(string $name): int
{
    return ExtGSimpleAction::new_($name);
}

function g_simple_action_set_enabled(int $handle, bool $enabled): void
{
    ExtGSimpleAction::setEnabled($handle, $enabled);
}
