<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gio\GSimpleActionGroup\GSimpleActionGroup as ExtGSimpleActionGroup;

function g_simple_action_group_new(): int
{
    return ExtGSimpleActionGroup::new_();
}
