<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gdk\GdkGLContext\GdkGLContext as ExtGdkGLContext;

function gdk_gl_context_get_allowed_apis(int $handle): int
{
    return ExtGdkGLContext::getAllowedApis($handle);
}

function gdk_gl_context_get_api(int $handle): int
{
    return ExtGdkGLContext::getApi($handle);
}

function gdk_gl_context_get_debug_enabled(int $handle): bool
{
    return ExtGdkGLContext::getDebugEnabled($handle);
}

function gdk_gl_context_get_display(int $handle): int
{
    return ExtGdkGLContext::getDisplay($handle);
}

function gdk_gl_context_get_forward_compatible(int $handle): bool
{
    return ExtGdkGLContext::getForwardCompatible($handle);
}

function gdk_gl_context_get_required_version(int $handle): array
{
    return ExtGdkGLContext::getRequiredVersion($handle);
}

function gdk_gl_context_get_surface(int $handle): int
{
    return ExtGdkGLContext::getSurface($handle);
}

function gdk_gl_context_get_use_es(int $handle): bool
{
    return ExtGdkGLContext::getUseEs($handle);
}

function gdk_gl_context_get_version(int $handle): array
{
    return ExtGdkGLContext::getVersion($handle);
}

function gdk_gl_context_is_legacy(int $handle): bool
{
    return ExtGdkGLContext::isLegacy($handle);
}

function gdk_gl_context_is_shared(int $handle, int $other): bool
{
    return ExtGdkGLContext::isShared($handle, $other);
}

function gdk_gl_context_make_current(int $handle): void
{
    ExtGdkGLContext::makeCurrent($handle);
}

function gdk_gl_context_set_allowed_apis(int $handle, int $apis): void
{
    ExtGdkGLContext::setAllowedApis($handle, $apis);
}

function gdk_gl_context_set_debug_enabled(int $handle, bool $enabled): void
{
    ExtGdkGLContext::setDebugEnabled($handle, $enabled);
}

function gdk_gl_context_set_forward_compatible(int $handle, bool $compatible): void
{
    ExtGdkGLContext::setForwardCompatible($handle, $compatible);
}

function gdk_gl_context_set_required_version(int $handle, int $major, int $minor): void
{
    ExtGdkGLContext::setRequiredVersion($handle, $major, $minor);
}

function gdk_gl_context_set_use_es(int $handle, int $useEs): void
{
    ExtGdkGLContext::setUseEs($handle, $useEs);
}

function gdk_gl_context_clear_current(): void
{
    ExtGdkGLContext::clearCurrent();
}

function gdk_gl_context_get_current(): int
{
    return ExtGdkGLContext::getCurrent();
}
