<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkStackPage\GtkStackPage as ExtGtkStackPage;

function gtk_stack_page_get_child(int $handle): int
{
    return ExtGtkStackPage::getChild($handle);
}

function gtk_stack_page_get_icon_name(int $handle): mixed
{
    return ExtGtkStackPage::getIconName($handle);
}

function gtk_stack_page_get_name(int $handle): mixed
{
    return ExtGtkStackPage::getName($handle);
}

function gtk_stack_page_get_needs_attention(int $handle): bool
{
    return ExtGtkStackPage::getNeedsAttention($handle);
}

function gtk_stack_page_get_title(int $handle): mixed
{
    return ExtGtkStackPage::getTitle($handle);
}

function gtk_stack_page_get_use_underline(int $handle): bool
{
    return ExtGtkStackPage::getUseUnderline($handle);
}

function gtk_stack_page_get_visible(int $handle): bool
{
    return ExtGtkStackPage::getVisible($handle);
}

function gtk_stack_page_set_icon_name(int $handle, string $setting): void
{
    ExtGtkStackPage::setIconName($handle, $setting);
}

function gtk_stack_page_set_name(int $handle, string $setting): void
{
    ExtGtkStackPage::setName($handle, $setting);
}

function gtk_stack_page_set_needs_attention(int $handle, bool $setting): void
{
    ExtGtkStackPage::setNeedsAttention($handle, $setting);
}

function gtk_stack_page_set_title(int $handle, string $setting): void
{
    ExtGtkStackPage::setTitle($handle, $setting);
}

function gtk_stack_page_set_use_underline(int $handle, bool $setting): void
{
    ExtGtkStackPage::setUseUnderline($handle, $setting);
}

function gtk_stack_page_set_visible(int $handle, bool $visible): void
{
    ExtGtkStackPage::setVisible($handle, $visible);
}
