<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkListBoxRow\GtkListBoxRow as ExtGtkListBoxRow;

function gtk_list_box_row_new(): int
{
    return ExtGtkListBoxRow::new_();
}

function gtk_list_box_row_changed(int $handle): void
{
    ExtGtkListBoxRow::changed($handle);
}

function gtk_list_box_row_get_activatable(int $handle): bool
{
    return ExtGtkListBoxRow::getActivatable($handle);
}

function gtk_list_box_row_get_child(int $handle): int
{
    return ExtGtkListBoxRow::getChild($handle);
}

function gtk_list_box_row_get_header(int $handle): int
{
    return ExtGtkListBoxRow::getHeader($handle);
}

function gtk_list_box_row_get_index(int $handle): int
{
    return ExtGtkListBoxRow::getIndex($handle);
}

function gtk_list_box_row_get_selectable(int $handle): bool
{
    return ExtGtkListBoxRow::getSelectable($handle);
}

function gtk_list_box_row_is_selected(int $handle): bool
{
    return ExtGtkListBoxRow::isSelected($handle);
}

function gtk_list_box_row_set_activatable(int $handle, bool $activatable): void
{
    ExtGtkListBoxRow::setActivatable($handle, $activatable);
}

function gtk_list_box_row_set_child(int $handle, int $child): void
{
    ExtGtkListBoxRow::setChild($handle, $child);
}

function gtk_list_box_row_set_header(int $handle, int $header): void
{
    ExtGtkListBoxRow::setHeader($handle, $header);
}

function gtk_list_box_row_set_selectable(int $handle, bool $selectable): void
{
    ExtGtkListBoxRow::setSelectable($handle, $selectable);
}
