<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkOrientable\GtkOrientable as ExtGtkOrientable;

function gtk_orientable_get_orientation(int $handle): int
{
    return ExtGtkOrientable::getOrientation($handle);
}

function gtk_orientable_set_orientation(int $handle, int $orientation): void
{
    ExtGtkOrientable::setOrientation($handle, $orientation);
}
