<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkTextTagTable\GtkTextTagTable as ExtGtkTextTagTable;

function gtk_text_tag_table_new(): int
{
    return ExtGtkTextTagTable::new_();
}

function gtk_text_tag_table_add(int $handle, int $tag): bool
{
    return ExtGtkTextTagTable::add($handle, $tag);
}

function gtk_text_tag_table_get_size(int $handle): int
{
    return ExtGtkTextTagTable::getSize($handle);
}

function gtk_text_tag_table_lookup(int $handle, string $name): int
{
    return ExtGtkTextTagTable::lookup($handle, $name);
}

function gtk_text_tag_table_remove(int $handle, int $tag): void
{
    ExtGtkTextTagTable::remove($handle, $tag);
}
