<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkButton\GtkButton as ExtGtkButton;

function gtk_button_new(): int
{
    return ExtGtkButton::new_();
}

function gtk_button_new_from_icon_name(string $iconName): int
{
    return ExtGtkButton::newFromIconName($iconName);
}

function gtk_button_new_with_label(string $label): int
{
    return ExtGtkButton::newWithLabel($label);
}

function gtk_button_new_with_mnemonic(string $label): int
{
    return ExtGtkButton::newWithMnemonic($label);
}

function gtk_button_get_can_shrink(int $handle): bool
{
    return ExtGtkButton::getCanShrink($handle);
}

function gtk_button_get_child(int $handle): int
{
    return ExtGtkButton::getChild($handle);
}

function gtk_button_get_has_frame(int $handle): bool
{
    return ExtGtkButton::getHasFrame($handle);
}

function gtk_button_get_icon_name(int $handle): mixed
{
    return ExtGtkButton::getIconName($handle);
}

function gtk_button_get_label(int $handle): mixed
{
    return ExtGtkButton::getLabel($handle);
}

function gtk_button_get_use_underline(int $handle): bool
{
    return ExtGtkButton::getUseUnderline($handle);
}

function gtk_button_set_can_shrink(int $handle, bool $canShrink): void
{
    ExtGtkButton::setCanShrink($handle, $canShrink);
}

function gtk_button_set_child(int $handle, int $child): void
{
    ExtGtkButton::setChild($handle, $child);
}

function gtk_button_set_has_frame(int $handle, bool $hasFrame): void
{
    ExtGtkButton::setHasFrame($handle, $hasFrame);
}

function gtk_button_set_icon_name(int $handle, string $iconName): void
{
    ExtGtkButton::setIconName($handle, $iconName);
}

function gtk_button_set_label(int $handle, string $label): void
{
    ExtGtkButton::setLabel($handle, $label);
}

function gtk_button_set_use_underline(int $handle, bool $useUnderline): void
{
    ExtGtkButton::setUseUnderline($handle, $useUnderline);
}
