<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkSwitch\GtkSwitch as ExtGtkSwitch;

function gtk_switch_new(): int
{
    return ExtGtkSwitch::new_();
}

function gtk_switch_get_active(int $handle): bool
{
    return ExtGtkSwitch::getActive($handle);
}

function gtk_switch_get_state(int $handle): bool
{
    return ExtGtkSwitch::getState($handle);
}

function gtk_switch_set_active(int $handle, bool $isActive): void
{
    ExtGtkSwitch::setActive($handle, $isActive);
}

function gtk_switch_set_state(int $handle, bool $state): void
{
    ExtGtkSwitch::setState($handle, $state);
}
