<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkStack\GtkStack as ExtGtkStack;

function gtk_stack_new(): int
{
    return ExtGtkStack::new_();
}

function gtk_stack_add_child(int $handle, int $child): int
{
    return ExtGtkStack::addChild($handle, $child);
}

function gtk_stack_add_named(int $handle, int $child, mixed $name): int
{
    return ExtGtkStack::addNamed($handle, $child, $name);
}

function gtk_stack_add_titled(int $handle, int $child, mixed $name, string $title): int
{
    return ExtGtkStack::addTitled($handle, $child, $name, $title);
}

function gtk_stack_get_child_by_name(int $handle, string $name): int
{
    return ExtGtkStack::getChildByName($handle, $name);
}

function gtk_stack_get_hhomogeneous(int $handle): bool
{
    return ExtGtkStack::getHhomogeneous($handle);
}

function gtk_stack_get_interpolate_size(int $handle): bool
{
    return ExtGtkStack::getInterpolateSize($handle);
}

function gtk_stack_get_page(int $handle, int $child): int
{
    return ExtGtkStack::getPage($handle, $child);
}

function gtk_stack_get_pages(int $handle): int
{
    return ExtGtkStack::getPages($handle);
}

function gtk_stack_get_transition_duration(int $handle): int
{
    return ExtGtkStack::getTransitionDuration($handle);
}

function gtk_stack_get_transition_running(int $handle): bool
{
    return ExtGtkStack::getTransitionRunning($handle);
}

function gtk_stack_get_transition_type(int $handle): int
{
    return ExtGtkStack::getTransitionType($handle);
}

function gtk_stack_get_vhomogeneous(int $handle): bool
{
    return ExtGtkStack::getVhomogeneous($handle);
}

function gtk_stack_get_visible_child(int $handle): int
{
    return ExtGtkStack::getVisibleChild($handle);
}

function gtk_stack_get_visible_child_name(int $handle): mixed
{
    return ExtGtkStack::getVisibleChildName($handle);
}

function gtk_stack_remove(int $handle, int $child): void
{
    ExtGtkStack::remove($handle, $child);
}

function gtk_stack_set_hhomogeneous(int $handle, bool $hhomogeneous): void
{
    ExtGtkStack::setHhomogeneous($handle, $hhomogeneous);
}

function gtk_stack_set_interpolate_size(int $handle, bool $interpolateSize): void
{
    ExtGtkStack::setInterpolateSize($handle, $interpolateSize);
}

function gtk_stack_set_transition_duration(int $handle, int $duration): void
{
    ExtGtkStack::setTransitionDuration($handle, $duration);
}

function gtk_stack_set_transition_type(int $handle, int $transition): void
{
    ExtGtkStack::setTransitionType($handle, $transition);
}

function gtk_stack_set_vhomogeneous(int $handle, bool $vhomogeneous): void
{
    ExtGtkStack::setVhomogeneous($handle, $vhomogeneous);
}

function gtk_stack_set_visible_child(int $handle, int $child): void
{
    ExtGtkStack::setVisibleChild($handle, $child);
}

function gtk_stack_set_visible_child_full(int $handle, string $name, int $transition): void
{
    ExtGtkStack::setVisibleChildFull($handle, $name, $transition);
}

function gtk_stack_set_visible_child_name(int $handle, string $name): void
{
    ExtGtkStack::setVisibleChildName($handle, $name);
}
