<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkGLArea\GtkGLArea as ExtGtkGLArea;

function gtk_gl_area_new(): int
{
    return ExtGtkGLArea::new_();
}

function gtk_gl_area_attach_buffers(int $handle): void
{
    ExtGtkGLArea::attachBuffers($handle);
}

function gtk_gl_area_get_allowed_apis(int $handle): int
{
    return ExtGtkGLArea::getAllowedApis($handle);
}

function gtk_gl_area_get_api(int $handle): int
{
    return ExtGtkGLArea::getApi($handle);
}

function gtk_gl_area_get_auto_render(int $handle): bool
{
    return ExtGtkGLArea::getAutoRender($handle);
}

function gtk_gl_area_get_context(int $handle): int
{
    return ExtGtkGLArea::getContext($handle);
}

function gtk_gl_area_get_has_depth_buffer(int $handle): bool
{
    return ExtGtkGLArea::getHasDepthBuffer($handle);
}

function gtk_gl_area_get_has_stencil_buffer(int $handle): bool
{
    return ExtGtkGLArea::getHasStencilBuffer($handle);
}

function gtk_gl_area_get_required_version(int $handle): array
{
    return ExtGtkGLArea::getRequiredVersion($handle);
}

function gtk_gl_area_make_current(int $handle): void
{
    ExtGtkGLArea::makeCurrent($handle);
}

function gtk_gl_area_queue_render(int $handle): void
{
    ExtGtkGLArea::queueRender($handle);
}

function gtk_gl_area_set_allowed_apis(int $handle, int $apis): void
{
    ExtGtkGLArea::setAllowedApis($handle, $apis);
}

function gtk_gl_area_set_auto_render(int $handle, bool $autoRender): void
{
    ExtGtkGLArea::setAutoRender($handle, $autoRender);
}

function gtk_gl_area_set_has_depth_buffer(int $handle, bool $hasDepthBuffer): void
{
    ExtGtkGLArea::setHasDepthBuffer($handle, $hasDepthBuffer);
}

function gtk_gl_area_set_has_stencil_buffer(int $handle, bool $hasStencilBuffer): void
{
    ExtGtkGLArea::setHasStencilBuffer($handle, $hasStencilBuffer);
}

function gtk_gl_area_set_required_version(int $handle, int $major, int $minor): void
{
    ExtGtkGLArea::setRequiredVersion($handle, $major, $minor);
}
