<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkPopover\GtkPopover as ExtGtkPopover;

function gtk_popover_new(): int
{
    return ExtGtkPopover::new_();
}

function gtk_popover_get_autohide(int $handle): bool
{
    return ExtGtkPopover::getAutohide($handle);
}

function gtk_popover_get_cascade_popdown(int $handle): bool
{
    return ExtGtkPopover::getCascadePopdown($handle);
}

function gtk_popover_get_child(int $handle): int
{
    return ExtGtkPopover::getChild($handle);
}

function gtk_popover_get_has_arrow(int $handle): bool
{
    return ExtGtkPopover::getHasArrow($handle);
}

function gtk_popover_get_mnemonics_visible(int $handle): bool
{
    return ExtGtkPopover::getMnemonicsVisible($handle);
}

function gtk_popover_get_offset(int $handle): array
{
    return ExtGtkPopover::getOffset($handle);
}

function gtk_popover_get_pointing_to(int $handle): array
{
    return ExtGtkPopover::getPointingTo($handle);
}

function gtk_popover_get_position(int $handle): int
{
    return ExtGtkPopover::getPosition($handle);
}

function gtk_popover_popdown(int $handle): void
{
    ExtGtkPopover::popdown($handle);
}

function gtk_popover_popup(int $handle): void
{
    ExtGtkPopover::popup($handle);
}

function gtk_popover_present(int $handle): void
{
    ExtGtkPopover::present($handle);
}

function gtk_popover_set_autohide(int $handle, bool $autohide): void
{
    ExtGtkPopover::setAutohide($handle, $autohide);
}

function gtk_popover_set_cascade_popdown(int $handle, bool $cascadePopdown): void
{
    ExtGtkPopover::setCascadePopdown($handle, $cascadePopdown);
}

function gtk_popover_set_child(int $handle, int $child): void
{
    ExtGtkPopover::setChild($handle, $child);
}

function gtk_popover_set_default_widget(int $handle, int $widget): void
{
    ExtGtkPopover::setDefaultWidget($handle, $widget);
}

function gtk_popover_set_has_arrow(int $handle, bool $hasArrow): void
{
    ExtGtkPopover::setHasArrow($handle, $hasArrow);
}

function gtk_popover_set_mnemonics_visible(int $handle, bool $mnemonicsVisible): void
{
    ExtGtkPopover::setMnemonicsVisible($handle, $mnemonicsVisible);
}

function gtk_popover_set_offset(int $handle, int $xOffset, int $yOffset): void
{
    ExtGtkPopover::setOffset($handle, $xOffset, $yOffset);
}

function gtk_popover_set_pointing_to(int $handle, float $x, float $y, float $width, float $height): void
{
    ExtGtkPopover::setPointingTo($handle, $x, $y, $width, $height);
}

function gtk_popover_set_position(int $handle, int $position): void
{
    ExtGtkPopover::setPosition($handle, $position);
}
