<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkLevelBar\GtkLevelBar as ExtGtkLevelBar;

function gtk_level_bar_new(): int
{
    return ExtGtkLevelBar::new_();
}

function gtk_level_bar_new_for_interval(float $minValue, float $maxValue): int
{
    return ExtGtkLevelBar::newForInterval($minValue, $maxValue);
}

function gtk_level_bar_add_offset_value(int $handle, string $name, float $value): void
{
    ExtGtkLevelBar::addOffsetValue($handle, $name, $value);
}

function gtk_level_bar_get_inverted(int $handle): bool
{
    return ExtGtkLevelBar::getInverted($handle);
}

function gtk_level_bar_get_max_value(int $handle): float
{
    return ExtGtkLevelBar::getMaxValue($handle);
}

function gtk_level_bar_get_min_value(int $handle): float
{
    return ExtGtkLevelBar::getMinValue($handle);
}

function gtk_level_bar_get_mode(int $handle): int
{
    return ExtGtkLevelBar::getMode($handle);
}

function gtk_level_bar_get_offset_value(int $handle, mixed $name): array
{
    return ExtGtkLevelBar::getOffsetValue($handle, $name);
}

function gtk_level_bar_get_value(int $handle): float
{
    return ExtGtkLevelBar::getValue($handle);
}

function gtk_level_bar_remove_offset_value(int $handle, mixed $name): void
{
    ExtGtkLevelBar::removeOffsetValue($handle, $name);
}

function gtk_level_bar_set_inverted(int $handle, bool $inverted): void
{
    ExtGtkLevelBar::setInverted($handle, $inverted);
}

function gtk_level_bar_set_max_value(int $handle, float $value): void
{
    ExtGtkLevelBar::setMaxValue($handle, $value);
}

function gtk_level_bar_set_min_value(int $handle, float $value): void
{
    ExtGtkLevelBar::setMinValue($handle, $value);
}

function gtk_level_bar_set_mode(int $handle, int $mode): void
{
    ExtGtkLevelBar::setMode($handle, $mode);
}

function gtk_level_bar_set_value(int $handle, float $value): void
{
    ExtGtkLevelBar::setValue($handle, $value);
}
