<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkAspectFrame\GtkAspectFrame as ExtGtkAspectFrame;

function gtk_aspect_frame_new(float $xalign, float $yalign, float $ratio, bool $obeyChild): int
{
    return ExtGtkAspectFrame::new_($xalign, $yalign, $ratio, $obeyChild);
}

function gtk_aspect_frame_get_child(int $handle): int
{
    return ExtGtkAspectFrame::getChild($handle);
}

function gtk_aspect_frame_get_obey_child(int $handle): bool
{
    return ExtGtkAspectFrame::getObeyChild($handle);
}

function gtk_aspect_frame_get_ratio(int $handle): float
{
    return ExtGtkAspectFrame::getRatio($handle);
}

function gtk_aspect_frame_get_xalign(int $handle): float
{
    return ExtGtkAspectFrame::getXalign($handle);
}

function gtk_aspect_frame_get_yalign(int $handle): float
{
    return ExtGtkAspectFrame::getYalign($handle);
}

function gtk_aspect_frame_set_child(int $handle, int $child): void
{
    ExtGtkAspectFrame::setChild($handle, $child);
}

function gtk_aspect_frame_set_obey_child(int $handle, bool $obeyChild): void
{
    ExtGtkAspectFrame::setObeyChild($handle, $obeyChild);
}

function gtk_aspect_frame_set_ratio(int $handle, float $ratio): void
{
    ExtGtkAspectFrame::setRatio($handle, $ratio);
}

function gtk_aspect_frame_set_xalign(int $handle, float $xalign): void
{
    ExtGtkAspectFrame::setXalign($handle, $xalign);
}

function gtk_aspect_frame_set_yalign(int $handle, float $yalign): void
{
    ExtGtkAspectFrame::setYalign($handle, $yalign);
}
