<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkScrolledWindow\GtkScrolledWindow as ExtGtkScrolledWindow;

function gtk_scrolled_window_new(): int
{
    return ExtGtkScrolledWindow::new_();
}

function gtk_scrolled_window_get_child(int $handle): int
{
    return ExtGtkScrolledWindow::getChild($handle);
}

function gtk_scrolled_window_get_hadjustment(int $handle): int
{
    return ExtGtkScrolledWindow::getHadjustment($handle);
}

function gtk_scrolled_window_get_has_frame(int $handle): bool
{
    return ExtGtkScrolledWindow::getHasFrame($handle);
}

function gtk_scrolled_window_get_hscrollbar(int $handle): int
{
    return ExtGtkScrolledWindow::getHscrollbar($handle);
}

function gtk_scrolled_window_get_kinetic_scrolling(int $handle): bool
{
    return ExtGtkScrolledWindow::getKineticScrolling($handle);
}

function gtk_scrolled_window_get_max_content_height(int $handle): int
{
    return ExtGtkScrolledWindow::getMaxContentHeight($handle);
}

function gtk_scrolled_window_get_max_content_width(int $handle): int
{
    return ExtGtkScrolledWindow::getMaxContentWidth($handle);
}

function gtk_scrolled_window_get_min_content_height(int $handle): int
{
    return ExtGtkScrolledWindow::getMinContentHeight($handle);
}

function gtk_scrolled_window_get_min_content_width(int $handle): int
{
    return ExtGtkScrolledWindow::getMinContentWidth($handle);
}

function gtk_scrolled_window_get_overlay_scrolling(int $handle): bool
{
    return ExtGtkScrolledWindow::getOverlayScrolling($handle);
}

function gtk_scrolled_window_get_placement(int $handle): int
{
    return ExtGtkScrolledWindow::getPlacement($handle);
}

function gtk_scrolled_window_get_policy(int $handle): array
{
    return ExtGtkScrolledWindow::getPolicy($handle);
}

function gtk_scrolled_window_get_propagate_natural_height(int $handle): bool
{
    return ExtGtkScrolledWindow::getPropagateNaturalHeight($handle);
}

function gtk_scrolled_window_get_propagate_natural_width(int $handle): bool
{
    return ExtGtkScrolledWindow::getPropagateNaturalWidth($handle);
}

function gtk_scrolled_window_get_vadjustment(int $handle): int
{
    return ExtGtkScrolledWindow::getVadjustment($handle);
}

function gtk_scrolled_window_get_vscrollbar(int $handle): int
{
    return ExtGtkScrolledWindow::getVscrollbar($handle);
}

function gtk_scrolled_window_set_child(int $handle, int $child): void
{
    ExtGtkScrolledWindow::setChild($handle, $child);
}

function gtk_scrolled_window_set_hadjustment(int $handle, int $hadjustment): void
{
    ExtGtkScrolledWindow::setHadjustment($handle, $hadjustment);
}

function gtk_scrolled_window_set_has_frame(int $handle, bool $hasFrame): void
{
    ExtGtkScrolledWindow::setHasFrame($handle, $hasFrame);
}

function gtk_scrolled_window_set_kinetic_scrolling(int $handle, bool $kineticScrolling): void
{
    ExtGtkScrolledWindow::setKineticScrolling($handle, $kineticScrolling);
}

function gtk_scrolled_window_set_max_content_height(int $handle, int $height): void
{
    ExtGtkScrolledWindow::setMaxContentHeight($handle, $height);
}

function gtk_scrolled_window_set_max_content_width(int $handle, int $width): void
{
    ExtGtkScrolledWindow::setMaxContentWidth($handle, $width);
}

function gtk_scrolled_window_set_min_content_height(int $handle, int $height): void
{
    ExtGtkScrolledWindow::setMinContentHeight($handle, $height);
}

function gtk_scrolled_window_set_min_content_width(int $handle, int $width): void
{
    ExtGtkScrolledWindow::setMinContentWidth($handle, $width);
}

function gtk_scrolled_window_set_overlay_scrolling(int $handle, bool $overlayScrolling): void
{
    ExtGtkScrolledWindow::setOverlayScrolling($handle, $overlayScrolling);
}

function gtk_scrolled_window_set_placement(int $handle, int $windowPlacement): void
{
    ExtGtkScrolledWindow::setPlacement($handle, $windowPlacement);
}

function gtk_scrolled_window_set_policy(int $handle, int $hscrollbarPolicy, int $vscrollbarPolicy): void
{
    ExtGtkScrolledWindow::setPolicy($handle, $hscrollbarPolicy, $vscrollbarPolicy);
}

function gtk_scrolled_window_set_propagate_natural_height(int $handle, bool $propagate): void
{
    ExtGtkScrolledWindow::setPropagateNaturalHeight($handle, $propagate);
}

function gtk_scrolled_window_set_propagate_natural_width(int $handle, bool $propagate): void
{
    ExtGtkScrolledWindow::setPropagateNaturalWidth($handle, $propagate);
}

function gtk_scrolled_window_set_vadjustment(int $handle, int $vadjustment): void
{
    ExtGtkScrolledWindow::setVadjustment($handle, $vadjustment);
}

function gtk_scrolled_window_unset_placement(int $handle): void
{
    ExtGtkScrolledWindow::unsetPlacement($handle);
}
