<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkTextBuffer\GtkTextBuffer as ExtGtkTextBuffer;

function gtk_text_buffer_new(int $table): int
{
    return ExtGtkTextBuffer::new_($table);
}

function gtk_text_buffer_add_selection_clipboard(int $handle, int $clipboard): void
{
    ExtGtkTextBuffer::addSelectionClipboard($handle, $clipboard);
}

function gtk_text_buffer_begin_irreversible_action(int $handle): void
{
    ExtGtkTextBuffer::beginIrreversibleAction($handle);
}

function gtk_text_buffer_begin_user_action(int $handle): void
{
    ExtGtkTextBuffer::beginUserAction($handle);
}

function gtk_text_buffer_copy_clipboard(int $handle, int $clipboard): void
{
    ExtGtkTextBuffer::copyClipboard($handle, $clipboard);
}

function gtk_text_buffer_cut_clipboard(int $handle, int $clipboard, bool $defaultEditable): void
{
    ExtGtkTextBuffer::cutClipboard($handle, $clipboard, $defaultEditable);
}

function gtk_text_buffer_delete_mark(int $handle, int $mark): void
{
    ExtGtkTextBuffer::deleteMark($handle, $mark);
}

function gtk_text_buffer_delete_mark_by_name(int $handle, string $name): void
{
    ExtGtkTextBuffer::deleteMarkByName($handle, $name);
}

function gtk_text_buffer_delete_selection(int $handle, bool $interactive, bool $defaultEditable): bool
{
    return ExtGtkTextBuffer::deleteSelection($handle, $interactive, $defaultEditable);
}

function gtk_text_buffer_end_irreversible_action(int $handle): void
{
    ExtGtkTextBuffer::endIrreversibleAction($handle);
}

function gtk_text_buffer_end_user_action(int $handle): void
{
    ExtGtkTextBuffer::endUserAction($handle);
}

function gtk_text_buffer_get_can_redo(int $handle): bool
{
    return ExtGtkTextBuffer::getCanRedo($handle);
}

function gtk_text_buffer_get_can_undo(int $handle): bool
{
    return ExtGtkTextBuffer::getCanUndo($handle);
}

function gtk_text_buffer_get_char_count(int $handle): int
{
    return ExtGtkTextBuffer::getCharCount($handle);
}

function gtk_text_buffer_get_enable_undo(int $handle): bool
{
    return ExtGtkTextBuffer::getEnableUndo($handle);
}

function gtk_text_buffer_get_has_selection(int $handle): bool
{
    return ExtGtkTextBuffer::getHasSelection($handle);
}

function gtk_text_buffer_get_insert(int $handle): int
{
    return ExtGtkTextBuffer::getInsert($handle);
}

function gtk_text_buffer_get_line_count(int $handle): int
{
    return ExtGtkTextBuffer::getLineCount($handle);
}

function gtk_text_buffer_get_mark(int $handle, string $name): int
{
    return ExtGtkTextBuffer::getMark($handle, $name);
}

function gtk_text_buffer_get_max_undo_levels(int $handle): int
{
    return ExtGtkTextBuffer::getMaxUndoLevels($handle);
}

function gtk_text_buffer_get_modified(int $handle): bool
{
    return ExtGtkTextBuffer::getModified($handle);
}

function gtk_text_buffer_get_selection_bound(int $handle): int
{
    return ExtGtkTextBuffer::getSelectionBound($handle);
}

function gtk_text_buffer_get_tag_table(int $handle): int
{
    return ExtGtkTextBuffer::getTagTable($handle);
}

function gtk_text_buffer_get_text(int $handle, int $startOffset, int $endOffset, bool $includeHiddenChars): mixed
{
    return ExtGtkTextBuffer::getText($handle, $startOffset, $endOffset, $includeHiddenChars);
}

function gtk_text_buffer_insert_at_cursor(int $handle, string $text, int $len): void
{
    ExtGtkTextBuffer::insertAtCursor($handle, $text, $len);
}

function gtk_text_buffer_insert_interactive_at_cursor(int $handle, string $text, int $len, bool $defaultEditable): bool
{
    return ExtGtkTextBuffer::insertInteractiveAtCursor($handle, $text, $len, $defaultEditable);
}

function gtk_text_buffer_redo(int $handle): void
{
    ExtGtkTextBuffer::redo($handle);
}

function gtk_text_buffer_remove_commit_notify(int $handle, int $commitNotifyHandler): void
{
    ExtGtkTextBuffer::removeCommitNotify($handle, $commitNotifyHandler);
}

function gtk_text_buffer_remove_selection_clipboard(int $handle, int $clipboard): void
{
    ExtGtkTextBuffer::removeSelectionClipboard($handle, $clipboard);
}

function gtk_text_buffer_set_enable_undo(int $handle, bool $enableUndo): void
{
    ExtGtkTextBuffer::setEnableUndo($handle, $enableUndo);
}

function gtk_text_buffer_set_max_undo_levels(int $handle, int $maxUndoLevels): void
{
    ExtGtkTextBuffer::setMaxUndoLevels($handle, $maxUndoLevels);
}

function gtk_text_buffer_set_modified(int $handle, bool $setting): void
{
    ExtGtkTextBuffer::setModified($handle, $setting);
}

function gtk_text_buffer_set_text(int $handle, string $text, int $len): void
{
    ExtGtkTextBuffer::setText($handle, $text, $len);
}

function gtk_text_buffer_undo(int $handle): void
{
    ExtGtkTextBuffer::undo($handle);
}
