<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkListItem\GtkListItem as ExtGtkListItem;

function gtk_list_item_get_accessible_description(int $handle): string
{
    return ExtGtkListItem::getAccessibleDescription($handle);
}

function gtk_list_item_get_accessible_label(int $handle): string
{
    return ExtGtkListItem::getAccessibleLabel($handle);
}

function gtk_list_item_get_activatable(int $handle): bool
{
    return ExtGtkListItem::getActivatable($handle);
}

function gtk_list_item_get_child(int $handle): int
{
    return ExtGtkListItem::getChild($handle);
}

function gtk_list_item_get_focusable(int $handle): bool
{
    return ExtGtkListItem::getFocusable($handle);
}

function gtk_list_item_get_item(int $handle): int
{
    return ExtGtkListItem::getItem($handle);
}

function gtk_list_item_get_position(int $handle): int
{
    return ExtGtkListItem::getPosition($handle);
}

function gtk_list_item_get_selectable(int $handle): bool
{
    return ExtGtkListItem::getSelectable($handle);
}

function gtk_list_item_get_selected(int $handle): bool
{
    return ExtGtkListItem::getSelected($handle);
}

function gtk_list_item_set_accessible_description(int $handle, string $description): void
{
    ExtGtkListItem::setAccessibleDescription($handle, $description);
}

function gtk_list_item_set_accessible_label(int $handle, string $label): void
{
    ExtGtkListItem::setAccessibleLabel($handle, $label);
}

function gtk_list_item_set_activatable(int $handle, bool $activatable): void
{
    ExtGtkListItem::setActivatable($handle, $activatable);
}

function gtk_list_item_set_child(int $handle, int $child): void
{
    ExtGtkListItem::setChild($handle, $child);
}

function gtk_list_item_set_focusable(int $handle, bool $focusable): void
{
    ExtGtkListItem::setFocusable($handle, $focusable);
}

function gtk_list_item_set_selectable(int $handle, bool $selectable): void
{
    ExtGtkListItem::setSelectable($handle, $selectable);
}
