<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkCssProvider\GtkCssProvider as ExtGtkCssProvider;

function gtk_css_provider_new(): int
{
    return ExtGtkCssProvider::new_();
}

function gtk_css_provider_load_from_string(int $handle, string $css): void
{
    ExtGtkCssProvider::loadFromString($handle, $css);
}

function gtk_css_provider_load_from_path(int $handle, string $path): void
{
    ExtGtkCssProvider::loadFromPath($handle, $path);
}

function gtk_css_provider_to_string(int $handle): string
{
    return ExtGtkCssProvider::toString($handle);
}
