<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkHeaderBar\GtkHeaderBar as ExtGtkHeaderBar;

function gtk_header_bar_new(): int
{
    return ExtGtkHeaderBar::new_();
}

function gtk_header_bar_get_decoration_layout(int $handle): mixed
{
    return ExtGtkHeaderBar::getDecorationLayout($handle);
}

function gtk_header_bar_get_show_title_buttons(int $handle): bool
{
    return ExtGtkHeaderBar::getShowTitleButtons($handle);
}

function gtk_header_bar_get_title_widget(int $handle): int
{
    return ExtGtkHeaderBar::getTitleWidget($handle);
}

function gtk_header_bar_get_use_native_controls(int $handle): bool
{
    return ExtGtkHeaderBar::getUseNativeControls($handle);
}

function gtk_header_bar_pack_end(int $handle, int $child): void
{
    ExtGtkHeaderBar::packEnd($handle, $child);
}

function gtk_header_bar_pack_start(int $handle, int $child): void
{
    ExtGtkHeaderBar::packStart($handle, $child);
}

function gtk_header_bar_remove(int $handle, int $child): void
{
    ExtGtkHeaderBar::remove($handle, $child);
}

function gtk_header_bar_set_decoration_layout(int $handle, mixed $layout): void
{
    ExtGtkHeaderBar::setDecorationLayout($handle, $layout);
}

function gtk_header_bar_set_show_title_buttons(int $handle, bool $setting): void
{
    ExtGtkHeaderBar::setShowTitleButtons($handle, $setting);
}

function gtk_header_bar_set_title_widget(int $handle, int $titleWidget): void
{
    ExtGtkHeaderBar::setTitleWidget($handle, $titleWidget);
}

function gtk_header_bar_set_use_native_controls(int $handle, bool $setting): void
{
    ExtGtkHeaderBar::setUseNativeControls($handle, $setting);
}
