<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkOverlay\GtkOverlay as ExtGtkOverlay;

function gtk_overlay_new(): int
{
    return ExtGtkOverlay::new_();
}

function gtk_overlay_add_overlay(int $handle, int $widget): void
{
    ExtGtkOverlay::addOverlay($handle, $widget);
}

function gtk_overlay_get_child(int $handle): int
{
    return ExtGtkOverlay::getChild($handle);
}

function gtk_overlay_get_clip_overlay(int $handle, int $widget): bool
{
    return ExtGtkOverlay::getClipOverlay($handle, $widget);
}

function gtk_overlay_get_measure_overlay(int $handle, int $widget): bool
{
    return ExtGtkOverlay::getMeasureOverlay($handle, $widget);
}

function gtk_overlay_remove_overlay(int $handle, int $widget): void
{
    ExtGtkOverlay::removeOverlay($handle, $widget);
}

function gtk_overlay_set_child(int $handle, int $child): void
{
    ExtGtkOverlay::setChild($handle, $child);
}

function gtk_overlay_set_clip_overlay(int $handle, int $widget, bool $clipOverlay): void
{
    ExtGtkOverlay::setClipOverlay($handle, $widget, $clipOverlay);
}

function gtk_overlay_set_measure_overlay(int $handle, int $widget, bool $measure): void
{
    ExtGtkOverlay::setMeasureOverlay($handle, $widget, $measure);
}
