<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkEditable\GtkEditable as ExtGtkEditable;

function gtk_editable_delegate_get_accessible_platform_state(int $handle, int $state): bool
{
    return ExtGtkEditable::delegateGetAccessiblePlatformState($handle, $state);
}

function gtk_editable_delete_selection(int $handle): void
{
    ExtGtkEditable::deleteSelection($handle);
}

function gtk_editable_delete_text(int $handle, int $startPos, int $endPos): void
{
    ExtGtkEditable::deleteText($handle, $startPos, $endPos);
}

function gtk_editable_finish_delegate(int $handle): void
{
    ExtGtkEditable::finishDelegate($handle);
}

function gtk_editable_get_alignment(int $handle): float
{
    return ExtGtkEditable::getAlignment($handle);
}

function gtk_editable_get_chars(int $handle, int $startPos, int $endPos): mixed
{
    return ExtGtkEditable::getChars($handle, $startPos, $endPos);
}

function gtk_editable_get_delegate(int $handle): int
{
    return ExtGtkEditable::getDelegate($handle);
}

function gtk_editable_get_editable(int $handle): bool
{
    return ExtGtkEditable::getEditable($handle);
}

function gtk_editable_get_enable_undo(int $handle): bool
{
    return ExtGtkEditable::getEnableUndo($handle);
}

function gtk_editable_get_max_width_chars(int $handle): int
{
    return ExtGtkEditable::getMaxWidthChars($handle);
}

function gtk_editable_get_position(int $handle): int
{
    return ExtGtkEditable::getPosition($handle);
}

function gtk_editable_get_selection_bounds(int $handle): array
{
    return ExtGtkEditable::getSelectionBounds($handle);
}

function gtk_editable_get_text(int $handle): mixed
{
    return ExtGtkEditable::getText($handle);
}

function gtk_editable_get_width_chars(int $handle): int
{
    return ExtGtkEditable::getWidthChars($handle);
}

function gtk_editable_init_delegate(int $handle): void
{
    ExtGtkEditable::initDelegate($handle);
}

function gtk_editable_insert_text(int $handle, string $text, int $length, int $position): array
{
    return ExtGtkEditable::insertText($handle, $text, $length, $position);
}

function gtk_editable_select_region(int $handle, int $startPos, int $endPos): void
{
    ExtGtkEditable::selectRegion($handle, $startPos, $endPos);
}

function gtk_editable_set_alignment(int $handle, float $xalign): void
{
    ExtGtkEditable::setAlignment($handle, $xalign);
}

function gtk_editable_set_editable(int $handle, bool $isEditable): void
{
    ExtGtkEditable::setEditable($handle, $isEditable);
}

function gtk_editable_set_enable_undo(int $handle, bool $enableUndo): void
{
    ExtGtkEditable::setEnableUndo($handle, $enableUndo);
}

function gtk_editable_set_max_width_chars(int $handle, int $nChars): void
{
    ExtGtkEditable::setMaxWidthChars($handle, $nChars);
}

function gtk_editable_set_position(int $handle, int $position): void
{
    ExtGtkEditable::setPosition($handle, $position);
}

function gtk_editable_set_text(int $handle, string $text): void
{
    ExtGtkEditable::setText($handle, $text);
}

function gtk_editable_set_width_chars(int $handle, int $nChars): void
{
    ExtGtkEditable::setWidthChars($handle, $nChars);
}
