<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkExpander\GtkExpander as ExtGtkExpander;

function gtk_expander_new(mixed $label): int
{
    return ExtGtkExpander::new_($label);
}

function gtk_expander_new_with_mnemonic(mixed $label): int
{
    return ExtGtkExpander::newWithMnemonic($label);
}

function gtk_expander_get_child(int $handle): int
{
    return ExtGtkExpander::getChild($handle);
}

function gtk_expander_get_expanded(int $handle): bool
{
    return ExtGtkExpander::getExpanded($handle);
}

function gtk_expander_get_label(int $handle): mixed
{
    return ExtGtkExpander::getLabel($handle);
}

function gtk_expander_get_label_widget(int $handle): int
{
    return ExtGtkExpander::getLabelWidget($handle);
}

function gtk_expander_get_resize_toplevel(int $handle): bool
{
    return ExtGtkExpander::getResizeToplevel($handle);
}

function gtk_expander_get_use_markup(int $handle): bool
{
    return ExtGtkExpander::getUseMarkup($handle);
}

function gtk_expander_get_use_underline(int $handle): bool
{
    return ExtGtkExpander::getUseUnderline($handle);
}

function gtk_expander_set_child(int $handle, int $child): void
{
    ExtGtkExpander::setChild($handle, $child);
}

function gtk_expander_set_expanded(int $handle, bool $expanded): void
{
    ExtGtkExpander::setExpanded($handle, $expanded);
}

function gtk_expander_set_label(int $handle, mixed $label): void
{
    ExtGtkExpander::setLabel($handle, $label);
}

function gtk_expander_set_label_widget(int $handle, int $labelWidget): void
{
    ExtGtkExpander::setLabelWidget($handle, $labelWidget);
}

function gtk_expander_set_resize_toplevel(int $handle, bool $resizeToplevel): void
{
    ExtGtkExpander::setResizeToplevel($handle, $resizeToplevel);
}

function gtk_expander_set_use_markup(int $handle, bool $useMarkup): void
{
    ExtGtkExpander::setUseMarkup($handle, $useMarkup);
}

function gtk_expander_set_use_underline(int $handle, bool $useUnderline): void
{
    ExtGtkExpander::setUseUnderline($handle, $useUnderline);
}
