<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkTextTag\GtkTextTag as ExtGtkTextTag;

function gtk_text_tag_new(mixed $name): int
{
    return ExtGtkTextTag::new_($name);
}

function gtk_text_tag_changed(int $handle, bool $sizeChanged): void
{
    ExtGtkTextTag::changed($handle, $sizeChanged);
}

function gtk_text_tag_get_priority(int $handle): int
{
    return ExtGtkTextTag::getPriority($handle);
}

function gtk_text_tag_set_priority(int $handle, int $priority): void
{
    ExtGtkTextTag::setPriority($handle, $priority);
}
