<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkNoSelection\GtkNoSelection as ExtGtkNoSelection;

function gtk_no_selection_new(int $model): int
{
    return ExtGtkNoSelection::new_($model);
}

function gtk_no_selection_get_model(int $handle): int
{
    return ExtGtkNoSelection::getModel($handle);
}

function gtk_no_selection_set_model(int $handle, int $model): void
{
    ExtGtkNoSelection::setModel($handle, $model);
}
