<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkStringList\GtkStringList as ExtGtkStringList;

function gtk_string_list_new(mixed $strings): int
{
    return ExtGtkStringList::new_($strings);
}

function gtk_string_list_append(int $handle, string $string_): void
{
    ExtGtkStringList::append($handle, $string_);
}

function gtk_string_list_find(int $handle, string $string_): int
{
    return ExtGtkStringList::find($handle, $string_);
}

function gtk_string_list_get_string(int $handle, int $position): mixed
{
    return ExtGtkStringList::getString($handle, $position);
}

function gtk_string_list_remove(int $handle, int $position): void
{
    ExtGtkStringList::remove($handle, $position);
}

function gtk_string_list_splice(int $handle, int $position, int $nRemovals, mixed $additions): void
{
    ExtGtkStringList::splice($handle, $position, $nRemovals, $additions);
}

function gtk_string_list_take(int $handle, string $string_): void
{
    ExtGtkStringList::take($handle, $string_);
}
