<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkActionable\GtkActionable as ExtGtkActionable;

function gtk_actionable_get_action_name(int $handle): mixed
{
    return ExtGtkActionable::getActionName($handle);
}

function gtk_actionable_set_action_name(int $handle, mixed $actionName): void
{
    ExtGtkActionable::setActionName($handle, $actionName);
}

function gtk_actionable_set_detailed_action_name(int $handle, string $detailedActionName): void
{
    ExtGtkActionable::setDetailedActionName($handle, $detailedActionName);
}
