<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkAboutDialog\GtkAboutDialog as ExtGtkAboutDialog;

function gtk_about_dialog_new(): int
{
    return ExtGtkAboutDialog::new_();
}

function gtk_about_dialog_add_credit_section(int $handle, string $sectionName, array $people): void
{
    ExtGtkAboutDialog::addCreditSection($handle, $sectionName, $people);
}

function gtk_about_dialog_get_artists(int $handle): array
{
    return ExtGtkAboutDialog::getArtists($handle);
}

function gtk_about_dialog_get_authors(int $handle): array
{
    return ExtGtkAboutDialog::getAuthors($handle);
}

function gtk_about_dialog_get_comments(int $handle): mixed
{
    return ExtGtkAboutDialog::getComments($handle);
}

function gtk_about_dialog_get_copyright(int $handle): mixed
{
    return ExtGtkAboutDialog::getCopyright($handle);
}

function gtk_about_dialog_get_documenters(int $handle): array
{
    return ExtGtkAboutDialog::getDocumenters($handle);
}

function gtk_about_dialog_get_license(int $handle): mixed
{
    return ExtGtkAboutDialog::getLicense($handle);
}

function gtk_about_dialog_get_license_type(int $handle): int
{
    return ExtGtkAboutDialog::getLicenseType($handle);
}

function gtk_about_dialog_get_logo(int $handle): int
{
    return ExtGtkAboutDialog::getLogo($handle);
}

function gtk_about_dialog_get_logo_icon_name(int $handle): mixed
{
    return ExtGtkAboutDialog::getLogoIconName($handle);
}

function gtk_about_dialog_get_program_name(int $handle): mixed
{
    return ExtGtkAboutDialog::getProgramName($handle);
}

function gtk_about_dialog_get_system_information(int $handle): mixed
{
    return ExtGtkAboutDialog::getSystemInformation($handle);
}

function gtk_about_dialog_get_translator_credits(int $handle): mixed
{
    return ExtGtkAboutDialog::getTranslatorCredits($handle);
}

function gtk_about_dialog_get_version(int $handle): mixed
{
    return ExtGtkAboutDialog::getVersion($handle);
}

function gtk_about_dialog_get_website(int $handle): mixed
{
    return ExtGtkAboutDialog::getWebsite($handle);
}

function gtk_about_dialog_get_website_label(int $handle): mixed
{
    return ExtGtkAboutDialog::getWebsiteLabel($handle);
}

function gtk_about_dialog_get_wrap_license(int $handle): bool
{
    return ExtGtkAboutDialog::getWrapLicense($handle);
}

function gtk_about_dialog_set_artists(int $handle, array $artists): void
{
    ExtGtkAboutDialog::setArtists($handle, $artists);
}

function gtk_about_dialog_set_authors(int $handle, array $authors): void
{
    ExtGtkAboutDialog::setAuthors($handle, $authors);
}

function gtk_about_dialog_set_comments(int $handle, mixed $comments): void
{
    ExtGtkAboutDialog::setComments($handle, $comments);
}

function gtk_about_dialog_set_copyright(int $handle, mixed $copyright): void
{
    ExtGtkAboutDialog::setCopyright($handle, $copyright);
}

function gtk_about_dialog_set_documenters(int $handle, array $documenters): void
{
    ExtGtkAboutDialog::setDocumenters($handle, $documenters);
}

function gtk_about_dialog_set_license(int $handle, mixed $license): void
{
    ExtGtkAboutDialog::setLicense($handle, $license);
}

function gtk_about_dialog_set_license_type(int $handle, int $licenseType): void
{
    ExtGtkAboutDialog::setLicenseType($handle, $licenseType);
}

function gtk_about_dialog_set_logo(int $handle, int $logo): void
{
    ExtGtkAboutDialog::setLogo($handle, $logo);
}

function gtk_about_dialog_set_logo_icon_name(int $handle, mixed $iconName): void
{
    ExtGtkAboutDialog::setLogoIconName($handle, $iconName);
}

function gtk_about_dialog_set_program_name(int $handle, mixed $name): void
{
    ExtGtkAboutDialog::setProgramName($handle, $name);
}

function gtk_about_dialog_set_system_information(int $handle, mixed $systemInformation): void
{
    ExtGtkAboutDialog::setSystemInformation($handle, $systemInformation);
}

function gtk_about_dialog_set_translator_credits(int $handle, mixed $translatorCredits): void
{
    ExtGtkAboutDialog::setTranslatorCredits($handle, $translatorCredits);
}

function gtk_about_dialog_set_version(int $handle, mixed $version): void
{
    ExtGtkAboutDialog::setVersion($handle, $version);
}

function gtk_about_dialog_set_website(int $handle, mixed $website): void
{
    ExtGtkAboutDialog::setWebsite($handle, $website);
}

function gtk_about_dialog_set_website_label(int $handle, string $websiteLabel): void
{
    ExtGtkAboutDialog::setWebsiteLabel($handle, $websiteLabel);
}

function gtk_about_dialog_set_wrap_license(int $handle, bool $wrapLicense): void
{
    ExtGtkAboutDialog::setWrapLicense($handle, $wrapLicense);
}
