<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkApplicationWindow\GtkApplicationWindow as ExtGtkApplicationWindow;

function gtk_application_window_new(int $application): int
{
    return ExtGtkApplicationWindow::new_($application);
}

function gtk_application_window_get_id(int $handle): int
{
    return ExtGtkApplicationWindow::getId($handle);
}

function gtk_application_window_get_show_menubar(int $handle): bool
{
    return ExtGtkApplicationWindow::getShowMenubar($handle);
}

function gtk_application_window_set_show_menubar(int $handle, bool $showMenubar): void
{
    ExtGtkApplicationWindow::setShowMenubar($handle, $showMenubar);
}
