<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkPicture\GtkPicture as ExtGtkPicture;

function gtk_picture_new(): int
{
    return ExtGtkPicture::new_();
}

function gtk_picture_new_for_file(int $file): int
{
    return ExtGtkPicture::newForFile($file);
}

function gtk_picture_new_for_filename(mixed $filename): int
{
    return ExtGtkPicture::newForFilename($filename);
}

function gtk_picture_new_for_paintable(int $paintable): int
{
    return ExtGtkPicture::newForPaintable($paintable);
}

function gtk_picture_new_for_resource(mixed $resourcePath): int
{
    return ExtGtkPicture::newForResource($resourcePath);
}

function gtk_picture_get_alternative_text(int $handle): mixed
{
    return ExtGtkPicture::getAlternativeText($handle);
}

function gtk_picture_get_can_shrink(int $handle): bool
{
    return ExtGtkPicture::getCanShrink($handle);
}

function gtk_picture_get_content_fit(int $handle): int
{
    return ExtGtkPicture::getContentFit($handle);
}

function gtk_picture_get_file(int $handle): int
{
    return ExtGtkPicture::getFile($handle);
}

function gtk_picture_get_paintable(int $handle): int
{
    return ExtGtkPicture::getPaintable($handle);
}

function gtk_picture_set_alternative_text(int $handle, mixed $alternativeText): void
{
    ExtGtkPicture::setAlternativeText($handle, $alternativeText);
}

function gtk_picture_set_can_shrink(int $handle, bool $canShrink): void
{
    ExtGtkPicture::setCanShrink($handle, $canShrink);
}

function gtk_picture_set_content_fit(int $handle, int $contentFit): void
{
    ExtGtkPicture::setContentFit($handle, $contentFit);
}

function gtk_picture_set_file(int $handle, int $file): void
{
    ExtGtkPicture::setFile($handle, $file);
}

function gtk_picture_set_filename(int $handle, mixed $filename): void
{
    ExtGtkPicture::setFilename($handle, $filename);
}

function gtk_picture_set_paintable(int $handle, int $paintable): void
{
    ExtGtkPicture::setPaintable($handle, $paintable);
}

function gtk_picture_set_resource(int $handle, mixed $resourcePath): void
{
    ExtGtkPicture::setResource($handle, $resourcePath);
}
