<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkToggleButton\GtkToggleButton as ExtGtkToggleButton;

function gtk_toggle_button_new(): int
{
    return ExtGtkToggleButton::new_();
}

function gtk_toggle_button_new_with_label(string $label): int
{
    return ExtGtkToggleButton::newWithLabel($label);
}

function gtk_toggle_button_new_with_mnemonic(string $label): int
{
    return ExtGtkToggleButton::newWithMnemonic($label);
}

function gtk_toggle_button_get_active(int $handle): bool
{
    return ExtGtkToggleButton::getActive($handle);
}

function gtk_toggle_button_set_active(int $handle, bool $isActive): void
{
    ExtGtkToggleButton::setActive($handle, $isActive);
}

function gtk_toggle_button_set_group(int $handle, int $group): void
{
    ExtGtkToggleButton::setGroup($handle, $group);
}
