<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkText\GtkText as ExtGtkText;

function gtk_text_new(): int
{
    return ExtGtkText::new_();
}

function gtk_text_new_with_buffer(int $buffer): int
{
    return ExtGtkText::newWithBuffer($buffer);
}

function gtk_text_compute_cursor_extents(int $handle, int $position): array
{
    return ExtGtkText::computeCursorExtents($handle, $position);
}

function gtk_text_get_activates_default(int $handle): bool
{
    return ExtGtkText::getActivatesDefault($handle);
}

function gtk_text_get_buffer(int $handle): int
{
    return ExtGtkText::getBuffer($handle);
}

function gtk_text_get_enable_emoji_completion(int $handle): bool
{
    return ExtGtkText::getEnableEmojiCompletion($handle);
}

function gtk_text_get_extra_menu(int $handle): int
{
    return ExtGtkText::getExtraMenu($handle);
}

function gtk_text_get_input_hints(int $handle): int
{
    return ExtGtkText::getInputHints($handle);
}

function gtk_text_get_input_purpose(int $handle): int
{
    return ExtGtkText::getInputPurpose($handle);
}

function gtk_text_get_invisible_char(int $handle): int
{
    return ExtGtkText::getInvisibleChar($handle);
}

function gtk_text_get_max_length(int $handle): int
{
    return ExtGtkText::getMaxLength($handle);
}

function gtk_text_get_overwrite_mode(int $handle): bool
{
    return ExtGtkText::getOverwriteMode($handle);
}

function gtk_text_get_placeholder_text(int $handle): mixed
{
    return ExtGtkText::getPlaceholderText($handle);
}

function gtk_text_get_propagate_text_width(int $handle): bool
{
    return ExtGtkText::getPropagateTextWidth($handle);
}

function gtk_text_get_text_length(int $handle): int
{
    return ExtGtkText::getTextLength($handle);
}

function gtk_text_get_truncate_multiline(int $handle): bool
{
    return ExtGtkText::getTruncateMultiline($handle);
}

function gtk_text_get_visibility(int $handle): bool
{
    return ExtGtkText::getVisibility($handle);
}

function gtk_text_grab_focus_without_selecting(int $handle): bool
{
    return ExtGtkText::grabFocusWithoutSelecting($handle);
}

function gtk_text_set_activates_default(int $handle, bool $activates): void
{
    ExtGtkText::setActivatesDefault($handle, $activates);
}

function gtk_text_set_buffer(int $handle, int $buffer): void
{
    ExtGtkText::setBuffer($handle, $buffer);
}

function gtk_text_set_enable_emoji_completion(int $handle, bool $enableEmojiCompletion): void
{
    ExtGtkText::setEnableEmojiCompletion($handle, $enableEmojiCompletion);
}

function gtk_text_set_extra_menu(int $handle, int $model): void
{
    ExtGtkText::setExtraMenu($handle, $model);
}

function gtk_text_set_input_hints(int $handle, int $hints): void
{
    ExtGtkText::setInputHints($handle, $hints);
}

function gtk_text_set_input_purpose(int $handle, int $purpose): void
{
    ExtGtkText::setInputPurpose($handle, $purpose);
}

function gtk_text_set_invisible_char(int $handle, int $ch): void
{
    ExtGtkText::setInvisibleChar($handle, $ch);
}

function gtk_text_set_max_length(int $handle, int $length): void
{
    ExtGtkText::setMaxLength($handle, $length);
}

function gtk_text_set_overwrite_mode(int $handle, bool $overwrite): void
{
    ExtGtkText::setOverwriteMode($handle, $overwrite);
}

function gtk_text_set_placeholder_text(int $handle, mixed $text): void
{
    ExtGtkText::setPlaceholderText($handle, $text);
}

function gtk_text_set_propagate_text_width(int $handle, bool $propagateTextWidth): void
{
    ExtGtkText::setPropagateTextWidth($handle, $propagateTextWidth);
}

function gtk_text_set_truncate_multiline(int $handle, bool $truncateMultiline): void
{
    ExtGtkText::setTruncateMultiline($handle, $truncateMultiline);
}

function gtk_text_set_visibility(int $handle, bool $visible): void
{
    ExtGtkText::setVisibility($handle, $visible);
}

function gtk_text_unset_invisible_char(int $handle): void
{
    ExtGtkText::unsetInvisibleChar($handle);
}
