<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkRange\GtkRange as ExtGtkRange;

function gtk_range_get_adjustment(int $handle): int
{
    return ExtGtkRange::getAdjustment($handle);
}

function gtk_range_get_fill_level(int $handle): float
{
    return ExtGtkRange::getFillLevel($handle);
}

function gtk_range_get_flippable(int $handle): bool
{
    return ExtGtkRange::getFlippable($handle);
}

function gtk_range_get_inverted(int $handle): bool
{
    return ExtGtkRange::getInverted($handle);
}

function gtk_range_get_range_rect(int $handle): array
{
    return ExtGtkRange::getRangeRect($handle);
}

function gtk_range_get_restrict_to_fill_level(int $handle): bool
{
    return ExtGtkRange::getRestrictToFillLevel($handle);
}

function gtk_range_get_round_digits(int $handle): int
{
    return ExtGtkRange::getRoundDigits($handle);
}

function gtk_range_get_show_fill_level(int $handle): bool
{
    return ExtGtkRange::getShowFillLevel($handle);
}

function gtk_range_get_slider_range(int $handle): array
{
    return ExtGtkRange::getSliderRange($handle);
}

function gtk_range_get_slider_size_fixed(int $handle): bool
{
    return ExtGtkRange::getSliderSizeFixed($handle);
}

function gtk_range_get_value(int $handle): float
{
    return ExtGtkRange::getValue($handle);
}

function gtk_range_set_adjustment(int $handle, int $adjustment): void
{
    ExtGtkRange::setAdjustment($handle, $adjustment);
}

function gtk_range_set_fill_level(int $handle, float $fillLevel): void
{
    ExtGtkRange::setFillLevel($handle, $fillLevel);
}

function gtk_range_set_flippable(int $handle, bool $flippable): void
{
    ExtGtkRange::setFlippable($handle, $flippable);
}

function gtk_range_set_increments(int $handle, float $step, float $page): void
{
    ExtGtkRange::setIncrements($handle, $step, $page);
}

function gtk_range_set_inverted(int $handle, bool $setting): void
{
    ExtGtkRange::setInverted($handle, $setting);
}

function gtk_range_set_range(int $handle, float $min, float $max): void
{
    ExtGtkRange::setRange($handle, $min, $max);
}

function gtk_range_set_restrict_to_fill_level(int $handle, bool $restrictToFillLevel): void
{
    ExtGtkRange::setRestrictToFillLevel($handle, $restrictToFillLevel);
}

function gtk_range_set_round_digits(int $handle, int $roundDigits): void
{
    ExtGtkRange::setRoundDigits($handle, $roundDigits);
}

function gtk_range_set_show_fill_level(int $handle, bool $showFillLevel): void
{
    ExtGtkRange::setShowFillLevel($handle, $showFillLevel);
}

function gtk_range_set_slider_size_fixed(int $handle, bool $sizeFixed): void
{
    ExtGtkRange::setSliderSizeFixed($handle, $sizeFixed);
}

function gtk_range_set_value(int $handle, float $value): void
{
    ExtGtkRange::setValue($handle, $value);
}
