<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkFlowBoxChild\GtkFlowBoxChild as ExtGtkFlowBoxChild;

function gtk_flow_box_child_new(): int
{
    return ExtGtkFlowBoxChild::new_();
}

function gtk_flow_box_child_changed(int $handle): void
{
    ExtGtkFlowBoxChild::changed($handle);
}

function gtk_flow_box_child_get_child(int $handle): int
{
    return ExtGtkFlowBoxChild::getChild($handle);
}

function gtk_flow_box_child_get_index(int $handle): int
{
    return ExtGtkFlowBoxChild::getIndex($handle);
}

function gtk_flow_box_child_is_selected(int $handle): bool
{
    return ExtGtkFlowBoxChild::isSelected($handle);
}

function gtk_flow_box_child_set_child(int $handle, int $child): void
{
    ExtGtkFlowBoxChild::setChild($handle, $child);
}
