<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkFrame\GtkFrame as ExtGtkFrame;

function gtk_frame_new(mixed $label): int
{
    return ExtGtkFrame::new_($label);
}

function gtk_frame_get_child(int $handle): int
{
    return ExtGtkFrame::getChild($handle);
}

function gtk_frame_get_label(int $handle): mixed
{
    return ExtGtkFrame::getLabel($handle);
}

function gtk_frame_get_label_align(int $handle): float
{
    return ExtGtkFrame::getLabelAlign($handle);
}

function gtk_frame_get_label_widget(int $handle): int
{
    return ExtGtkFrame::getLabelWidget($handle);
}

function gtk_frame_set_child(int $handle, int $child): void
{
    ExtGtkFrame::setChild($handle, $child);
}

function gtk_frame_set_label(int $handle, mixed $label): void
{
    ExtGtkFrame::setLabel($handle, $label);
}

function gtk_frame_set_label_align(int $handle, float $xalign): void
{
    ExtGtkFrame::setLabelAlign($handle, $xalign);
}

function gtk_frame_set_label_widget(int $handle, int $labelWidget): void
{
    ExtGtkFrame::setLabelWidget($handle, $labelWidget);
}
