<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkStackSidebar\GtkStackSidebar as ExtGtkStackSidebar;

function gtk_stack_sidebar_new(): int
{
    return ExtGtkStackSidebar::new_();
}

function gtk_stack_sidebar_get_stack(int $handle): int
{
    return ExtGtkStackSidebar::getStack($handle);
}

function gtk_stack_sidebar_set_stack(int $handle, int $stack): void
{
    ExtGtkStackSidebar::setStack($handle, $stack);
}
