<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkNotebook\GtkNotebook as ExtGtkNotebook;

function gtk_notebook_new(): int
{
    return ExtGtkNotebook::new_();
}

function gtk_notebook_append_page(int $handle, int $child, int $tabLabel): int
{
    return ExtGtkNotebook::appendPage($handle, $child, $tabLabel);
}

function gtk_notebook_append_page_menu(int $handle, int $child, int $tabLabel, int $menuLabel): int
{
    return ExtGtkNotebook::appendPageMenu($handle, $child, $tabLabel, $menuLabel);
}

function gtk_notebook_detach_tab(int $handle, int $child): void
{
    ExtGtkNotebook::detachTab($handle, $child);
}

function gtk_notebook_get_action_widget(int $handle, int $packType): int
{
    return ExtGtkNotebook::getActionWidget($handle, $packType);
}

function gtk_notebook_get_current_page(int $handle): int
{
    return ExtGtkNotebook::getCurrentPage($handle);
}

function gtk_notebook_get_group_name(int $handle): mixed
{
    return ExtGtkNotebook::getGroupName($handle);
}

function gtk_notebook_get_menu_label(int $handle, int $child): int
{
    return ExtGtkNotebook::getMenuLabel($handle, $child);
}

function gtk_notebook_get_menu_label_text(int $handle, int $child): mixed
{
    return ExtGtkNotebook::getMenuLabelText($handle, $child);
}

function gtk_notebook_get_n_pages(int $handle): int
{
    return ExtGtkNotebook::getNPages($handle);
}

function gtk_notebook_get_nth_page(int $handle, int $pageNum): int
{
    return ExtGtkNotebook::getNthPage($handle, $pageNum);
}

function gtk_notebook_get_page(int $handle, int $child): int
{
    return ExtGtkNotebook::getPage($handle, $child);
}

function gtk_notebook_get_pages(int $handle): int
{
    return ExtGtkNotebook::getPages($handle);
}

function gtk_notebook_get_scrollable(int $handle): bool
{
    return ExtGtkNotebook::getScrollable($handle);
}

function gtk_notebook_get_show_border(int $handle): bool
{
    return ExtGtkNotebook::getShowBorder($handle);
}

function gtk_notebook_get_show_tabs(int $handle): bool
{
    return ExtGtkNotebook::getShowTabs($handle);
}

function gtk_notebook_get_tab_detachable(int $handle, int $child): bool
{
    return ExtGtkNotebook::getTabDetachable($handle, $child);
}

function gtk_notebook_get_tab_label(int $handle, int $child): int
{
    return ExtGtkNotebook::getTabLabel($handle, $child);
}

function gtk_notebook_get_tab_label_text(int $handle, int $child): mixed
{
    return ExtGtkNotebook::getTabLabelText($handle, $child);
}

function gtk_notebook_get_tab_pos(int $handle): int
{
    return ExtGtkNotebook::getTabPos($handle);
}

function gtk_notebook_get_tab_reorderable(int $handle, int $child): bool
{
    return ExtGtkNotebook::getTabReorderable($handle, $child);
}

function gtk_notebook_insert_page(int $handle, int $child, int $tabLabel, int $position): int
{
    return ExtGtkNotebook::insertPage($handle, $child, $tabLabel, $position);
}

function gtk_notebook_insert_page_menu(int $handle, int $child, int $tabLabel, int $menuLabel, int $position): int
{
    return ExtGtkNotebook::insertPageMenu($handle, $child, $tabLabel, $menuLabel, $position);
}

function gtk_notebook_next_page(int $handle): void
{
    ExtGtkNotebook::nextPage($handle);
}

function gtk_notebook_page_num(int $handle, int $child): int
{
    return ExtGtkNotebook::pageNum($handle, $child);
}

function gtk_notebook_popup_disable(int $handle): void
{
    ExtGtkNotebook::popupDisable($handle);
}

function gtk_notebook_popup_enable(int $handle): void
{
    ExtGtkNotebook::popupEnable($handle);
}

function gtk_notebook_prepend_page(int $handle, int $child, int $tabLabel): int
{
    return ExtGtkNotebook::prependPage($handle, $child, $tabLabel);
}

function gtk_notebook_prepend_page_menu(int $handle, int $child, int $tabLabel, int $menuLabel): int
{
    return ExtGtkNotebook::prependPageMenu($handle, $child, $tabLabel, $menuLabel);
}

function gtk_notebook_prev_page(int $handle): void
{
    ExtGtkNotebook::prevPage($handle);
}

function gtk_notebook_remove_page(int $handle, int $pageNum): void
{
    ExtGtkNotebook::removePage($handle, $pageNum);
}

function gtk_notebook_reorder_child(int $handle, int $child, int $position): void
{
    ExtGtkNotebook::reorderChild($handle, $child, $position);
}

function gtk_notebook_set_action_widget(int $handle, int $widget, int $packType): void
{
    ExtGtkNotebook::setActionWidget($handle, $widget, $packType);
}

function gtk_notebook_set_current_page(int $handle, int $pageNum): void
{
    ExtGtkNotebook::setCurrentPage($handle, $pageNum);
}

function gtk_notebook_set_group_name(int $handle, mixed $groupName): void
{
    ExtGtkNotebook::setGroupName($handle, $groupName);
}

function gtk_notebook_set_menu_label(int $handle, int $child, int $menuLabel): void
{
    ExtGtkNotebook::setMenuLabel($handle, $child, $menuLabel);
}

function gtk_notebook_set_menu_label_text(int $handle, int $child, string $menuText): void
{
    ExtGtkNotebook::setMenuLabelText($handle, $child, $menuText);
}

function gtk_notebook_set_scrollable(int $handle, bool $scrollable): void
{
    ExtGtkNotebook::setScrollable($handle, $scrollable);
}

function gtk_notebook_set_show_border(int $handle, bool $showBorder): void
{
    ExtGtkNotebook::setShowBorder($handle, $showBorder);
}

function gtk_notebook_set_show_tabs(int $handle, bool $showTabs): void
{
    ExtGtkNotebook::setShowTabs($handle, $showTabs);
}

function gtk_notebook_set_tab_detachable(int $handle, int $child, bool $detachable): void
{
    ExtGtkNotebook::setTabDetachable($handle, $child, $detachable);
}

function gtk_notebook_set_tab_label(int $handle, int $child, int $tabLabel): void
{
    ExtGtkNotebook::setTabLabel($handle, $child, $tabLabel);
}

function gtk_notebook_set_tab_label_text(int $handle, int $child, string $tabText): void
{
    ExtGtkNotebook::setTabLabelText($handle, $child, $tabText);
}

function gtk_notebook_set_tab_pos(int $handle, int $pos): void
{
    ExtGtkNotebook::setTabPos($handle, $pos);
}

function gtk_notebook_set_tab_reorderable(int $handle, int $child, bool $reorderable): void
{
    ExtGtkNotebook::setTabReorderable($handle, $child, $reorderable);
}
