<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkNotebookPage\GtkNotebookPage as ExtGtkNotebookPage;

function gtk_notebook_page_get_child(int $handle): int
{
    return ExtGtkNotebookPage::getChild($handle);
}
