<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkViewport\GtkViewport as ExtGtkViewport;

function gtk_viewport_new(int $hadjustment, int $vadjustment): int
{
    return ExtGtkViewport::new_($hadjustment, $vadjustment);
}

function gtk_viewport_get_child(int $handle): int
{
    return ExtGtkViewport::getChild($handle);
}

function gtk_viewport_get_scroll_to_focus(int $handle): bool
{
    return ExtGtkViewport::getScrollToFocus($handle);
}

function gtk_viewport_set_child(int $handle, int $child): void
{
    ExtGtkViewport::setChild($handle, $child);
}

function gtk_viewport_set_scroll_to_focus(int $handle, bool $scrollToFocus): void
{
    ExtGtkViewport::setScrollToFocus($handle, $scrollToFocus);
}
