<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkProgressBar\GtkProgressBar as ExtGtkProgressBar;

function gtk_progress_bar_new(): int
{
    return ExtGtkProgressBar::new_();
}

function gtk_progress_bar_get_ellipsize(int $handle): int
{
    return ExtGtkProgressBar::getEllipsize($handle);
}

function gtk_progress_bar_get_fraction(int $handle): float
{
    return ExtGtkProgressBar::getFraction($handle);
}

function gtk_progress_bar_get_inverted(int $handle): bool
{
    return ExtGtkProgressBar::getInverted($handle);
}

function gtk_progress_bar_get_pulse_step(int $handle): float
{
    return ExtGtkProgressBar::getPulseStep($handle);
}

function gtk_progress_bar_get_show_text(int $handle): bool
{
    return ExtGtkProgressBar::getShowText($handle);
}

function gtk_progress_bar_get_text(int $handle): mixed
{
    return ExtGtkProgressBar::getText($handle);
}

function gtk_progress_bar_pulse(int $handle): void
{
    ExtGtkProgressBar::pulse($handle);
}

function gtk_progress_bar_set_ellipsize(int $handle, int $mode): void
{
    ExtGtkProgressBar::setEllipsize($handle, $mode);
}

function gtk_progress_bar_set_fraction(int $handle, float $fraction): void
{
    ExtGtkProgressBar::setFraction($handle, $fraction);
}

function gtk_progress_bar_set_inverted(int $handle, bool $inverted): void
{
    ExtGtkProgressBar::setInverted($handle, $inverted);
}

function gtk_progress_bar_set_pulse_step(int $handle, float $fraction): void
{
    ExtGtkProgressBar::setPulseStep($handle, $fraction);
}

function gtk_progress_bar_set_show_text(int $handle, bool $showText): void
{
    ExtGtkProgressBar::setShowText($handle, $showText);
}

function gtk_progress_bar_set_text(int $handle, mixed $text): void
{
    ExtGtkProgressBar::setText($handle, $text);
}
