<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkImage\GtkImage as ExtGtkImage;

function gtk_image_new(): int
{
    return ExtGtkImage::new_();
}

function gtk_image_new_from_file(string $filename): int
{
    return ExtGtkImage::newFromFile($filename);
}

function gtk_image_new_from_gicon(int $icon): int
{
    return ExtGtkImage::newFromGicon($icon);
}

function gtk_image_new_from_icon_name(mixed $iconName): int
{
    return ExtGtkImage::newFromIconName($iconName);
}

function gtk_image_new_from_paintable(int $paintable): int
{
    return ExtGtkImage::newFromPaintable($paintable);
}

function gtk_image_new_from_resource(string $resourcePath): int
{
    return ExtGtkImage::newFromResource($resourcePath);
}

function gtk_image_clear(int $handle): void
{
    ExtGtkImage::clear($handle);
}

function gtk_image_get_gicon(int $handle): int
{
    return ExtGtkImage::getGicon($handle);
}

function gtk_image_get_icon_name(int $handle): mixed
{
    return ExtGtkImage::getIconName($handle);
}

function gtk_image_get_icon_size(int $handle): int
{
    return ExtGtkImage::getIconSize($handle);
}

function gtk_image_get_paintable(int $handle): int
{
    return ExtGtkImage::getPaintable($handle);
}

function gtk_image_get_pixel_size(int $handle): int
{
    return ExtGtkImage::getPixelSize($handle);
}

function gtk_image_get_storage_type(int $handle): int
{
    return ExtGtkImage::getStorageType($handle);
}

function gtk_image_set_from_file(int $handle, mixed $filename): void
{
    ExtGtkImage::setFromFile($handle, $filename);
}

function gtk_image_set_from_gicon(int $handle, int $icon): void
{
    ExtGtkImage::setFromGicon($handle, $icon);
}

function gtk_image_set_from_icon_name(int $handle, mixed $iconName): void
{
    ExtGtkImage::setFromIconName($handle, $iconName);
}

function gtk_image_set_from_paintable(int $handle, int $paintable): void
{
    ExtGtkImage::setFromPaintable($handle, $paintable);
}

function gtk_image_set_from_resource(int $handle, mixed $resourcePath): void
{
    ExtGtkImage::setFromResource($handle, $resourcePath);
}

function gtk_image_set_icon_size(int $handle, int $iconSize): void
{
    ExtGtkImage::setIconSize($handle, $iconSize);
}

function gtk_image_set_pixel_size(int $handle, int $pixelSize): void
{
    ExtGtkImage::setPixelSize($handle, $pixelSize);
}
