<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkSignalListItemFactory\GtkSignalListItemFactory as ExtGtkSignalListItemFactory;

function gtk_signal_list_item_factory_new(): int
{
    return ExtGtkSignalListItemFactory::new_();
}
