<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkTextView\GtkTextView as ExtGtkTextView;

function gtk_text_view_new(): int
{
    return ExtGtkTextView::new_();
}

function gtk_text_view_new_with_buffer(int $buffer): int
{
    return ExtGtkTextView::newWithBuffer($buffer);
}

function gtk_text_view_add_child_at_anchor(int $handle, int $child, int $anchor): void
{
    ExtGtkTextView::addChildAtAnchor($handle, $child, $anchor);
}

function gtk_text_view_add_overlay(int $handle, int $child, int $xpos, int $ypos): void
{
    ExtGtkTextView::addOverlay($handle, $child, $xpos, $ypos);
}

function gtk_text_view_buffer_to_window_coords(int $handle, int $win, int $bufferX, int $bufferY): array
{
    return ExtGtkTextView::bufferToWindowCoords($handle, $win, $bufferX, $bufferY);
}

function gtk_text_view_get_accepts_tab(int $handle): bool
{
    return ExtGtkTextView::getAcceptsTab($handle);
}

function gtk_text_view_get_bottom_margin(int $handle): int
{
    return ExtGtkTextView::getBottomMargin($handle);
}

function gtk_text_view_get_buffer(int $handle): int
{
    return ExtGtkTextView::getBuffer($handle);
}

function gtk_text_view_get_cursor_visible(int $handle): bool
{
    return ExtGtkTextView::getCursorVisible($handle);
}

function gtk_text_view_get_editable(int $handle): bool
{
    return ExtGtkTextView::getEditable($handle);
}

function gtk_text_view_get_extra_menu(int $handle): int
{
    return ExtGtkTextView::getExtraMenu($handle);
}

function gtk_text_view_get_gutter(int $handle, int $win): int
{
    return ExtGtkTextView::getGutter($handle, $win);
}

function gtk_text_view_get_indent(int $handle): int
{
    return ExtGtkTextView::getIndent($handle);
}

function gtk_text_view_get_input_hints(int $handle): int
{
    return ExtGtkTextView::getInputHints($handle);
}

function gtk_text_view_get_input_purpose(int $handle): int
{
    return ExtGtkTextView::getInputPurpose($handle);
}

function gtk_text_view_get_justification(int $handle): int
{
    return ExtGtkTextView::getJustification($handle);
}

function gtk_text_view_get_left_margin(int $handle): int
{
    return ExtGtkTextView::getLeftMargin($handle);
}

function gtk_text_view_get_ltr_context(int $handle): int
{
    return ExtGtkTextView::getLtrContext($handle);
}

function gtk_text_view_get_monospace(int $handle): bool
{
    return ExtGtkTextView::getMonospace($handle);
}

function gtk_text_view_get_overwrite(int $handle): bool
{
    return ExtGtkTextView::getOverwrite($handle);
}

function gtk_text_view_get_pixels_above_lines(int $handle): int
{
    return ExtGtkTextView::getPixelsAboveLines($handle);
}

function gtk_text_view_get_pixels_below_lines(int $handle): int
{
    return ExtGtkTextView::getPixelsBelowLines($handle);
}

function gtk_text_view_get_pixels_inside_wrap(int $handle): int
{
    return ExtGtkTextView::getPixelsInsideWrap($handle);
}

function gtk_text_view_get_right_margin(int $handle): int
{
    return ExtGtkTextView::getRightMargin($handle);
}

function gtk_text_view_get_rtl_context(int $handle): int
{
    return ExtGtkTextView::getRtlContext($handle);
}

function gtk_text_view_get_top_margin(int $handle): int
{
    return ExtGtkTextView::getTopMargin($handle);
}

function gtk_text_view_get_visible_offset(int $handle): array
{
    return ExtGtkTextView::getVisibleOffset($handle);
}

function gtk_text_view_get_visible_rect(int $handle): array
{
    return ExtGtkTextView::getVisibleRect($handle);
}

function gtk_text_view_get_wrap_mode(int $handle): int
{
    return ExtGtkTextView::getWrapMode($handle);
}

function gtk_text_view_im_context_filter_keypress(int $handle, int $event): bool
{
    return ExtGtkTextView::imContextFilterKeypress($handle, $event);
}

function gtk_text_view_move_mark_onscreen(int $handle, int $mark): bool
{
    return ExtGtkTextView::moveMarkOnscreen($handle, $mark);
}

function gtk_text_view_move_overlay(int $handle, int $child, int $xpos, int $ypos): void
{
    ExtGtkTextView::moveOverlay($handle, $child, $xpos, $ypos);
}

function gtk_text_view_place_cursor_onscreen(int $handle): bool
{
    return ExtGtkTextView::placeCursorOnscreen($handle);
}

function gtk_text_view_remove(int $handle, int $child): void
{
    ExtGtkTextView::remove($handle, $child);
}

function gtk_text_view_reset_cursor_blink(int $handle): void
{
    ExtGtkTextView::resetCursorBlink($handle);
}

function gtk_text_view_reset_im_context(int $handle): void
{
    ExtGtkTextView::resetImContext($handle);
}

function gtk_text_view_scroll_mark_onscreen(int $handle, int $mark): void
{
    ExtGtkTextView::scrollMarkOnscreen($handle, $mark);
}

function gtk_text_view_scroll_to_mark(int $handle, int $mark, float $withinMargin, bool $useAlign, float $xalign, float $yalign): void
{
    ExtGtkTextView::scrollToMark($handle, $mark, $withinMargin, $useAlign, $xalign, $yalign);
}

function gtk_text_view_set_accepts_tab(int $handle, bool $acceptsTab): void
{
    ExtGtkTextView::setAcceptsTab($handle, $acceptsTab);
}

function gtk_text_view_set_bottom_margin(int $handle, int $bottomMargin): void
{
    ExtGtkTextView::setBottomMargin($handle, $bottomMargin);
}

function gtk_text_view_set_buffer(int $handle, int $buffer): void
{
    ExtGtkTextView::setBuffer($handle, $buffer);
}

function gtk_text_view_set_cursor_visible(int $handle, bool $setting): void
{
    ExtGtkTextView::setCursorVisible($handle, $setting);
}

function gtk_text_view_set_editable(int $handle, bool $setting): void
{
    ExtGtkTextView::setEditable($handle, $setting);
}

function gtk_text_view_set_extra_menu(int $handle, int $model): void
{
    ExtGtkTextView::setExtraMenu($handle, $model);
}

function gtk_text_view_set_gutter(int $handle, int $win, int $widget): void
{
    ExtGtkTextView::setGutter($handle, $win, $widget);
}

function gtk_text_view_set_indent(int $handle, int $indent): void
{
    ExtGtkTextView::setIndent($handle, $indent);
}

function gtk_text_view_set_input_hints(int $handle, int $hints): void
{
    ExtGtkTextView::setInputHints($handle, $hints);
}

function gtk_text_view_set_input_purpose(int $handle, int $purpose): void
{
    ExtGtkTextView::setInputPurpose($handle, $purpose);
}

function gtk_text_view_set_justification(int $handle, int $justification): void
{
    ExtGtkTextView::setJustification($handle, $justification);
}

function gtk_text_view_set_left_margin(int $handle, int $leftMargin): void
{
    ExtGtkTextView::setLeftMargin($handle, $leftMargin);
}

function gtk_text_view_set_monospace(int $handle, bool $monospace): void
{
    ExtGtkTextView::setMonospace($handle, $monospace);
}

function gtk_text_view_set_overwrite(int $handle, bool $overwrite): void
{
    ExtGtkTextView::setOverwrite($handle, $overwrite);
}

function gtk_text_view_set_pixels_above_lines(int $handle, int $pixelsAboveLines): void
{
    ExtGtkTextView::setPixelsAboveLines($handle, $pixelsAboveLines);
}

function gtk_text_view_set_pixels_below_lines(int $handle, int $pixelsBelowLines): void
{
    ExtGtkTextView::setPixelsBelowLines($handle, $pixelsBelowLines);
}

function gtk_text_view_set_pixels_inside_wrap(int $handle, int $pixelsInsideWrap): void
{
    ExtGtkTextView::setPixelsInsideWrap($handle, $pixelsInsideWrap);
}

function gtk_text_view_set_right_margin(int $handle, int $rightMargin): void
{
    ExtGtkTextView::setRightMargin($handle, $rightMargin);
}

function gtk_text_view_set_top_margin(int $handle, int $topMargin): void
{
    ExtGtkTextView::setTopMargin($handle, $topMargin);
}

function gtk_text_view_set_wrap_mode(int $handle, int $wrapMode): void
{
    ExtGtkTextView::setWrapMode($handle, $wrapMode);
}

function gtk_text_view_window_to_buffer_coords(int $handle, int $win, int $windowX, int $windowY): array
{
    return ExtGtkTextView::windowToBufferCoords($handle, $win, $windowX, $windowY);
}
