<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkColumnViewColumn\GtkColumnViewColumn as ExtGtkColumnViewColumn;

function gtk_column_view_column_new(mixed $title, int $factory): int
{
    return ExtGtkColumnViewColumn::new_($title, $factory);
}

function gtk_column_view_column_get_column_view(int $handle): int
{
    return ExtGtkColumnViewColumn::getColumnView($handle);
}

function gtk_column_view_column_get_expand(int $handle): bool
{
    return ExtGtkColumnViewColumn::getExpand($handle);
}

function gtk_column_view_column_get_factory(int $handle): int
{
    return ExtGtkColumnViewColumn::getFactory($handle);
}

function gtk_column_view_column_get_fixed_width(int $handle): int
{
    return ExtGtkColumnViewColumn::getFixedWidth($handle);
}

function gtk_column_view_column_get_header_menu(int $handle): int
{
    return ExtGtkColumnViewColumn::getHeaderMenu($handle);
}

function gtk_column_view_column_get_id(int $handle): mixed
{
    return ExtGtkColumnViewColumn::getId($handle);
}

function gtk_column_view_column_get_resizable(int $handle): bool
{
    return ExtGtkColumnViewColumn::getResizable($handle);
}

function gtk_column_view_column_get_title(int $handle): mixed
{
    return ExtGtkColumnViewColumn::getTitle($handle);
}

function gtk_column_view_column_get_visible(int $handle): bool
{
    return ExtGtkColumnViewColumn::getVisible($handle);
}

function gtk_column_view_column_set_expand(int $handle, bool $expand): void
{
    ExtGtkColumnViewColumn::setExpand($handle, $expand);
}

function gtk_column_view_column_set_factory(int $handle, int $factory): void
{
    ExtGtkColumnViewColumn::setFactory($handle, $factory);
}

function gtk_column_view_column_set_fixed_width(int $handle, int $fixedWidth): void
{
    ExtGtkColumnViewColumn::setFixedWidth($handle, $fixedWidth);
}

function gtk_column_view_column_set_header_menu(int $handle, int $menu): void
{
    ExtGtkColumnViewColumn::setHeaderMenu($handle, $menu);
}

function gtk_column_view_column_set_id(int $handle, mixed $id): void
{
    ExtGtkColumnViewColumn::setId($handle, $id);
}

function gtk_column_view_column_set_resizable(int $handle, bool $resizable): void
{
    ExtGtkColumnViewColumn::setResizable($handle, $resizable);
}

function gtk_column_view_column_set_title(int $handle, mixed $title): void
{
    ExtGtkColumnViewColumn::setTitle($handle, $title);
}

function gtk_column_view_column_set_visible(int $handle, bool $visible): void
{
    ExtGtkColumnViewColumn::setVisible($handle, $visible);
}
