<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkCalendar\GtkCalendar as ExtGtkCalendar;

function gtk_calendar_new(): int
{
    return ExtGtkCalendar::new_();
}

function gtk_calendar_clear_marks(int $handle): void
{
    ExtGtkCalendar::clearMarks($handle);
}

function gtk_calendar_get_day(int $handle): int
{
    return ExtGtkCalendar::getDay($handle);
}

function gtk_calendar_get_day_is_marked(int $handle, int $day): bool
{
    return ExtGtkCalendar::getDayIsMarked($handle, $day);
}

function gtk_calendar_get_month(int $handle): int
{
    return ExtGtkCalendar::getMonth($handle);
}

function gtk_calendar_get_show_day_names(int $handle): bool
{
    return ExtGtkCalendar::getShowDayNames($handle);
}

function gtk_calendar_get_show_heading(int $handle): bool
{
    return ExtGtkCalendar::getShowHeading($handle);
}

function gtk_calendar_get_show_week_numbers(int $handle): bool
{
    return ExtGtkCalendar::getShowWeekNumbers($handle);
}

function gtk_calendar_get_year(int $handle): int
{
    return ExtGtkCalendar::getYear($handle);
}

function gtk_calendar_mark_day(int $handle, int $day): void
{
    ExtGtkCalendar::markDay($handle, $day);
}

function gtk_calendar_set_day(int $handle, int $day): void
{
    ExtGtkCalendar::setDay($handle, $day);
}

function gtk_calendar_set_month(int $handle, int $month): void
{
    ExtGtkCalendar::setMonth($handle, $month);
}

function gtk_calendar_set_show_day_names(int $handle, bool $value): void
{
    ExtGtkCalendar::setShowDayNames($handle, $value);
}

function gtk_calendar_set_show_heading(int $handle, bool $value): void
{
    ExtGtkCalendar::setShowHeading($handle, $value);
}

function gtk_calendar_set_show_week_numbers(int $handle, bool $value): void
{
    ExtGtkCalendar::setShowWeekNumbers($handle, $value);
}

function gtk_calendar_set_year(int $handle, int $year): void
{
    ExtGtkCalendar::setYear($handle, $year);
}

function gtk_calendar_unmark_day(int $handle, int $day): void
{
    ExtGtkCalendar::unmarkDay($handle, $day);
}
