<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkRevealer\GtkRevealer as ExtGtkRevealer;

function gtk_revealer_new(): int
{
    return ExtGtkRevealer::new_();
}

function gtk_revealer_get_child(int $handle): int
{
    return ExtGtkRevealer::getChild($handle);
}

function gtk_revealer_get_child_revealed(int $handle): bool
{
    return ExtGtkRevealer::getChildRevealed($handle);
}

function gtk_revealer_get_reveal_child(int $handle): bool
{
    return ExtGtkRevealer::getRevealChild($handle);
}

function gtk_revealer_get_transition_duration(int $handle): int
{
    return ExtGtkRevealer::getTransitionDuration($handle);
}

function gtk_revealer_get_transition_type(int $handle): int
{
    return ExtGtkRevealer::getTransitionType($handle);
}

function gtk_revealer_set_child(int $handle, int $child): void
{
    ExtGtkRevealer::setChild($handle, $child);
}

function gtk_revealer_set_reveal_child(int $handle, bool $revealChild): void
{
    ExtGtkRevealer::setRevealChild($handle, $revealChild);
}

function gtk_revealer_set_transition_duration(int $handle, int $duration): void
{
    ExtGtkRevealer::setTransitionDuration($handle, $duration);
}

function gtk_revealer_set_transition_type(int $handle, int $transition): void
{
    ExtGtkRevealer::setTransitionType($handle, $transition);
}
