<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkCenterBox\GtkCenterBox as ExtGtkCenterBox;

function gtk_center_box_new(): int
{
    return ExtGtkCenterBox::new_();
}

function gtk_center_box_get_baseline_position(int $handle): int
{
    return ExtGtkCenterBox::getBaselinePosition($handle);
}

function gtk_center_box_get_center_widget(int $handle): int
{
    return ExtGtkCenterBox::getCenterWidget($handle);
}

function gtk_center_box_get_end_widget(int $handle): int
{
    return ExtGtkCenterBox::getEndWidget($handle);
}

function gtk_center_box_get_shrink_center_last(int $handle): bool
{
    return ExtGtkCenterBox::getShrinkCenterLast($handle);
}

function gtk_center_box_get_start_widget(int $handle): int
{
    return ExtGtkCenterBox::getStartWidget($handle);
}

function gtk_center_box_set_baseline_position(int $handle, int $position): void
{
    ExtGtkCenterBox::setBaselinePosition($handle, $position);
}

function gtk_center_box_set_center_widget(int $handle, int $child): void
{
    ExtGtkCenterBox::setCenterWidget($handle, $child);
}

function gtk_center_box_set_end_widget(int $handle, int $child): void
{
    ExtGtkCenterBox::setEndWidget($handle, $child);
}

function gtk_center_box_set_shrink_center_last(int $handle, bool $shrinkCenterLast): void
{
    ExtGtkCenterBox::setShrinkCenterLast($handle, $shrinkCenterLast);
}

function gtk_center_box_set_start_widget(int $handle, int $child): void
{
    ExtGtkCenterBox::setStartWidget($handle, $child);
}
