<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkSpinner\GtkSpinner as ExtGtkSpinner;

function gtk_spinner_new(): int
{
    return ExtGtkSpinner::new_();
}

function gtk_spinner_get_spinning(int $handle): bool
{
    return ExtGtkSpinner::getSpinning($handle);
}

function gtk_spinner_set_spinning(int $handle, bool $spinning): void
{
    ExtGtkSpinner::setSpinning($handle, $spinning);
}

function gtk_spinner_start(int $handle): void
{
    ExtGtkSpinner::start($handle);
}

function gtk_spinner_stop(int $handle): void
{
    ExtGtkSpinner::stop($handle);
}
