<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkDropDown\GtkDropDown as ExtGtkDropDown;

function gtk_drop_down_new(int $model): int
{
    return ExtGtkDropDown::new_($model);
}

function gtk_drop_down_new_from_strings(array $strings): int
{
    return ExtGtkDropDown::newFromStrings($strings);
}

function gtk_drop_down_get_enable_search(int $handle): bool
{
    return ExtGtkDropDown::getEnableSearch($handle);
}

function gtk_drop_down_get_factory(int $handle): int
{
    return ExtGtkDropDown::getFactory($handle);
}

function gtk_drop_down_get_header_factory(int $handle): int
{
    return ExtGtkDropDown::getHeaderFactory($handle);
}

function gtk_drop_down_get_list_factory(int $handle): int
{
    return ExtGtkDropDown::getListFactory($handle);
}

function gtk_drop_down_get_model(int $handle): int
{
    return ExtGtkDropDown::getModel($handle);
}

function gtk_drop_down_get_search_match_mode(int $handle): int
{
    return ExtGtkDropDown::getSearchMatchMode($handle);
}

function gtk_drop_down_get_selected(int $handle): int
{
    return ExtGtkDropDown::getSelected($handle);
}

function gtk_drop_down_get_selected_item(int $handle): int
{
    return ExtGtkDropDown::getSelectedItem($handle);
}

function gtk_drop_down_get_show_arrow(int $handle): bool
{
    return ExtGtkDropDown::getShowArrow($handle);
}

function gtk_drop_down_set_enable_search(int $handle, bool $enableSearch): void
{
    ExtGtkDropDown::setEnableSearch($handle, $enableSearch);
}

function gtk_drop_down_set_factory(int $handle, int $factory): void
{
    ExtGtkDropDown::setFactory($handle, $factory);
}

function gtk_drop_down_set_header_factory(int $handle, int $factory): void
{
    ExtGtkDropDown::setHeaderFactory($handle, $factory);
}

function gtk_drop_down_set_list_factory(int $handle, int $factory): void
{
    ExtGtkDropDown::setListFactory($handle, $factory);
}

function gtk_drop_down_set_model(int $handle, int $model): void
{
    ExtGtkDropDown::setModel($handle, $model);
}

function gtk_drop_down_set_search_match_mode(int $handle, int $searchMatchMode): void
{
    ExtGtkDropDown::setSearchMatchMode($handle, $searchMatchMode);
}

function gtk_drop_down_set_selected(int $handle, int $position): void
{
    ExtGtkDropDown::setSelected($handle, $position);
}

function gtk_drop_down_set_show_arrow(int $handle, bool $showArrow): void
{
    ExtGtkDropDown::setShowArrow($handle, $showArrow);
}
