<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkSingleSelection\GtkSingleSelection as ExtGtkSingleSelection;

function gtk_single_selection_new(int $model): int
{
    return ExtGtkSingleSelection::new_($model);
}

function gtk_single_selection_get_autoselect(int $handle): bool
{
    return ExtGtkSingleSelection::getAutoselect($handle);
}

function gtk_single_selection_get_can_unselect(int $handle): bool
{
    return ExtGtkSingleSelection::getCanUnselect($handle);
}

function gtk_single_selection_get_model(int $handle): int
{
    return ExtGtkSingleSelection::getModel($handle);
}

function gtk_single_selection_get_selected(int $handle): int
{
    return ExtGtkSingleSelection::getSelected($handle);
}

function gtk_single_selection_get_selected_item(int $handle): int
{
    return ExtGtkSingleSelection::getSelectedItem($handle);
}

function gtk_single_selection_set_autoselect(int $handle, bool $autoselect): void
{
    ExtGtkSingleSelection::setAutoselect($handle, $autoselect);
}

function gtk_single_selection_set_can_unselect(int $handle, bool $canUnselect): void
{
    ExtGtkSingleSelection::setCanUnselect($handle, $canUnselect);
}

function gtk_single_selection_set_model(int $handle, int $model): void
{
    ExtGtkSingleSelection::setModel($handle, $model);
}

function gtk_single_selection_set_selected(int $handle, int $position): void
{
    ExtGtkSingleSelection::setSelected($handle, $position);
}
