<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkTextMark\GtkTextMark as ExtGtkTextMark;

function gtk_text_mark_new(mixed $name, bool $leftGravity): int
{
    return ExtGtkTextMark::new_($name, $leftGravity);
}

function gtk_text_mark_get_buffer(int $handle): int
{
    return ExtGtkTextMark::getBuffer($handle);
}

function gtk_text_mark_get_deleted(int $handle): bool
{
    return ExtGtkTextMark::getDeleted($handle);
}

function gtk_text_mark_get_left_gravity(int $handle): bool
{
    return ExtGtkTextMark::getLeftGravity($handle);
}

function gtk_text_mark_get_name(int $handle): mixed
{
    return ExtGtkTextMark::getName($handle);
}

function gtk_text_mark_get_visible(int $handle): bool
{
    return ExtGtkTextMark::getVisible($handle);
}

function gtk_text_mark_set_visible(int $handle, bool $setting): void
{
    ExtGtkTextMark::setVisible($handle, $setting);
}
