<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkWidget\GtkWidget as ExtGtkWidget;

function gtk_widget_get_default_direction(): int
{
    return ExtGtkWidget::getDefaultDirection();
}

function gtk_widget_set_default_direction(int $dir): void
{
    ExtGtkWidget::setDefaultDirection($dir);
}

function gtk_widget_action_set_enabled(int $handle, string $actionName, bool $enabled): void
{
    ExtGtkWidget::actionSetEnabled($handle, $actionName, $enabled);
}

function gtk_widget_activate(int $handle): bool
{
    return ExtGtkWidget::activate($handle);
}

function gtk_widget_activate_default(int $handle): void
{
    ExtGtkWidget::activateDefault($handle);
}

function gtk_widget_add_controller(int $handle, int $controller): void
{
    ExtGtkWidget::addController($handle, $controller);
}

function gtk_widget_add_css_class(int $handle, string $cssClass): void
{
    ExtGtkWidget::addCssClass($handle, $cssClass);
}

function gtk_widget_add_mnemonic_label(int $handle, int $label): void
{
    ExtGtkWidget::addMnemonicLabel($handle, $label);
}

function gtk_widget_child_focus(int $handle, int $direction): bool
{
    return ExtGtkWidget::childFocus($handle, $direction);
}

function gtk_widget_compute_bounds(int $handle, int $target): mixed
{
    return ExtGtkWidget::computeBounds($handle, $target);
}

function gtk_widget_compute_expand(int $handle, int $orientation): bool
{
    return ExtGtkWidget::computeExpand($handle, $orientation);
}

function gtk_widget_compute_point(int $handle, int $target, float $pointX, float $pointY): mixed
{
    return ExtGtkWidget::computePoint($handle, $target, $pointX, $pointY);
}

function gtk_widget_contains(int $handle, float $x, float $y): bool
{
    return ExtGtkWidget::contains($handle, $x, $y);
}

function gtk_widget_create_pango_context(int $handle): int
{
    return ExtGtkWidget::createPangoContext($handle);
}

function gtk_widget_create_pango_layout(int $handle, mixed $text): int
{
    return ExtGtkWidget::createPangoLayout($handle, $text);
}

function gtk_widget_dispose_template(int $handle, int $widgetType): void
{
    ExtGtkWidget::disposeTemplate($handle, $widgetType);
}

function gtk_drag_check_threshold(int $handle, int $startX, int $startY, int $currentX, int $currentY): bool
{
    return ExtGtkWidget::dragCheckThreshold($handle, $startX, $startY, $currentX, $currentY);
}

function gtk_widget_error_bell(int $handle): void
{
    ExtGtkWidget::errorBell($handle);
}

function gtk_widget_get_ancestor(int $handle, int $widgetType): int
{
    return ExtGtkWidget::getAncestor($handle, $widgetType);
}

function gtk_widget_get_baseline(int $handle): int
{
    return ExtGtkWidget::getBaseline($handle);
}

function gtk_widget_get_can_focus(int $handle): bool
{
    return ExtGtkWidget::getCanFocus($handle);
}

function gtk_widget_get_can_target(int $handle): bool
{
    return ExtGtkWidget::getCanTarget($handle);
}

function gtk_widget_get_child_visible(int $handle): bool
{
    return ExtGtkWidget::getChildVisible($handle);
}

function gtk_widget_get_clipboard(int $handle): int
{
    return ExtGtkWidget::getClipboard($handle);
}

function gtk_widget_get_color(int $handle): array
{
    return ExtGtkWidget::getColor($handle);
}

function gtk_widget_get_css_classes(int $handle): array
{
    return ExtGtkWidget::getCssClasses($handle);
}

function gtk_widget_get_css_name(int $handle): string
{
    return ExtGtkWidget::getCssName($handle);
}

function gtk_widget_get_cursor(int $handle): int
{
    return ExtGtkWidget::getCursor($handle);
}

function gtk_widget_get_direction(int $handle): int
{
    return ExtGtkWidget::getDirection($handle);
}

function gtk_widget_get_display(int $handle): int
{
    return ExtGtkWidget::getDisplay($handle);
}

function gtk_widget_get_first_child(int $handle): int
{
    return ExtGtkWidget::getFirstChild($handle);
}

function gtk_widget_get_focus_child(int $handle): int
{
    return ExtGtkWidget::getFocusChild($handle);
}

function gtk_widget_get_focus_on_click(int $handle): bool
{
    return ExtGtkWidget::getFocusOnClick($handle);
}

function gtk_widget_get_focusable(int $handle): bool
{
    return ExtGtkWidget::getFocusable($handle);
}

function gtk_widget_get_font_map(int $handle): int
{
    return ExtGtkWidget::getFontMap($handle);
}

function gtk_widget_get_frame_clock(int $handle): int
{
    return ExtGtkWidget::getFrameClock($handle);
}

function gtk_widget_get_halign(int $handle): int
{
    return ExtGtkWidget::getHalign($handle);
}

function gtk_widget_get_has_tooltip(int $handle): bool
{
    return ExtGtkWidget::getHasTooltip($handle);
}

function gtk_widget_get_height(int $handle): int
{
    return ExtGtkWidget::getHeight($handle);
}

function gtk_widget_get_hexpand(int $handle): bool
{
    return ExtGtkWidget::getHexpand($handle);
}

function gtk_widget_get_hexpand_set(int $handle): bool
{
    return ExtGtkWidget::getHexpandSet($handle);
}

function gtk_widget_get_last_child(int $handle): int
{
    return ExtGtkWidget::getLastChild($handle);
}

function gtk_widget_get_layout_manager(int $handle): int
{
    return ExtGtkWidget::getLayoutManager($handle);
}

function gtk_widget_get_limit_events(int $handle): bool
{
    return ExtGtkWidget::getLimitEvents($handle);
}

function gtk_widget_get_mapped(int $handle): bool
{
    return ExtGtkWidget::getMapped($handle);
}

function gtk_widget_get_margin_bottom(int $handle): int
{
    return ExtGtkWidget::getMarginBottom($handle);
}

function gtk_widget_get_margin_end(int $handle): int
{
    return ExtGtkWidget::getMarginEnd($handle);
}

function gtk_widget_get_margin_start(int $handle): int
{
    return ExtGtkWidget::getMarginStart($handle);
}

function gtk_widget_get_margin_top(int $handle): int
{
    return ExtGtkWidget::getMarginTop($handle);
}

function gtk_widget_get_name(int $handle): string
{
    return ExtGtkWidget::getName($handle);
}

function gtk_widget_get_native(int $handle): int
{
    return ExtGtkWidget::getNative($handle);
}

function gtk_widget_get_next_sibling(int $handle): int
{
    return ExtGtkWidget::getNextSibling($handle);
}

function gtk_widget_get_opacity(int $handle): float
{
    return ExtGtkWidget::getOpacity($handle);
}

function gtk_widget_get_overflow(int $handle): int
{
    return ExtGtkWidget::getOverflow($handle);
}

function gtk_widget_get_pango_context(int $handle): int
{
    return ExtGtkWidget::getPangoContext($handle);
}

function gtk_widget_get_parent(int $handle): int
{
    return ExtGtkWidget::getParent($handle);
}

function gtk_widget_get_preferred_size(int $handle): array
{
    return ExtGtkWidget::getPreferredSize($handle);
}

function gtk_widget_get_prev_sibling(int $handle): int
{
    return ExtGtkWidget::getPrevSibling($handle);
}

function gtk_widget_get_primary_clipboard(int $handle): int
{
    return ExtGtkWidget::getPrimaryClipboard($handle);
}

function gtk_widget_get_realized(int $handle): bool
{
    return ExtGtkWidget::getRealized($handle);
}

function gtk_widget_get_receives_default(int $handle): bool
{
    return ExtGtkWidget::getReceivesDefault($handle);
}

function gtk_widget_get_request_mode(int $handle): int
{
    return ExtGtkWidget::getRequestMode($handle);
}

function gtk_widget_get_root(int $handle): int
{
    return ExtGtkWidget::getRoot($handle);
}

function gtk_widget_get_scale_factor(int $handle): int
{
    return ExtGtkWidget::getScaleFactor($handle);
}

function gtk_widget_get_sensitive(int $handle): bool
{
    return ExtGtkWidget::getSensitive($handle);
}

function gtk_widget_get_settings(int $handle): int
{
    return ExtGtkWidget::getSettings($handle);
}

function gtk_widget_get_size(int $handle, int $orientation): int
{
    return ExtGtkWidget::getSize($handle, $orientation);
}

function gtk_widget_get_size_request(int $handle): array
{
    return ExtGtkWidget::getSizeRequest($handle);
}

function gtk_widget_get_state_flags(int $handle): int
{
    return ExtGtkWidget::getStateFlags($handle);
}

function gtk_widget_get_template_child(int $handle, int $widgetType, string $name): int
{
    return ExtGtkWidget::getTemplateChild($handle, $widgetType, $name);
}

function gtk_widget_get_tooltip_markup(int $handle): mixed
{
    return ExtGtkWidget::getTooltipMarkup($handle);
}

function gtk_widget_get_tooltip_text(int $handle): mixed
{
    return ExtGtkWidget::getTooltipText($handle);
}

function gtk_widget_get_valign(int $handle): int
{
    return ExtGtkWidget::getValign($handle);
}

function gtk_widget_get_vexpand(int $handle): bool
{
    return ExtGtkWidget::getVexpand($handle);
}

function gtk_widget_get_vexpand_set(int $handle): bool
{
    return ExtGtkWidget::getVexpandSet($handle);
}

function gtk_widget_get_visible(int $handle): bool
{
    return ExtGtkWidget::getVisible($handle);
}

function gtk_widget_get_width(int $handle): int
{
    return ExtGtkWidget::getWidth($handle);
}

function gtk_widget_grab_focus(int $handle): bool
{
    return ExtGtkWidget::grabFocus($handle);
}

function gtk_widget_has_css_class(int $handle, string $cssClass): bool
{
    return ExtGtkWidget::hasCssClass($handle, $cssClass);
}

function gtk_widget_has_default(int $handle): bool
{
    return ExtGtkWidget::hasDefault($handle);
}

function gtk_widget_has_focus(int $handle): bool
{
    return ExtGtkWidget::hasFocus($handle);
}

function gtk_widget_has_visible_focus(int $handle): bool
{
    return ExtGtkWidget::hasVisibleFocus($handle);
}

function gtk_widget_in_destruction(int $handle): bool
{
    return ExtGtkWidget::inDestruction($handle);
}

function gtk_widget_init_template(int $handle): void
{
    ExtGtkWidget::initTemplate($handle);
}

function gtk_widget_insert_action_group(int $handle, string $name, int $group): void
{
    ExtGtkWidget::insertActionGroup($handle, $name, $group);
}

function gtk_widget_insert_after(int $handle, int $parent, int $previousSibling): void
{
    ExtGtkWidget::insertAfter($handle, $parent, $previousSibling);
}

function gtk_widget_insert_before(int $handle, int $parent, int $nextSibling): void
{
    ExtGtkWidget::insertBefore($handle, $parent, $nextSibling);
}

function gtk_widget_is_ancestor(int $handle, int $ancestor): bool
{
    return ExtGtkWidget::isAncestor($handle, $ancestor);
}

function gtk_widget_is_drawable(int $handle): bool
{
    return ExtGtkWidget::isDrawable($handle);
}

function gtk_widget_is_focus(int $handle): bool
{
    return ExtGtkWidget::isFocus($handle);
}

function gtk_widget_is_sensitive(int $handle): bool
{
    return ExtGtkWidget::isSensitive($handle);
}

function gtk_widget_is_visible(int $handle): bool
{
    return ExtGtkWidget::isVisible($handle);
}

function gtk_widget_keynav_failed(int $handle, int $direction): bool
{
    return ExtGtkWidget::keynavFailed($handle, $direction);
}

function gtk_widget_list_mnemonic_labels(int $handle): array
{
    return ExtGtkWidget::listMnemonicLabels($handle);
}

function gtk_widget_map(int $handle): void
{
    ExtGtkWidget::map($handle);
}

function gtk_widget_measure(int $handle, int $orientation, int $forSize): array
{
    return ExtGtkWidget::measure($handle, $orientation, $forSize);
}

function gtk_widget_mnemonic_activate(int $handle, bool $groupCycling): bool
{
    return ExtGtkWidget::mnemonicActivate($handle, $groupCycling);
}

function gtk_widget_observe_children(int $handle): int
{
    return ExtGtkWidget::observeChildren($handle);
}

function gtk_widget_observe_controllers(int $handle): int
{
    return ExtGtkWidget::observeControllers($handle);
}

function gtk_widget_pick(int $handle, float $x, float $y, int $flags): int
{
    return ExtGtkWidget::pick($handle, $x, $y, $flags);
}

function gtk_widget_queue_allocate(int $handle): void
{
    ExtGtkWidget::queueAllocate($handle);
}

function gtk_widget_queue_draw(int $handle): void
{
    ExtGtkWidget::queueDraw($handle);
}

function gtk_widget_queue_resize(int $handle): void
{
    ExtGtkWidget::queueResize($handle);
}

function gtk_widget_realize(int $handle): void
{
    ExtGtkWidget::realize($handle);
}

function gtk_widget_remove_controller(int $handle, int $controller): void
{
    ExtGtkWidget::removeController($handle, $controller);
}

function gtk_widget_remove_css_class(int $handle, string $cssClass): void
{
    ExtGtkWidget::removeCssClass($handle, $cssClass);
}

function gtk_widget_remove_mnemonic_label(int $handle, int $label): void
{
    ExtGtkWidget::removeMnemonicLabel($handle, $label);
}

function gtk_widget_remove_tick_callback(int $handle, int $id): void
{
    ExtGtkWidget::removeTickCallback($handle, $id);
}

function gtk_widget_set_can_focus(int $handle, bool $canFocus): void
{
    ExtGtkWidget::setCanFocus($handle, $canFocus);
}

function gtk_widget_set_can_target(int $handle, bool $canTarget): void
{
    ExtGtkWidget::setCanTarget($handle, $canTarget);
}

function gtk_widget_set_child_visible(int $handle, bool $childVisible): void
{
    ExtGtkWidget::setChildVisible($handle, $childVisible);
}

function gtk_widget_set_css_classes(int $handle, array $classes): void
{
    ExtGtkWidget::setCssClasses($handle, $classes);
}

function gtk_widget_set_cursor(int $handle, int $cursor): void
{
    ExtGtkWidget::setCursor($handle, $cursor);
}

function gtk_widget_set_cursor_from_name(int $handle, mixed $name): void
{
    ExtGtkWidget::setCursorFromName($handle, $name);
}

function gtk_widget_set_direction(int $handle, int $dir): void
{
    ExtGtkWidget::setDirection($handle, $dir);
}

function gtk_widget_set_focus_child(int $handle, int $child): void
{
    ExtGtkWidget::setFocusChild($handle, $child);
}

function gtk_widget_set_focus_on_click(int $handle, bool $focusOnClick): void
{
    ExtGtkWidget::setFocusOnClick($handle, $focusOnClick);
}

function gtk_widget_set_focusable(int $handle, bool $focusable): void
{
    ExtGtkWidget::setFocusable($handle, $focusable);
}

function gtk_widget_set_font_map(int $handle, int $fontMap): void
{
    ExtGtkWidget::setFontMap($handle, $fontMap);
}

function gtk_widget_set_halign(int $handle, int $align): void
{
    ExtGtkWidget::setHalign($handle, $align);
}

function gtk_widget_set_has_tooltip(int $handle, bool $hasTooltip): void
{
    ExtGtkWidget::setHasTooltip($handle, $hasTooltip);
}

function gtk_widget_set_hexpand(int $handle, bool $expand): void
{
    ExtGtkWidget::setHexpand($handle, $expand);
}

function gtk_widget_set_hexpand_set(int $handle, bool $set): void
{
    ExtGtkWidget::setHexpandSet($handle, $set);
}

function gtk_widget_set_layout_manager(int $handle, int $layoutManager): void
{
    ExtGtkWidget::setLayoutManager($handle, $layoutManager);
}

function gtk_widget_set_limit_events(int $handle, bool $limitEvents): void
{
    ExtGtkWidget::setLimitEvents($handle, $limitEvents);
}

function gtk_widget_set_margin_bottom(int $handle, int $margin): void
{
    ExtGtkWidget::setMarginBottom($handle, $margin);
}

function gtk_widget_set_margin_end(int $handle, int $margin): void
{
    ExtGtkWidget::setMarginEnd($handle, $margin);
}

function gtk_widget_set_margin_start(int $handle, int $margin): void
{
    ExtGtkWidget::setMarginStart($handle, $margin);
}

function gtk_widget_set_margin_top(int $handle, int $margin): void
{
    ExtGtkWidget::setMarginTop($handle, $margin);
}

function gtk_widget_set_name(int $handle, string $name): void
{
    ExtGtkWidget::setName($handle, $name);
}

function gtk_widget_set_opacity(int $handle, float $opacity): void
{
    ExtGtkWidget::setOpacity($handle, $opacity);
}

function gtk_widget_set_overflow(int $handle, int $overflow): void
{
    ExtGtkWidget::setOverflow($handle, $overflow);
}

function gtk_widget_set_parent(int $handle, int $parent): void
{
    ExtGtkWidget::setParent($handle, $parent);
}

function gtk_widget_set_receives_default(int $handle, bool $receivesDefault): void
{
    ExtGtkWidget::setReceivesDefault($handle, $receivesDefault);
}

function gtk_widget_set_sensitive(int $handle, bool $sensitive): void
{
    ExtGtkWidget::setSensitive($handle, $sensitive);
}

function gtk_widget_set_size_request(int $handle, int $width, int $height): void
{
    ExtGtkWidget::setSizeRequest($handle, $width, $height);
}

function gtk_widget_set_state_flags(int $handle, int $flags, bool $clear): void
{
    ExtGtkWidget::setStateFlags($handle, $flags, $clear);
}

function gtk_widget_set_tooltip_markup(int $handle, mixed $markup): void
{
    ExtGtkWidget::setTooltipMarkup($handle, $markup);
}

function gtk_widget_set_tooltip_text(int $handle, mixed $text): void
{
    ExtGtkWidget::setTooltipText($handle, $text);
}

function gtk_widget_set_valign(int $handle, int $align): void
{
    ExtGtkWidget::setValign($handle, $align);
}

function gtk_widget_set_vexpand(int $handle, bool $expand): void
{
    ExtGtkWidget::setVexpand($handle, $expand);
}

function gtk_widget_set_vexpand_set(int $handle, bool $set): void
{
    ExtGtkWidget::setVexpandSet($handle, $set);
}

function gtk_widget_set_visible(int $handle, bool $visible): void
{
    ExtGtkWidget::setVisible($handle, $visible);
}

function gtk_widget_should_layout(int $handle): bool
{
    return ExtGtkWidget::shouldLayout($handle);
}

function gtk_widget_size_allocate(int $handle, int $allocationX, int $allocationY, int $allocationWidth, int $allocationHeight, int $baseline): void
{
    ExtGtkWidget::sizeAllocate($handle, $allocationX, $allocationY, $allocationWidth, $allocationHeight, $baseline);
}

function gtk_widget_snapshot_child(int $handle, int $child, int $snapshot): void
{
    ExtGtkWidget::snapshotChild($handle, $child, $snapshot);
}

function gtk_widget_trigger_tooltip_query(int $handle): void
{
    ExtGtkWidget::triggerTooltipQuery($handle);
}

function gtk_widget_unmap(int $handle): void
{
    ExtGtkWidget::unmap($handle);
}

function gtk_widget_unparent(int $handle): void
{
    ExtGtkWidget::unparent($handle);
}

function gtk_widget_unrealize(int $handle): void
{
    ExtGtkWidget::unrealize($handle);
}

function gtk_widget_unset_state_flags(int $handle, int $flags): void
{
    ExtGtkWidget::unsetStateFlags($handle, $flags);
}
