<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkListBox\GtkListBox as ExtGtkListBox;

function gtk_list_box_new(): int
{
    return ExtGtkListBox::new_();
}

function gtk_list_box_append(int $handle, int $child): void
{
    ExtGtkListBox::append($handle, $child);
}

function gtk_list_box_drag_highlight_row(int $handle, int $row): void
{
    ExtGtkListBox::dragHighlightRow($handle, $row);
}

function gtk_list_box_drag_unhighlight_row(int $handle): void
{
    ExtGtkListBox::dragUnhighlightRow($handle);
}

function gtk_list_box_get_activate_on_single_click(int $handle): bool
{
    return ExtGtkListBox::getActivateOnSingleClick($handle);
}

function gtk_list_box_get_adjustment(int $handle): int
{
    return ExtGtkListBox::getAdjustment($handle);
}

function gtk_list_box_get_row_at_index(int $handle, int $index): int
{
    return ExtGtkListBox::getRowAtIndex($handle, $index);
}

function gtk_list_box_get_row_at_y(int $handle, int $y): int
{
    return ExtGtkListBox::getRowAtY($handle, $y);
}

function gtk_list_box_get_selected_row(int $handle): int
{
    return ExtGtkListBox::getSelectedRow($handle);
}

function gtk_list_box_get_selected_rows(int $handle): array
{
    return ExtGtkListBox::getSelectedRows($handle);
}

function gtk_list_box_get_selection_mode(int $handle): int
{
    return ExtGtkListBox::getSelectionMode($handle);
}

function gtk_list_box_get_show_separators(int $handle): bool
{
    return ExtGtkListBox::getShowSeparators($handle);
}

function gtk_list_box_get_tab_behavior(int $handle): int
{
    return ExtGtkListBox::getTabBehavior($handle);
}

function gtk_list_box_insert(int $handle, int $child, int $position): void
{
    ExtGtkListBox::insert($handle, $child, $position);
}

function gtk_list_box_invalidate_filter(int $handle): void
{
    ExtGtkListBox::invalidateFilter($handle);
}

function gtk_list_box_invalidate_headers(int $handle): void
{
    ExtGtkListBox::invalidateHeaders($handle);
}

function gtk_list_box_invalidate_sort(int $handle): void
{
    ExtGtkListBox::invalidateSort($handle);
}

function gtk_list_box_prepend(int $handle, int $child): void
{
    ExtGtkListBox::prepend($handle, $child);
}

function gtk_list_box_remove(int $handle, int $child): void
{
    ExtGtkListBox::remove($handle, $child);
}

function gtk_list_box_remove_all(int $handle): void
{
    ExtGtkListBox::removeAll($handle);
}

function gtk_list_box_select_all(int $handle): void
{
    ExtGtkListBox::selectAll($handle);
}

function gtk_list_box_select_row(int $handle, int $row): void
{
    ExtGtkListBox::selectRow($handle, $row);
}

function gtk_list_box_set_activate_on_single_click(int $handle, bool $single): void
{
    ExtGtkListBox::setActivateOnSingleClick($handle, $single);
}

function gtk_list_box_set_adjustment(int $handle, int $adjustment): void
{
    ExtGtkListBox::setAdjustment($handle, $adjustment);
}

function gtk_list_box_set_placeholder(int $handle, int $placeholder): void
{
    ExtGtkListBox::setPlaceholder($handle, $placeholder);
}

function gtk_list_box_set_selection_mode(int $handle, int $mode): void
{
    ExtGtkListBox::setSelectionMode($handle, $mode);
}

function gtk_list_box_set_show_separators(int $handle, bool $showSeparators): void
{
    ExtGtkListBox::setShowSeparators($handle, $showSeparators);
}

function gtk_list_box_set_tab_behavior(int $handle, int $behavior): void
{
    ExtGtkListBox::setTabBehavior($handle, $behavior);
}

function gtk_list_box_unselect_all(int $handle): void
{
    ExtGtkListBox::unselectAll($handle);
}

function gtk_list_box_unselect_row(int $handle, int $row): void
{
    ExtGtkListBox::unselectRow($handle, $row);
}
