<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkSeparator\GtkSeparator as ExtGtkSeparator;

function gtk_separator_new(int $orientation): int
{
    return ExtGtkSeparator::new_($orientation);
}
