<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkStringObject\GtkStringObject as ExtGtkStringObject;

function gtk_string_object_new(string $string_): int
{
    return ExtGtkStringObject::new_($string_);
}

function gtk_string_object_get_string(int $handle): mixed
{
    return ExtGtkStringObject::getString($handle);
}
