<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkGrid\GtkGrid as ExtGtkGrid;

function gtk_grid_new(): int
{
    return ExtGtkGrid::new_();
}

function gtk_grid_attach(int $handle, int $child, int $column, int $row, int $width, int $height): void
{
    ExtGtkGrid::attach($handle, $child, $column, $row, $width, $height);
}

function gtk_grid_attach_next_to(int $handle, int $child, int $sibling, int $side, int $width, int $height): void
{
    ExtGtkGrid::attachNextTo($handle, $child, $sibling, $side, $width, $height);
}

function gtk_grid_get_baseline_row(int $handle): int
{
    return ExtGtkGrid::getBaselineRow($handle);
}

function gtk_grid_get_child_at(int $handle, int $column, int $row): int
{
    return ExtGtkGrid::getChildAt($handle, $column, $row);
}

function gtk_grid_get_column_homogeneous(int $handle): bool
{
    return ExtGtkGrid::getColumnHomogeneous($handle);
}

function gtk_grid_get_column_spacing(int $handle): int
{
    return ExtGtkGrid::getColumnSpacing($handle);
}

function gtk_grid_get_row_baseline_position(int $handle, int $row): int
{
    return ExtGtkGrid::getRowBaselinePosition($handle, $row);
}

function gtk_grid_get_row_homogeneous(int $handle): bool
{
    return ExtGtkGrid::getRowHomogeneous($handle);
}

function gtk_grid_get_row_spacing(int $handle): int
{
    return ExtGtkGrid::getRowSpacing($handle);
}

function gtk_grid_insert_column(int $handle, int $position): void
{
    ExtGtkGrid::insertColumn($handle, $position);
}

function gtk_grid_insert_next_to(int $handle, int $sibling, int $side): void
{
    ExtGtkGrid::insertNextTo($handle, $sibling, $side);
}

function gtk_grid_insert_row(int $handle, int $position): void
{
    ExtGtkGrid::insertRow($handle, $position);
}

function gtk_grid_query_child(int $handle, int $child): array
{
    return ExtGtkGrid::queryChild($handle, $child);
}

function gtk_grid_remove(int $handle, int $child): void
{
    ExtGtkGrid::remove($handle, $child);
}

function gtk_grid_remove_column(int $handle, int $position): void
{
    ExtGtkGrid::removeColumn($handle, $position);
}

function gtk_grid_remove_row(int $handle, int $position): void
{
    ExtGtkGrid::removeRow($handle, $position);
}

function gtk_grid_set_baseline_row(int $handle, int $row): void
{
    ExtGtkGrid::setBaselineRow($handle, $row);
}

function gtk_grid_set_column_homogeneous(int $handle, bool $homogeneous): void
{
    ExtGtkGrid::setColumnHomogeneous($handle, $homogeneous);
}

function gtk_grid_set_column_spacing(int $handle, int $spacing): void
{
    ExtGtkGrid::setColumnSpacing($handle, $spacing);
}

function gtk_grid_set_row_baseline_position(int $handle, int $row, int $pos): void
{
    ExtGtkGrid::setRowBaselinePosition($handle, $row, $pos);
}

function gtk_grid_set_row_homogeneous(int $handle, bool $homogeneous): void
{
    ExtGtkGrid::setRowHomogeneous($handle, $homogeneous);
}

function gtk_grid_set_row_spacing(int $handle, int $spacing): void
{
    ExtGtkGrid::setRowSpacing($handle, $spacing);
}
