<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkWindowControls\GtkWindowControls as ExtGtkWindowControls;

function gtk_window_controls_new(int $side): int
{
    return ExtGtkWindowControls::new_($side);
}

function gtk_window_controls_get_decoration_layout(int $handle): mixed
{
    return ExtGtkWindowControls::getDecorationLayout($handle);
}

function gtk_window_controls_get_empty(int $handle): bool
{
    return ExtGtkWindowControls::getEmpty($handle);
}

function gtk_window_controls_get_side(int $handle): int
{
    return ExtGtkWindowControls::getSide($handle);
}

function gtk_window_controls_get_use_native_controls(int $handle): bool
{
    return ExtGtkWindowControls::getUseNativeControls($handle);
}

function gtk_window_controls_set_decoration_layout(int $handle, mixed $layout): void
{
    ExtGtkWindowControls::setDecorationLayout($handle, $layout);
}

function gtk_window_controls_set_side(int $handle, int $side): void
{
    ExtGtkWindowControls::setSide($handle, $side);
}

function gtk_window_controls_set_use_native_controls(int $handle, bool $setting): void
{
    ExtGtkWindowControls::setUseNativeControls($handle, $setting);
}
