<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkPopoverMenuBar\GtkPopoverMenuBar as ExtGtkPopoverMenuBar;

function gtk_popover_menu_bar_new_from_model(int $model): int
{
    return ExtGtkPopoverMenuBar::newFromModel($model);
}

function gtk_popover_menu_bar_add_child(int $handle, int $child, string $id): bool
{
    return ExtGtkPopoverMenuBar::addChild($handle, $child, $id);
}

function gtk_popover_menu_bar_get_menu_model(int $handle): int
{
    return ExtGtkPopoverMenuBar::getMenuModel($handle);
}

function gtk_popover_menu_bar_remove_child(int $handle, int $child): bool
{
    return ExtGtkPopoverMenuBar::removeChild($handle, $child);
}

function gtk_popover_menu_bar_set_menu_model(int $handle, int $model): void
{
    ExtGtkPopoverMenuBar::setMenuModel($handle, $model);
}
