<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkMediaStream\GtkMediaStream as ExtGtkMediaStream;

function gtk_media_stream_get_duration(int $handle): int
{
    return ExtGtkMediaStream::getDuration($handle);
}

function gtk_media_stream_get_ended(int $handle): bool
{
    return ExtGtkMediaStream::getEnded($handle);
}

function gtk_media_stream_get_loop(int $handle): bool
{
    return ExtGtkMediaStream::getLoop($handle);
}

function gtk_media_stream_get_muted(int $handle): bool
{
    return ExtGtkMediaStream::getMuted($handle);
}

function gtk_media_stream_get_playing(int $handle): bool
{
    return ExtGtkMediaStream::getPlaying($handle);
}

function gtk_media_stream_get_timestamp(int $handle): int
{
    return ExtGtkMediaStream::getTimestamp($handle);
}

function gtk_media_stream_get_volume(int $handle): float
{
    return ExtGtkMediaStream::getVolume($handle);
}

function gtk_media_stream_has_audio(int $handle): bool
{
    return ExtGtkMediaStream::hasAudio($handle);
}

function gtk_media_stream_has_video(int $handle): bool
{
    return ExtGtkMediaStream::hasVideo($handle);
}

function gtk_media_stream_is_prepared(int $handle): bool
{
    return ExtGtkMediaStream::isPrepared($handle);
}

function gtk_media_stream_is_seekable(int $handle): bool
{
    return ExtGtkMediaStream::isSeekable($handle);
}

function gtk_media_stream_is_seeking(int $handle): bool
{
    return ExtGtkMediaStream::isSeeking($handle);
}

function gtk_media_stream_pause(int $handle): void
{
    ExtGtkMediaStream::pause($handle);
}

function gtk_media_stream_play(int $handle): void
{
    ExtGtkMediaStream::play($handle);
}

function gtk_media_stream_realize(int $handle, int $surface): void
{
    ExtGtkMediaStream::realize($handle, $surface);
}

function gtk_media_stream_seek(int $handle, int $timestamp): void
{
    ExtGtkMediaStream::seek($handle, $timestamp);
}

function gtk_media_stream_seek_failed(int $handle): void
{
    ExtGtkMediaStream::seekFailed($handle);
}

function gtk_media_stream_seek_success(int $handle): void
{
    ExtGtkMediaStream::seekSuccess($handle);
}

function gtk_media_stream_set_loop(int $handle, bool $loop_): void
{
    ExtGtkMediaStream::setLoop($handle, $loop_);
}

function gtk_media_stream_set_muted(int $handle, bool $muted): void
{
    ExtGtkMediaStream::setMuted($handle, $muted);
}

function gtk_media_stream_set_playing(int $handle, bool $playing): void
{
    ExtGtkMediaStream::setPlaying($handle, $playing);
}

function gtk_media_stream_set_volume(int $handle, float $volume): void
{
    ExtGtkMediaStream::setVolume($handle, $volume);
}

function gtk_media_stream_stream_ended(int $handle): void
{
    ExtGtkMediaStream::streamEnded($handle);
}

function gtk_media_stream_stream_prepared(int $handle, bool $hasAudio, bool $hasVideo, bool $seekable, int $duration): void
{
    ExtGtkMediaStream::streamPrepared($handle, $hasAudio, $hasVideo, $seekable, $duration);
}

function gtk_media_stream_stream_unprepared(int $handle): void
{
    ExtGtkMediaStream::streamUnprepared($handle);
}

function gtk_media_stream_unrealize(int $handle, int $surface): void
{
    ExtGtkMediaStream::unrealize($handle, $surface);
}

function gtk_media_stream_update(int $handle, int $timestamp): void
{
    ExtGtkMediaStream::update($handle, $timestamp);
}
