<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkPaned\GtkPaned as ExtGtkPaned;

function gtk_paned_new(int $orientation): int
{
    return ExtGtkPaned::new_($orientation);
}

function gtk_paned_get_end_child(int $handle): int
{
    return ExtGtkPaned::getEndChild($handle);
}

function gtk_paned_get_position(int $handle): int
{
    return ExtGtkPaned::getPosition($handle);
}

function gtk_paned_get_resize_end_child(int $handle): bool
{
    return ExtGtkPaned::getResizeEndChild($handle);
}

function gtk_paned_get_resize_start_child(int $handle): bool
{
    return ExtGtkPaned::getResizeStartChild($handle);
}

function gtk_paned_get_shrink_end_child(int $handle): bool
{
    return ExtGtkPaned::getShrinkEndChild($handle);
}

function gtk_paned_get_shrink_start_child(int $handle): bool
{
    return ExtGtkPaned::getShrinkStartChild($handle);
}

function gtk_paned_get_start_child(int $handle): int
{
    return ExtGtkPaned::getStartChild($handle);
}

function gtk_paned_get_wide_handle(int $handle): bool
{
    return ExtGtkPaned::getWideHandle($handle);
}

function gtk_paned_set_end_child(int $handle, int $child): void
{
    ExtGtkPaned::setEndChild($handle, $child);
}

function gtk_paned_set_position(int $handle, int $position): void
{
    ExtGtkPaned::setPosition($handle, $position);
}

function gtk_paned_set_resize_end_child(int $handle, bool $resize): void
{
    ExtGtkPaned::setResizeEndChild($handle, $resize);
}

function gtk_paned_set_resize_start_child(int $handle, bool $resize): void
{
    ExtGtkPaned::setResizeStartChild($handle, $resize);
}

function gtk_paned_set_shrink_end_child(int $handle, bool $resize): void
{
    ExtGtkPaned::setShrinkEndChild($handle, $resize);
}

function gtk_paned_set_shrink_start_child(int $handle, bool $resize): void
{
    ExtGtkPaned::setShrinkStartChild($handle, $resize);
}

function gtk_paned_set_start_child(int $handle, int $child): void
{
    ExtGtkPaned::setStartChild($handle, $child);
}

function gtk_paned_set_wide_handle(int $handle, bool $wide): void
{
    ExtGtkPaned::setWideHandle($handle, $wide);
}
