<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkLabel\GtkLabel as ExtGtkLabel;

function gtk_label_new(mixed $str): int
{
    return ExtGtkLabel::new_($str);
}

function gtk_label_new_with_mnemonic(mixed $str): int
{
    return ExtGtkLabel::newWithMnemonic($str);
}

function gtk_label_get_current_uri(int $handle): mixed
{
    return ExtGtkLabel::getCurrentUri($handle);
}

function gtk_label_get_ellipsize(int $handle): int
{
    return ExtGtkLabel::getEllipsize($handle);
}

function gtk_label_get_extra_menu(int $handle): int
{
    return ExtGtkLabel::getExtraMenu($handle);
}

function gtk_label_get_justify(int $handle): int
{
    return ExtGtkLabel::getJustify($handle);
}

function gtk_label_get_label(int $handle): string
{
    return ExtGtkLabel::getLabel($handle);
}

function gtk_label_get_layout(int $handle): int
{
    return ExtGtkLabel::getLayout($handle);
}

function gtk_label_get_layout_offsets(int $handle): array
{
    return ExtGtkLabel::getLayoutOffsets($handle);
}

function gtk_label_get_lines(int $handle): int
{
    return ExtGtkLabel::getLines($handle);
}

function gtk_label_get_max_width_chars(int $handle): int
{
    return ExtGtkLabel::getMaxWidthChars($handle);
}

function gtk_label_get_mnemonic_keyval(int $handle): int
{
    return ExtGtkLabel::getMnemonicKeyval($handle);
}

function gtk_label_get_mnemonic_widget(int $handle): int
{
    return ExtGtkLabel::getMnemonicWidget($handle);
}

function gtk_label_get_natural_wrap_mode(int $handle): int
{
    return ExtGtkLabel::getNaturalWrapMode($handle);
}

function gtk_label_get_selectable(int $handle): bool
{
    return ExtGtkLabel::getSelectable($handle);
}

function gtk_label_get_selection_bounds(int $handle): array
{
    return ExtGtkLabel::getSelectionBounds($handle);
}

function gtk_label_get_single_line_mode(int $handle): bool
{
    return ExtGtkLabel::getSingleLineMode($handle);
}

function gtk_label_get_text(int $handle): string
{
    return ExtGtkLabel::getText($handle);
}

function gtk_label_get_use_markup(int $handle): bool
{
    return ExtGtkLabel::getUseMarkup($handle);
}

function gtk_label_get_use_underline(int $handle): bool
{
    return ExtGtkLabel::getUseUnderline($handle);
}

function gtk_label_get_width_chars(int $handle): int
{
    return ExtGtkLabel::getWidthChars($handle);
}

function gtk_label_get_wrap(int $handle): bool
{
    return ExtGtkLabel::getWrap($handle);
}

function gtk_label_get_wrap_mode(int $handle): int
{
    return ExtGtkLabel::getWrapMode($handle);
}

function gtk_label_get_xalign(int $handle): float
{
    return ExtGtkLabel::getXalign($handle);
}

function gtk_label_get_yalign(int $handle): float
{
    return ExtGtkLabel::getYalign($handle);
}

function gtk_label_select_region(int $handle, int $startOffset, int $endOffset): void
{
    ExtGtkLabel::selectRegion($handle, $startOffset, $endOffset);
}

function gtk_label_set_ellipsize(int $handle, int $mode): void
{
    ExtGtkLabel::setEllipsize($handle, $mode);
}

function gtk_label_set_extra_menu(int $handle, int $model): void
{
    ExtGtkLabel::setExtraMenu($handle, $model);
}

function gtk_label_set_justify(int $handle, int $jtype): void
{
    ExtGtkLabel::setJustify($handle, $jtype);
}

function gtk_label_set_label(int $handle, string $str): void
{
    ExtGtkLabel::setLabel($handle, $str);
}

function gtk_label_set_lines(int $handle, int $lines): void
{
    ExtGtkLabel::setLines($handle, $lines);
}

function gtk_label_set_markup(int $handle, string $str): void
{
    ExtGtkLabel::setMarkup($handle, $str);
}

function gtk_label_set_markup_with_mnemonic(int $handle, string $str): void
{
    ExtGtkLabel::setMarkupWithMnemonic($handle, $str);
}

function gtk_label_set_max_width_chars(int $handle, int $nChars): void
{
    ExtGtkLabel::setMaxWidthChars($handle, $nChars);
}

function gtk_label_set_mnemonic_widget(int $handle, int $widget): void
{
    ExtGtkLabel::setMnemonicWidget($handle, $widget);
}

function gtk_label_set_natural_wrap_mode(int $handle, int $wrapMode): void
{
    ExtGtkLabel::setNaturalWrapMode($handle, $wrapMode);
}

function gtk_label_set_selectable(int $handle, bool $setting): void
{
    ExtGtkLabel::setSelectable($handle, $setting);
}

function gtk_label_set_single_line_mode(int $handle, bool $singleLineMode): void
{
    ExtGtkLabel::setSingleLineMode($handle, $singleLineMode);
}

function gtk_label_set_text(int $handle, string $str): void
{
    ExtGtkLabel::setText($handle, $str);
}

function gtk_label_set_text_with_mnemonic(int $handle, string $str): void
{
    ExtGtkLabel::setTextWithMnemonic($handle, $str);
}

function gtk_label_set_use_markup(int $handle, bool $setting): void
{
    ExtGtkLabel::setUseMarkup($handle, $setting);
}

function gtk_label_set_use_underline(int $handle, bool $setting): void
{
    ExtGtkLabel::setUseUnderline($handle, $setting);
}

function gtk_label_set_width_chars(int $handle, int $nChars): void
{
    ExtGtkLabel::setWidthChars($handle, $nChars);
}

function gtk_label_set_wrap(int $handle, bool $wrap): void
{
    ExtGtkLabel::setWrap($handle, $wrap);
}

function gtk_label_set_wrap_mode(int $handle, int $wrapMode): void
{
    ExtGtkLabel::setWrapMode($handle, $wrapMode);
}

function gtk_label_set_xalign(int $handle, float $xalign): void
{
    ExtGtkLabel::setXalign($handle, $xalign);
}

function gtk_label_set_yalign(int $handle, float $yalign): void
{
    ExtGtkLabel::setYalign($handle, $yalign);
}
