<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkPopoverMenu\GtkPopoverMenu as ExtGtkPopoverMenu;

function gtk_popover_menu_new_from_model(int $model): int
{
    return ExtGtkPopoverMenu::newFromModel($model);
}

function gtk_popover_menu_new_from_model_full(int $model, int $flags): int
{
    return ExtGtkPopoverMenu::newFromModelFull($model, $flags);
}

function gtk_popover_menu_add_child(int $handle, int $child, string $id): bool
{
    return ExtGtkPopoverMenu::addChild($handle, $child, $id);
}

function gtk_popover_menu_get_flags(int $handle): int
{
    return ExtGtkPopoverMenu::getFlags($handle);
}

function gtk_popover_menu_get_menu_model(int $handle): int
{
    return ExtGtkPopoverMenu::getMenuModel($handle);
}

function gtk_popover_menu_remove_child(int $handle, int $child): bool
{
    return ExtGtkPopoverMenu::removeChild($handle, $child);
}

function gtk_popover_menu_set_flags(int $handle, int $flags): void
{
    ExtGtkPopoverMenu::setFlags($handle, $flags);
}

function gtk_popover_menu_set_menu_model(int $handle, int $model): void
{
    ExtGtkPopoverMenu::setMenuModel($handle, $model);
}
