<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkWindow\GtkWindow as ExtGtkWindow;

function gtk_window_new(): int
{
    return ExtGtkWindow::new_();
}

function gtk_window_get_default_icon_name(): mixed
{
    return ExtGtkWindow::getDefaultIconName();
}

function gtk_window_get_toplevels(): int
{
    return ExtGtkWindow::getToplevels();
}

function gtk_window_list_toplevels(): array
{
    return ExtGtkWindow::listToplevels();
}

function gtk_window_set_auto_startup_notification(bool $setting): void
{
    ExtGtkWindow::setAutoStartupNotification($setting);
}

function gtk_window_set_default_icon_name(string $name): void
{
    ExtGtkWindow::setDefaultIconName($name);
}

function gtk_window_set_interactive_debugging(bool $enable): void
{
    ExtGtkWindow::setInteractiveDebugging($enable);
}

function gtk_window_close(int $handle): void
{
    ExtGtkWindow::close($handle);
}

function gtk_window_destroy(int $handle): void
{
    ExtGtkWindow::destroy($handle);
}

function gtk_window_fullscreen(int $handle): void
{
    ExtGtkWindow::fullscreen($handle);
}

function gtk_window_fullscreen_on_monitor(int $handle, int $monitor): void
{
    ExtGtkWindow::fullscreenOnMonitor($handle, $monitor);
}

function gtk_window_get_application(int $handle): int
{
    return ExtGtkWindow::getApplication($handle);
}

function gtk_window_get_child(int $handle): int
{
    return ExtGtkWindow::getChild($handle);
}

function gtk_window_get_decorated(int $handle): bool
{
    return ExtGtkWindow::getDecorated($handle);
}

function gtk_window_get_default_size(int $handle): array
{
    return ExtGtkWindow::getDefaultSize($handle);
}

function gtk_window_get_default_widget(int $handle): int
{
    return ExtGtkWindow::getDefaultWidget($handle);
}

function gtk_window_get_deletable(int $handle): bool
{
    return ExtGtkWindow::getDeletable($handle);
}

function gtk_window_get_destroy_with_parent(int $handle): bool
{
    return ExtGtkWindow::getDestroyWithParent($handle);
}

function gtk_window_get_focus(int $handle): int
{
    return ExtGtkWindow::getFocus($handle);
}

function gtk_window_get_focus_visible(int $handle): bool
{
    return ExtGtkWindow::getFocusVisible($handle);
}

function gtk_window_get_group(int $handle): int
{
    return ExtGtkWindow::getGroup($handle);
}

function gtk_window_get_handle_menubar_accel(int $handle): bool
{
    return ExtGtkWindow::getHandleMenubarAccel($handle);
}

function gtk_window_get_hide_on_close(int $handle): bool
{
    return ExtGtkWindow::getHideOnClose($handle);
}

function gtk_window_get_icon_name(int $handle): mixed
{
    return ExtGtkWindow::getIconName($handle);
}

function gtk_window_get_mnemonics_visible(int $handle): bool
{
    return ExtGtkWindow::getMnemonicsVisible($handle);
}

function gtk_window_get_modal(int $handle): bool
{
    return ExtGtkWindow::getModal($handle);
}

function gtk_window_get_resizable(int $handle): bool
{
    return ExtGtkWindow::getResizable($handle);
}

function gtk_window_get_title(int $handle): mixed
{
    return ExtGtkWindow::getTitle($handle);
}

function gtk_window_get_titlebar(int $handle): int
{
    return ExtGtkWindow::getTitlebar($handle);
}

function gtk_window_get_transient_for(int $handle): int
{
    return ExtGtkWindow::getTransientFor($handle);
}

function gtk_window_has_group(int $handle): bool
{
    return ExtGtkWindow::hasGroup($handle);
}

function gtk_window_is_active(int $handle): bool
{
    return ExtGtkWindow::isActive($handle);
}

function gtk_window_is_fullscreen(int $handle): bool
{
    return ExtGtkWindow::isFullscreen($handle);
}

function gtk_window_is_maximized(int $handle): bool
{
    return ExtGtkWindow::isMaximized($handle);
}

function gtk_window_is_suspended(int $handle): bool
{
    return ExtGtkWindow::isSuspended($handle);
}

function gtk_window_maximize(int $handle): void
{
    ExtGtkWindow::maximize($handle);
}

function gtk_window_minimize(int $handle): void
{
    ExtGtkWindow::minimize($handle);
}

function gtk_window_present(int $handle): void
{
    ExtGtkWindow::present($handle);
}

function gtk_window_set_application(int $handle, int $application): void
{
    ExtGtkWindow::setApplication($handle, $application);
}

function gtk_window_set_child(int $handle, int $child): void
{
    ExtGtkWindow::setChild($handle, $child);
}

function gtk_window_set_decorated(int $handle, bool $setting): void
{
    ExtGtkWindow::setDecorated($handle, $setting);
}

function gtk_window_set_default_size(int $handle, int $width, int $height): void
{
    ExtGtkWindow::setDefaultSize($handle, $width, $height);
}

function gtk_window_set_default_widget(int $handle, int $defaultWidget): void
{
    ExtGtkWindow::setDefaultWidget($handle, $defaultWidget);
}

function gtk_window_set_deletable(int $handle, bool $setting): void
{
    ExtGtkWindow::setDeletable($handle, $setting);
}

function gtk_window_set_destroy_with_parent(int $handle, bool $setting): void
{
    ExtGtkWindow::setDestroyWithParent($handle, $setting);
}

function gtk_window_set_display(int $handle, int $display): void
{
    ExtGtkWindow::setDisplay($handle, $display);
}

function gtk_window_set_focus(int $handle, int $focus): void
{
    ExtGtkWindow::setFocus($handle, $focus);
}

function gtk_window_set_focus_visible(int $handle, bool $setting): void
{
    ExtGtkWindow::setFocusVisible($handle, $setting);
}

function gtk_window_set_handle_menubar_accel(int $handle, bool $handleMenubarAccel): void
{
    ExtGtkWindow::setHandleMenubarAccel($handle, $handleMenubarAccel);
}

function gtk_window_set_hide_on_close(int $handle, bool $setting): void
{
    ExtGtkWindow::setHideOnClose($handle, $setting);
}

function gtk_window_set_icon_name(int $handle, mixed $name): void
{
    ExtGtkWindow::setIconName($handle, $name);
}

function gtk_window_set_mnemonics_visible(int $handle, bool $setting): void
{
    ExtGtkWindow::setMnemonicsVisible($handle, $setting);
}

function gtk_window_set_modal(int $handle, bool $modal): void
{
    ExtGtkWindow::setModal($handle, $modal);
}

function gtk_window_set_resizable(int $handle, bool $resizable): void
{
    ExtGtkWindow::setResizable($handle, $resizable);
}

function gtk_window_set_startup_id(int $handle, string $startupId): void
{
    ExtGtkWindow::setStartupId($handle, $startupId);
}

function gtk_window_set_title(int $handle, mixed $title): void
{
    ExtGtkWindow::setTitle($handle, $title);
}

function gtk_window_set_titlebar(int $handle, int $titlebar): void
{
    ExtGtkWindow::setTitlebar($handle, $titlebar);
}

function gtk_window_set_transient_for(int $handle, int $parent): void
{
    ExtGtkWindow::setTransientFor($handle, $parent);
}

function gtk_window_unfullscreen(int $handle): void
{
    ExtGtkWindow::unfullscreen($handle);
}

function gtk_window_unmaximize(int $handle): void
{
    ExtGtkWindow::unmaximize($handle);
}

function gtk_window_unminimize(int $handle): void
{
    ExtGtkWindow::unminimize($handle);
}
