<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkFixed\GtkFixed as ExtGtkFixed;

function gtk_fixed_new(): int
{
    return ExtGtkFixed::new_();
}

function gtk_fixed_get_child_position(int $handle, int $widget): array
{
    return ExtGtkFixed::getChildPosition($handle, $widget);
}

function gtk_fixed_move(int $handle, int $widget, float $x, float $y): void
{
    ExtGtkFixed::move($handle, $widget, $x, $y);
}

function gtk_fixed_put(int $handle, int $widget, float $x, float $y): void
{
    ExtGtkFixed::put($handle, $widget, $x, $y);
}

function gtk_fixed_remove(int $handle, int $widget): void
{
    ExtGtkFixed::remove($handle, $widget);
}
