<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkEntry\GtkEntry as ExtGtkEntry;

function gtk_entry_new(): int
{
    return ExtGtkEntry::new_();
}

function gtk_entry_new_with_buffer(int $buffer): int
{
    return ExtGtkEntry::newWithBuffer($buffer);
}

function gtk_entry_get_activates_default(int $handle): bool
{
    return ExtGtkEntry::getActivatesDefault($handle);
}

function gtk_entry_get_alignment(int $handle): float
{
    return ExtGtkEntry::getAlignment($handle);
}

function gtk_entry_get_buffer(int $handle): int
{
    return ExtGtkEntry::getBuffer($handle);
}

function gtk_entry_get_current_icon_drag_source(int $handle): int
{
    return ExtGtkEntry::getCurrentIconDragSource($handle);
}

function gtk_entry_get_extra_menu(int $handle): int
{
    return ExtGtkEntry::getExtraMenu($handle);
}

function gtk_entry_get_has_frame(int $handle): bool
{
    return ExtGtkEntry::getHasFrame($handle);
}

function gtk_entry_get_icon_activatable(int $handle, int $iconPos): bool
{
    return ExtGtkEntry::getIconActivatable($handle, $iconPos);
}

function gtk_entry_get_icon_area(int $handle, int $iconPos): array
{
    return ExtGtkEntry::getIconArea($handle, $iconPos);
}

function gtk_entry_get_icon_at_pos(int $handle, int $x, int $y): int
{
    return ExtGtkEntry::getIconAtPos($handle, $x, $y);
}

function gtk_entry_get_icon_gicon(int $handle, int $iconPos): int
{
    return ExtGtkEntry::getIconGicon($handle, $iconPos);
}

function gtk_entry_get_icon_name(int $handle, int $iconPos): mixed
{
    return ExtGtkEntry::getIconName($handle, $iconPos);
}

function gtk_entry_get_icon_paintable(int $handle, int $iconPos): int
{
    return ExtGtkEntry::getIconPaintable($handle, $iconPos);
}

function gtk_entry_get_icon_sensitive(int $handle, int $iconPos): bool
{
    return ExtGtkEntry::getIconSensitive($handle, $iconPos);
}

function gtk_entry_get_icon_storage_type(int $handle, int $iconPos): int
{
    return ExtGtkEntry::getIconStorageType($handle, $iconPos);
}

function gtk_entry_get_icon_tooltip_markup(int $handle, int $iconPos): mixed
{
    return ExtGtkEntry::getIconTooltipMarkup($handle, $iconPos);
}

function gtk_entry_get_icon_tooltip_text(int $handle, int $iconPos): mixed
{
    return ExtGtkEntry::getIconTooltipText($handle, $iconPos);
}

function gtk_entry_get_input_hints(int $handle): int
{
    return ExtGtkEntry::getInputHints($handle);
}

function gtk_entry_get_input_purpose(int $handle): int
{
    return ExtGtkEntry::getInputPurpose($handle);
}

function gtk_entry_get_invisible_char(int $handle): int
{
    return ExtGtkEntry::getInvisibleChar($handle);
}

function gtk_entry_get_max_length(int $handle): int
{
    return ExtGtkEntry::getMaxLength($handle);
}

function gtk_entry_get_overwrite_mode(int $handle): bool
{
    return ExtGtkEntry::getOverwriteMode($handle);
}

function gtk_entry_get_placeholder_text(int $handle): mixed
{
    return ExtGtkEntry::getPlaceholderText($handle);
}

function gtk_entry_get_progress_fraction(int $handle): float
{
    return ExtGtkEntry::getProgressFraction($handle);
}

function gtk_entry_get_progress_pulse_step(int $handle): float
{
    return ExtGtkEntry::getProgressPulseStep($handle);
}

function gtk_entry_get_text_length(int $handle): int
{
    return ExtGtkEntry::getTextLength($handle);
}

function gtk_entry_get_visibility(int $handle): bool
{
    return ExtGtkEntry::getVisibility($handle);
}

function gtk_entry_grab_focus_without_selecting(int $handle): bool
{
    return ExtGtkEntry::grabFocusWithoutSelecting($handle);
}

function gtk_entry_progress_pulse(int $handle): void
{
    ExtGtkEntry::progressPulse($handle);
}

function gtk_entry_reset_im_context(int $handle): void
{
    ExtGtkEntry::resetImContext($handle);
}

function gtk_entry_set_activates_default(int $handle, bool $setting): void
{
    ExtGtkEntry::setActivatesDefault($handle, $setting);
}

function gtk_entry_set_alignment(int $handle, float $xalign): void
{
    ExtGtkEntry::setAlignment($handle, $xalign);
}

function gtk_entry_set_buffer(int $handle, int $buffer): void
{
    ExtGtkEntry::setBuffer($handle, $buffer);
}

function gtk_entry_set_extra_menu(int $handle, int $model): void
{
    ExtGtkEntry::setExtraMenu($handle, $model);
}

function gtk_entry_set_has_frame(int $handle, bool $setting): void
{
    ExtGtkEntry::setHasFrame($handle, $setting);
}

function gtk_entry_set_icon_activatable(int $handle, int $iconPos, bool $activatable): void
{
    ExtGtkEntry::setIconActivatable($handle, $iconPos, $activatable);
}

function gtk_entry_set_icon_from_gicon(int $handle, int $iconPos, int $icon): void
{
    ExtGtkEntry::setIconFromGicon($handle, $iconPos, $icon);
}

function gtk_entry_set_icon_from_icon_name(int $handle, int $iconPos, mixed $iconName): void
{
    ExtGtkEntry::setIconFromIconName($handle, $iconPos, $iconName);
}

function gtk_entry_set_icon_from_paintable(int $handle, int $iconPos, int $paintable): void
{
    ExtGtkEntry::setIconFromPaintable($handle, $iconPos, $paintable);
}

function gtk_entry_set_icon_sensitive(int $handle, int $iconPos, bool $sensitive): void
{
    ExtGtkEntry::setIconSensitive($handle, $iconPos, $sensitive);
}

function gtk_entry_set_icon_tooltip_markup(int $handle, int $iconPos, mixed $tooltip): void
{
    ExtGtkEntry::setIconTooltipMarkup($handle, $iconPos, $tooltip);
}

function gtk_entry_set_icon_tooltip_text(int $handle, int $iconPos, mixed $tooltip): void
{
    ExtGtkEntry::setIconTooltipText($handle, $iconPos, $tooltip);
}

function gtk_entry_set_input_hints(int $handle, int $hints): void
{
    ExtGtkEntry::setInputHints($handle, $hints);
}

function gtk_entry_set_input_purpose(int $handle, int $purpose): void
{
    ExtGtkEntry::setInputPurpose($handle, $purpose);
}

function gtk_entry_set_invisible_char(int $handle, int $ch): void
{
    ExtGtkEntry::setInvisibleChar($handle, $ch);
}

function gtk_entry_set_max_length(int $handle, int $max): void
{
    ExtGtkEntry::setMaxLength($handle, $max);
}

function gtk_entry_set_overwrite_mode(int $handle, bool $overwrite): void
{
    ExtGtkEntry::setOverwriteMode($handle, $overwrite);
}

function gtk_entry_set_placeholder_text(int $handle, mixed $text): void
{
    ExtGtkEntry::setPlaceholderText($handle, $text);
}

function gtk_entry_set_progress_fraction(int $handle, float $fraction): void
{
    ExtGtkEntry::setProgressFraction($handle, $fraction);
}

function gtk_entry_set_progress_pulse_step(int $handle, float $fraction): void
{
    ExtGtkEntry::setProgressPulseStep($handle, $fraction);
}

function gtk_entry_set_visibility(int $handle, bool $visible): void
{
    ExtGtkEntry::setVisibility($handle, $visible);
}

function gtk_entry_unset_invisible_char(int $handle): void
{
    ExtGtkEntry::unsetInvisibleChar($handle);
}
