<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

use Gtk\Gtk\GtkFlowBox\GtkFlowBox as ExtGtkFlowBox;

function gtk_flow_box_new(): int
{
    return ExtGtkFlowBox::new_();
}

function gtk_flow_box_append(int $handle, int $child): void
{
    ExtGtkFlowBox::append($handle, $child);
}

function gtk_flow_box_get_activate_on_single_click(int $handle): bool
{
    return ExtGtkFlowBox::getActivateOnSingleClick($handle);
}

function gtk_flow_box_get_child_at_index(int $handle, int $idx): int
{
    return ExtGtkFlowBox::getChildAtIndex($handle, $idx);
}

function gtk_flow_box_get_child_at_pos(int $handle, int $x, int $y): int
{
    return ExtGtkFlowBox::getChildAtPos($handle, $x, $y);
}

function gtk_flow_box_get_column_spacing(int $handle): int
{
    return ExtGtkFlowBox::getColumnSpacing($handle);
}

function gtk_flow_box_get_homogeneous(int $handle): bool
{
    return ExtGtkFlowBox::getHomogeneous($handle);
}

function gtk_flow_box_get_max_children_per_line(int $handle): int
{
    return ExtGtkFlowBox::getMaxChildrenPerLine($handle);
}

function gtk_flow_box_get_min_children_per_line(int $handle): int
{
    return ExtGtkFlowBox::getMinChildrenPerLine($handle);
}

function gtk_flow_box_get_row_spacing(int $handle): int
{
    return ExtGtkFlowBox::getRowSpacing($handle);
}

function gtk_flow_box_get_selected_children(int $handle): array
{
    return ExtGtkFlowBox::getSelectedChildren($handle);
}

function gtk_flow_box_get_selection_mode(int $handle): int
{
    return ExtGtkFlowBox::getSelectionMode($handle);
}

function gtk_flow_box_insert(int $handle, int $widget, int $position): void
{
    ExtGtkFlowBox::insert($handle, $widget, $position);
}

function gtk_flow_box_invalidate_filter(int $handle): void
{
    ExtGtkFlowBox::invalidateFilter($handle);
}

function gtk_flow_box_invalidate_sort(int $handle): void
{
    ExtGtkFlowBox::invalidateSort($handle);
}

function gtk_flow_box_prepend(int $handle, int $child): void
{
    ExtGtkFlowBox::prepend($handle, $child);
}

function gtk_flow_box_remove(int $handle, int $widget): void
{
    ExtGtkFlowBox::remove($handle, $widget);
}

function gtk_flow_box_remove_all(int $handle): void
{
    ExtGtkFlowBox::removeAll($handle);
}

function gtk_flow_box_select_all(int $handle): void
{
    ExtGtkFlowBox::selectAll($handle);
}

function gtk_flow_box_select_child(int $handle, int $child): void
{
    ExtGtkFlowBox::selectChild($handle, $child);
}

function gtk_flow_box_set_activate_on_single_click(int $handle, bool $single): void
{
    ExtGtkFlowBox::setActivateOnSingleClick($handle, $single);
}

function gtk_flow_box_set_column_spacing(int $handle, int $spacing): void
{
    ExtGtkFlowBox::setColumnSpacing($handle, $spacing);
}

function gtk_flow_box_set_hadjustment(int $handle, int $adjustment): void
{
    ExtGtkFlowBox::setHadjustment($handle, $adjustment);
}

function gtk_flow_box_set_homogeneous(int $handle, bool $homogeneous): void
{
    ExtGtkFlowBox::setHomogeneous($handle, $homogeneous);
}

function gtk_flow_box_set_max_children_per_line(int $handle, int $nChildren): void
{
    ExtGtkFlowBox::setMaxChildrenPerLine($handle, $nChildren);
}

function gtk_flow_box_set_min_children_per_line(int $handle, int $nChildren): void
{
    ExtGtkFlowBox::setMinChildrenPerLine($handle, $nChildren);
}

function gtk_flow_box_set_row_spacing(int $handle, int $spacing): void
{
    ExtGtkFlowBox::setRowSpacing($handle, $spacing);
}

function gtk_flow_box_set_selection_mode(int $handle, int $mode): void
{
    ExtGtkFlowBox::setSelectionMode($handle, $mode);
}

function gtk_flow_box_set_vadjustment(int $handle, int $adjustment): void
{
    ExtGtkFlowBox::setVadjustment($handle, $adjustment);
}

function gtk_flow_box_unselect_all(int $handle): void
{
    ExtGtkFlowBox::unselectAll($handle);
}

function gtk_flow_box_unselect_child(int $handle, int $child): void
{
    ExtGtkFlowBox::unselectChild($handle, $child);
}
