<?php

declare(strict_types=1);

use Jovian\Bindings\Gtk\Enums\GApplicationFlags;
use Jovian\Bindings\Gtk\Enums\GtkAlign;
use Jovian\Bindings\Gtk\Enums\GtkLicense;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;
use Jovian\Bindings\Gtk\Enums\GtkStateFlags;

it('emits int-backed enums with FULLY UPPERCASE cases and no class constants', function (): void {
    $files = glob(dirname(__DIR__, 2) . '/src/Enums/*.php') ?: [];
    expect($files)->not->toBeEmpty();

    foreach ($files as $file) {
        $source = (string) file_get_contents($file);
        expect($source)->toContain('GENERATED by scripts/generate.php')
            ->and($source)->toMatch('/enum\s+\w+\s*:\s*int/')
            ->and($source)->not->toMatch('/\bconst\s+/');

        preg_match_all('/case\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/', $source, $matches);
        expect($matches[1])->not->toBeEmpty();
        foreach ($matches[1] as $case) {
            expect($case)->toMatch('/^[A-Z][A-Z0-9_]*$/');
        }
    }
});

it('projects GtkOrientation from the GIR members horizontal and vertical', function (): void {
    expect(GtkOrientation::HORIZONTAL->value)->toBe(0)
        ->and(GtkOrientation::VERTICAL->value)->toBe(1);
});

it('prefixes a leading-digit GIR member so PHP can parse GtkLicense::N_0BSD', function (): void {
    expect(GtkLicense::N_0BSD->name)->toBe('N_0BSD');
});

it('skips GIR aliases that would duplicate a backed value', function (): void {
    $alignCases = array_map(static fn (GtkAlign $case): int => $case->value, GtkAlign::cases());
    expect($alignCases)->toHaveCount(count(array_unique($alignCases)));

    $flagCases = array_map(static fn (GApplicationFlags $case): int => $case->value, GApplicationFlags::cases());
    expect($flagCases)->toHaveCount(count(array_unique($flagCases)));
});

it('keeps bitfields as int-backed enums whose generated files say parameters stay int', function (): void {
    $path = dirname(__DIR__, 2) . '/src/Enums/GtkStateFlags.php';
    $source = (string) file_get_contents($path);
    expect($source)->toContain('GIR bitfield')
        ->and($source)->toContain("PHP enums cannot be OR'd")
        ->and(GtkStateFlags::NORMAL->value)->toBe(0);
});
