<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/scripts/lib/emit.php';

use Jovian\Bindings\Gtk\Enums\GdkGLAPI;

/*
 * The GL wave (ext-gtk 0.8.1) projects GtkGLArea and GdkGLContext — the
 * latter being the first Gdk class, and the first one to land in its own
 * src/Gdk/ tree. These gates pin the shape the windowed GL proof depends
 * on.
 */

it('emits the GL DTOs and helpers on the GIR kebab path', function (): void {
    $root = dirname(__DIR__, 2);

    $pairs = [
        ['Gtk\\GtkGLArea', 'src/Gtk/GtkGLArea.php', 'src/Helpers/gtk-gl-area.php'],
        ['Gdk\\GdkGLContext', 'src/Gdk/GdkGLContext.php', 'src/Helpers/gdk-gl-context.php'],
    ];

    foreach ($pairs as [$classPath, $dtoRel, $helperRel]) {
        expect(helperRelPath($classPath))->toBe($helperRel);

        expect(is_file($root . '/' . $dtoRel))->toBeTrue("missing GL DTO {$dtoRel}");
        expect(is_file($root . '/' . $helperRel))->toBeTrue("missing GL helper {$helperRel}");

        $dtoText = (string) file_get_contents($root . '/' . $dtoRel);
        expect($dtoText)->toContain('GENERATED by scripts/generate.php')
            ->and($dtoText)->toContain(' as Ext');
    }
});

it('autoloads the first Gdk class out of the new src/Gdk tree', function (): void {
    expect(class_exists(\Jovian\Bindings\Gtk\Gdk\GdkGLContext::class))->toBeTrue()
        ->and(class_exists(\Jovian\Bindings\Gtk\Gtk\GtkGLArea::class))->toBeTrue();

    $reflection = new ReflectionClass(\Jovian\Bindings\Gtk\Gdk\GdkGLContext::class);
    expect($reflection->getFileName())->toContain('/src/Gdk/GdkGLContext.php');
});

it('gives GtkGLArea a constructor and GdkGLContext none, because the GIR says abstract', function (): void {
    $area = new ReflectionClass(\Jovian\Bindings\Gtk\Gtk\GtkGLArea::class);
    $context = new ReflectionClass(\Jovian\Bindings\Gtk\Gdk\GdkGLContext::class);

    expect($area->hasMethod('new'))->toBeTrue()
        ->and($area->getParentClass()->getName())->toBe(\Jovian\Bindings\Gtk\Gtk\GtkWidget::class);

    // Abstract in the GIR: you obtain one, never construct it.
    expect($context->hasMethod('new'))->toBeFalse()
        ->and($context->getParentClass()->getName())->toBe(\Jovian\Bindings\Gtk\Runtime\GObject::class);

    // The two GIR <function> members stay static — they take no handle.
    foreach (['clearCurrent', 'getCurrent'] as $static) {
        expect($context->hasMethod($static))->toBeTrue("GdkGLContext::{$static} missing");
        expect($context->getMethod($static)->isStatic())->toBeTrue("GdkGLContext::{$static} is not static");
    }
});

it('projects all three GtkGLArea signals, render included', function (): void {
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Gtk/GtkGLArea.php');

    $signals = [
        'onRender' => 'render',
        'onResize' => 'resize',
        'onCreateContext' => 'create-context',
    ];

    foreach ($signals as $method => $signal) {
        expect($text)->toContain("public function {$method}(callable \$callback): int")
            ->and($text)->toContain("Bridge::connect(\$this->handle, '{$signal}'");
    }
});

it('returns the version out-params as {major, minor} on both GL classes', function (): void {
    $root = dirname(__DIR__, 2);
    $area = (string) file_get_contents($root . '/src/Gtk/GtkGLArea.php');
    $context = (string) file_get_contents($root . '/src/Gdk/GdkGLContext.php');

    expect($area)->toContain('public function getRequiredVersion(): array')
        ->and($area)->toContain('array{major: mixed, minor: mixed}');

    expect($context)->toContain('public function getVersion(): array')
        ->and($context)->toContain('public function getRequiredVersion(): array');
});

it('keeps GdkGLAPI a bitfield enum whose parameters stay int', function (): void {
    // GIR bitfield: parameters stay int because PHP enums cannot be OR'd.
    expect(GdkGLAPI::GL->value)->toBe(1)
        ->and(GdkGLAPI::GLES->value)->toBe(2)
        ->and(GdkGLAPI::cases())->toHaveCount(2);

    $area = new ReflectionClass(\Jovian\Bindings\Gtk\Gtk\GtkGLArea::class);
    $apis = $area->getMethod('setAllowedApis')->getParameters()[0];
    expect((string) $apis->getType())->toBe('int');
});

it('agrees with the vendored GIR on the GtkGLArea member count', function (): void {
    $gir = gtkExtRoot() . '/scripts/gir/Gtk-4.0.gir.gz';
    expect(is_file($gir))->toBeTrue();

    $xml = gzdecode((string) file_get_contents($gir));
    $doc = new DOMDocument();
    $doc->loadXML((string) $xml, LIBXML_NONET | LIBXML_COMPACT);
    $xp = new DOMXPath($doc);
    $xp->registerNamespace('gir', 'http://www.gtk.org/introspection/core/1.0');
    $xp->registerNamespace('c', 'http://www.gtk.org/introspection/c/1.0');

    $nodes = $xp->query('//gir:class[@c:type="GtkGLArea"]');
    expect($nodes->length)->toBe(1);

    $class = $nodes->item(0);
    $signals = $xp->query('glib:signal', $class);
    // 3 signals in the GIR, 3 on* methods in the DTO.
    $text = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Gtk/GtkGLArea.php');
    expect(preg_match_all('/public function on[A-Za-z]+\(callable /', $text))->toBe(3);
});
