<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/scripts/lib/emit.php';

$spine = [
    ['Gtk\\GtkWidget', 'src/Gtk/GtkWidget.php', 'src/Helpers/gtk-widget.php'],
    ['Gtk\\GtkWindow', 'src/Gtk/GtkWindow.php', 'src/Helpers/gtk-window.php'],
    ['Gtk\\GtkApplication', 'src/Gtk/GtkApplication.php', 'src/Helpers/gtk-application.php'],
    ['Gtk\\GtkApplicationWindow', 'src/Gtk/GtkApplicationWindow.php', 'src/Helpers/gtk-application-window.php'],
    ['Gtk\\GtkBox', 'src/Gtk/GtkBox.php', 'src/Helpers/gtk-box.php'],
    ['Gtk\\GtkButton', 'src/Gtk/GtkButton.php', 'src/Helpers/gtk-button.php'],
    ['Gtk\\GtkLabel', 'src/Gtk/GtkLabel.php', 'src/Helpers/gtk-label.php'],
    ['Gio\\GApplication', 'src/Gio/GApplication.php', 'src/Helpers/g-application.php'],
];

it('autoloads a spine DTO that uses a generated interface trait', function (): void {
    expect(class_exists(\Jovian\Bindings\Gtk\Gtk\GtkBox::class))->toBeTrue()
        ->and(trait_exists(\Jovian\Bindings\Gtk\Contracts\GtkOrientableMethods::class))->toBeTrue()
        ->and(class_exists(\Jovian\Bindings\Gtk\Gtk\GtkButton::class))->toBeTrue();
});

it('keeps the handwritten Runtime\\GObject as the spine root', function (): void {
    $path = dirname(__DIR__, 2) . '/src/Runtime/GObject.php';
    expect(is_file($path))->toBeTrue();
    $text = (string) file_get_contents($path);
    expect($text)->toContain('class GObject')
        ->and($text)->toContain('public readonly int $handle')
        ->and($text)->not->toContain('GENERATED by scripts/generate.php');
});

it('emits every spine DTO and helper on the GIR kebab path', function () use ($spine): void {
    $root = dirname(__DIR__, 2);

    foreach ($spine as [$classPath, $dtoRel, $helperRel]) {
        expect(helperRelPath($classPath))->toBe($helperRel);

        $dto = $root . '/' . $dtoRel;
        $helper = $root . '/' . $helperRel;
        expect(is_file($dto))->toBeTrue("missing spine DTO {$dtoRel}");
        expect(is_file($helper))->toBeTrue("missing spine helper {$helperRel}");

        $dtoText = (string) file_get_contents($dto);
        $helperText = (string) file_get_contents($helper);
        expect($dtoText)->toContain('GENERATED by scripts/generate.php')
            ->and($dtoText)->toContain(' as Ext')
            ->and($helperText)->toContain('GENERATED by scripts/generate.php')
            ->and($helperText)->toContain(' as Ext');
    }
});

it('exposes DTO new() and the GIR-declared clicked and close-request projections', function (): void {
    $root = dirname(__DIR__, 2);
    $button = (string) file_get_contents($root . '/src/Gtk/GtkButton.php');
    $window = (string) file_get_contents($root . '/src/Gtk/GtkWindow.php');
    $appWindow = (string) file_get_contents($root . '/src/Gtk/GtkApplicationWindow.php');

    expect($button)->toContain('public static function new()')
        ->and($button)->toContain('ExtGtkButton::new_()')
        ->and($button)->toContain("Bridge::connect(\$this->handle, 'clicked'")
        ->and($button)->toContain('public function onClicked(callable $callback): int');

    expect($window)->toContain('public static function new()')
        ->and($window)->toContain("Bridge::connect(\$this->handle, 'close-request'")
        ->and($window)->toContain('public function onCloseRequest(callable $callback): int');

    expect($appWindow)->toContain('public static function new(?GtkApplication $application = null): self')
        ->and($appWindow)->toContain('is_null($application)')
        ->and($appWindow)->toContain('$application->handle');
});

it('names spine helpers from the GIR c:identifier and keeps them int-in / int-out', function (): void {
    $root = dirname(__DIR__, 2);

    $button = (string) file_get_contents($root . '/src/Helpers/gtk-button.php');
    expect($button)->toContain('function gtk_button_new(): int')
        ->and($button)->toContain('function gtk_button_set_label(int $handle, string $label): void')
        ->and($button)->toContain('function gtk_button_new_with_label(string $label): int');

    $window = (string) file_get_contents($root . '/src/Helpers/gtk-window.php');
    expect($window)->toContain('function gtk_window_new(): int')
        ->and($window)->toContain('function gtk_window_set_title(int $handle, mixed $title): void');

    $box = (string) file_get_contents($root . '/src/Helpers/gtk-box.php');
    expect($box)->toContain('function gtk_box_new(int $orientation, int $spacing): int');

    $label = (string) file_get_contents($root . '/src/Helpers/gtk-label.php');
    expect($label)->toContain('function gtk_label_new(mixed $str): int');

    $appWindow = (string) file_get_contents($root . '/src/Helpers/gtk-application-window.php');
    expect($appWindow)->toContain('function gtk_application_window_new(int $application): int');

    $gApp = (string) file_get_contents($root . '/src/Helpers/g-application.php');
    expect($gApp)->toContain('function g_application_new(mixed $applicationId, int $flags): int');
});
