<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gio\GAction\GAction as ExtGAction;

interface GAction
{
    public static function nameIsValid(string $actionName): bool;

    public function getEnabled(): bool;

    public function getName(): ?string;
}

trait GActionMethods
{
    public static function nameIsValid(string $actionName): bool
    {
        return ExtGAction::nameIsValid($actionName);
    }

    public function getEnabled(): bool
    {
        return ExtGAction::getEnabled($this->handle);
    }

    public function getName(): ?string
    {
        return ExtGAction::getName($this->handle);
    }
}
