<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gio\GActionMap\GActionMap as ExtGActionMap;
use Jovian\Bindings\Gtk\Contracts\GAction;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

interface GActionMap
{
    public function addAction(GAction $action): static;

    public function lookupAction(string $actionName): ?GObject;

    public function removeAction(string $actionName): static;
}

trait GActionMapMethods
{
    public function addAction(GAction $action): static
    {
        ExtGActionMap::addAction($this->handle, $action->handle);

        return $this;
    }

    public function lookupAction(string $actionName): ?GObject
    {
        return Registry::box(ExtGActionMap::lookupAction($this->handle, $actionName));
    }

    public function removeAction(string $actionName): static
    {
        ExtGActionMap::removeAction($this->handle, $actionName);

        return $this;
    }
}
