<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gtk\GtkActionable\GtkActionable as ExtGtkActionable;

interface GtkActionable
{
    public function getActionName(): ?string;

    public function setActionName(mixed $actionName): static;

    public function setDetailedActionName(string $detailedActionName): static;
}

trait GtkActionableMethods
{
    public function getActionName(): ?string
    {
        return ExtGtkActionable::getActionName($this->handle);
    }

    public function setActionName(mixed $actionName): static
    {
        ExtGtkActionable::setActionName($this->handle, $actionName);

        return $this;
    }

    public function setDetailedActionName(string $detailedActionName): static
    {
        ExtGtkActionable::setDetailedActionName($this->handle, $detailedActionName);

        return $this;
    }
}
