<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gtk\GtkOrientable\GtkOrientable as ExtGtkOrientable;
use Jovian\Bindings\Gtk\Enums\GtkOrientation;

interface GtkOrientable
{
    public function getOrientation(): int;

    public function setOrientation(GtkOrientation|int $orientation): static;
}

trait GtkOrientableMethods
{
    public function getOrientation(): int
    {
        return ExtGtkOrientable::getOrientation($this->handle);
    }

    public function setOrientation(GtkOrientation|int $orientation): static
    {
        ExtGtkOrientable::setOrientation($this->handle, ($orientation instanceof GtkOrientation ? $orientation->value : $orientation));

        return $this;
    }
}
