<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gtk\GtkSelectionModel\GtkSelectionModel as ExtGtkSelectionModel;
use Jovian\Bindings\Gtk\Runtime\Bridge;

interface GtkSelectionModel
{
    public function isSelected(int $position): bool;

    public function selectAll(): bool;

    public function selectItem(int $position, bool $unselectRest): bool;

    public function selectRange(int $position, int $nItems, bool $unselectRest): bool;

    public function selectionChanged(int $position, int $nItems): static;

    public function unselectAll(): bool;

    public function unselectItem(int $position): bool;

    public function unselectRange(int $position, int $nItems): bool;

    public function onSelectionChanged(callable $callback): int;
}

trait GtkSelectionModelMethods
{
    public function isSelected(int $position): bool
    {
        return ExtGtkSelectionModel::isSelected($this->handle, $position);
    }

    public function selectAll(): bool
    {
        return ExtGtkSelectionModel::selectAll($this->handle);
    }

    public function selectItem(int $position, bool $unselectRest): bool
    {
        return ExtGtkSelectionModel::selectItem($this->handle, $position, $unselectRest);
    }

    public function selectRange(int $position, int $nItems, bool $unselectRest): bool
    {
        return ExtGtkSelectionModel::selectRange($this->handle, $position, $nItems, $unselectRest);
    }

    public function selectionChanged(int $position, int $nItems): static
    {
        ExtGtkSelectionModel::selectionChanged($this->handle, $position, $nItems);

        return $this;
    }

    public function unselectAll(): bool
    {
        return ExtGtkSelectionModel::unselectAll($this->handle);
    }

    public function unselectItem(int $position): bool
    {
        return ExtGtkSelectionModel::unselectItem($this->handle, $position);
    }

    public function unselectRange(int $position, int $nItems): bool
    {
        return ExtGtkSelectionModel::unselectRange($this->handle, $position, $nItems);
    }

    public function onSelectionChanged(callable $callback): int
    {
        return Bridge::connect($this->handle, 'selection-changed', $callback);
    }
}
