<?php

declare(strict_types=1);

/* GENERATED by scripts/generate.php — DO NOT EDIT. */

namespace Jovian\Bindings\Gtk\Contracts;

use Gtk\Gtk\GtkScrollable\GtkScrollable as ExtGtkScrollable;
use Jovian\Bindings\Gtk\Enums\GtkScrollablePolicy;
use Jovian\Bindings\Gtk\Gtk\GtkAdjustment;
use Jovian\Bindings\Gtk\Runtime\GObject;
use Jovian\Bindings\Gtk\Runtime\Registry;

interface GtkScrollable
{
    public function getBorder(): array;

    public function getHadjustment(): ?GObject;

    public function getHscrollPolicy(): int;

    public function getVadjustment(): ?GObject;

    public function getVscrollPolicy(): int;

    public function setHadjustment(?GtkAdjustment $hadjustment): static;

    public function setHscrollPolicy(GtkScrollablePolicy|int $policy): static;

    public function setVadjustment(?GtkAdjustment $vadjustment): static;

    public function setVscrollPolicy(GtkScrollablePolicy|int $policy): static;
}

trait GtkScrollableMethods
{
    public function getBorder(): array
    {
        return ExtGtkScrollable::getBorder($this->handle);
    }

    public function getHadjustment(): ?GObject
    {
        return Registry::box(ExtGtkScrollable::getHadjustment($this->handle));
    }

    public function getHscrollPolicy(): int
    {
        return ExtGtkScrollable::getHscrollPolicy($this->handle);
    }

    public function getVadjustment(): ?GObject
    {
        return Registry::box(ExtGtkScrollable::getVadjustment($this->handle));
    }

    public function getVscrollPolicy(): int
    {
        return ExtGtkScrollable::getVscrollPolicy($this->handle);
    }

    public function setHadjustment(?GtkAdjustment $hadjustment): static
    {
        ExtGtkScrollable::setHadjustment($this->handle, (is_null($hadjustment) ? 0 : $hadjustment->handle));

        return $this;
    }

    public function setHscrollPolicy(GtkScrollablePolicy|int $policy): static
    {
        ExtGtkScrollable::setHscrollPolicy($this->handle, ($policy instanceof GtkScrollablePolicy ? $policy->value : $policy));

        return $this;
    }

    public function setVadjustment(?GtkAdjustment $vadjustment): static
    {
        ExtGtkScrollable::setVadjustment($this->handle, (is_null($vadjustment) ? 0 : $vadjustment->handle));

        return $this;
    }

    public function setVscrollPolicy(GtkScrollablePolicy|int $policy): static
    {
        ExtGtkScrollable::setVscrollPolicy($this->handle, ($policy instanceof GtkScrollablePolicy ? $policy->value : $policy));

        return $this;
    }
}
